// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task/v1/commit.proto

package types

import (
	fmt "fmt"
	_ "github.com/TrueOpen/node/x/shared/types"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CommitStatusV1 is the lifecycle of one accepted verifier commit row.
//
// CONTRACT-GAP: keeper_data_structure_contract.md §6.6 declares CommitState.status =
// ACCEPTED as the only value, and keeper_api_contract.md §9.6b does not register this
// enum. The single non-zero value below is exactly what the frozen schema names.
// CommitStatusV1 defines the CommitStatusV1 wire type.
type CommitStatusV1 int32

const (
	// Never written; rejects zero-value rows.
	// COMMIT_STATUS_V1_UNSPECIFIED identifies the corresponding protocol value.
	CommitStatusV1_COMMIT_STATUS_V1_UNSPECIFIED CommitStatusV1 = 0
	// First accepted commit for this commit_key; duplicates are a noop.
	// COMMIT_STATUS_V1_ACCEPTED identifies the corresponding protocol value.
	CommitStatusV1_COMMIT_STATUS_V1_ACCEPTED CommitStatusV1 = 1
)

var CommitStatusV1_name = map[int32]string{
	0: "COMMIT_STATUS_V1_UNSPECIFIED",
	1: "COMMIT_STATUS_V1_ACCEPTED",
}

var CommitStatusV1_value = map[string]int32{
	"COMMIT_STATUS_V1_UNSPECIFIED": 0,
	"COMMIT_STATUS_V1_ACCEPTED":    1,
}

func (x CommitStatusV1) String() string {
	return proto.EnumName(CommitStatusV1_name, int32(x))
}

func (CommitStatusV1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2ce2aa1b30c68d91, []int{0}
}

// VerifyCommitV1 is the verifier-signed result commitment carried by
// MsgSubmitVerifyCommit and MsgBatchSubmitVerifyCommit. Field numbers, types and
// order are frozen by keeper_api_contract.md §5.14 and are the length-framed preimage
// of
//
//	verify_commit_signing_digest = H_FIELDS_V1("TRUEOPEN_COMMIT_V1",
//	  schema_version, chain_id, task_id, verify_round,
//	  verifier_operator_address, service_authorization_nonce,
//	  commit_hash, expiry_height)
//
// commit_hash must be a canonical 32-byte SHA-256 value produced by
//
//	commit_hash = H_FIELDS_V1("TRUEOPEN_RESULT_COMMITMENT_V2", chain_id, task_id,
//	  task_hash, verify_round, verifier_operator_address, result_payload_hash,
//	  salt)
//
// Non-canonical placeholder values are rejected at the entry point; there is no
// "looks like a hash" conditional branch and no optional commitment field.
//
// schema_version is 1, the same value as every other §5.14 stage wire and §4.1
// handraise wire. The single normative statement of that value, its derivation and
// its schema-version rule lives on InferReceiptV2 in task/v1/infer_receipt.proto;
// this file does not restate them.
// VerifyCommitV1 defines the VerifyCommitV1 wire type.
type VerifyCommitV1 struct {
	// Always 1; InferReceiptV2 alone uses schema version 2.
	SchemaVersion uint32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ChainId       string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TaskId        []byte `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Every verify_round in this file uses ADR-0014 v1.1 numbering: 1 is the
	// initial verification, values >= 2 are challenge rounds, and 0 is invalid.
	VerifyRound               uint32 `protobuf:"varint,4,opt,name=verify_round,json=verifyRound,proto3" json:"verify_round,omitempty"`
	VerifierOperatorAddress   string `protobuf:"bytes,5,opt,name=verifier_operator_address,json=verifierOperatorAddress,proto3" json:"verifier_operator_address,omitempty"`
	ServiceAuthorizationNonce uint64 `protobuf:"varint,6,opt,name=service_authorization_nonce,json=serviceAuthorizationNonce,proto3" json:"service_authorization_nonce,omitempty"`
	CommitHash                []byte `protobuf:"bytes,7,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	ExpiryHeight              uint64 `protobuf:"varint,8,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	ServiceSignature          []byte `protobuf:"bytes,9,opt,name=service_signature,json=serviceSignature,proto3" json:"service_signature,omitempty"`
}

func (m *VerifyCommitV1) Reset()         { *m = VerifyCommitV1{} }
func (m *VerifyCommitV1) String() string { return proto.CompactTextString(m) }
func (*VerifyCommitV1) ProtoMessage()    {}
func (*VerifyCommitV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce2aa1b30c68d91, []int{0}
}
func (m *VerifyCommitV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyCommitV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyCommitV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifyCommitV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCommitV1.Merge(m, src)
}
func (m *VerifyCommitV1) XXX_Size() int {
	return m.Size()
}
func (m *VerifyCommitV1) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCommitV1.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCommitV1 proto.InternalMessageInfo

func (m *VerifyCommitV1) GetSchemaVersion() uint32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *VerifyCommitV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *VerifyCommitV1) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *VerifyCommitV1) GetVerifyRound() uint32 {
	if m != nil {
		return m.VerifyRound
	}
	return 0
}

func (m *VerifyCommitV1) GetVerifierOperatorAddress() string {
	if m != nil {
		return m.VerifierOperatorAddress
	}
	return ""
}

func (m *VerifyCommitV1) GetServiceAuthorizationNonce() uint64 {
	if m != nil {
		return m.ServiceAuthorizationNonce
	}
	return 0
}

func (m *VerifyCommitV1) GetCommitHash() []byte {
	if m != nil {
		return m.CommitHash
	}
	return nil
}

func (m *VerifyCommitV1) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *VerifyCommitV1) GetServiceSignature() []byte {
	if m != nil {
		return m.ServiceSignature
	}
	return nil
}

// CommitState is the first accepted verifier commit, keyed by commit_key
// (keeper_data_structure_contract.md §6.6). commit_key has exactly one ordered preimage in
// the whole repository (keeper_api_contract.md §10.9):
//
//	commit_key = H_FIELDS_V1("TRUEOPEN_COMMIT_KEY_V1",
//	  chain_id, task_id, verify_round, verifier_operator_address)
//
// with verify_round encoded as uint32_be and verifier_operator_address as stable
// operator address codec bytes.
// CommitState defines the CommitState wire type.
type CommitState struct {
	CommitKey               []byte `protobuf:"bytes,1,opt,name=commit_key,json=commitKey,proto3" json:"commit_key,omitempty"`
	TaskId                  []byte `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VerifyRound             uint32 `protobuf:"varint,3,opt,name=verify_round,json=verifyRound,proto3" json:"verify_round,omitempty"`
	VerifierOperatorAddress string `protobuf:"bytes,4,opt,name=verifier_operator_address,json=verifierOperatorAddress,proto3" json:"verifier_operator_address,omitempty"`
	CommitHash              []byte `protobuf:"bytes,5,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	CommitSigningDigest     []byte `protobuf:"bytes,6,opt,name=commit_signing_digest,json=commitSigningDigest,proto3" json:"commit_signing_digest,omitempty"`
	// SHA256(raw_signature_64), retained as a 32-byte audit/exact-replay fingerprint.
	// The 64-byte signature was verified before initial live acceptance and is not retained.
	// This digest is not authorization state and never enters a signing/business digest;
	// replay compares it only to identify the same previously accepted signature.
	SignatureDigest []byte         `protobuf:"bytes,7,opt,name=signature_digest,json=signatureDigest,proto3" json:"signature_digest,omitempty"`
	CommitHeight    uint64         `protobuf:"varint,8,opt,name=commit_height,json=commitHeight,proto3" json:"commit_height,omitempty"`
	Status          CommitStatusV1 `protobuf:"varint,9,opt,name=status,proto3,enum=task.v1.CommitStatusV1" json:"status,omitempty"`
}

func (m *CommitState) Reset()         { *m = CommitState{} }
func (m *CommitState) String() string { return proto.CompactTextString(m) }
func (*CommitState) ProtoMessage()    {}
func (*CommitState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce2aa1b30c68d91, []int{1}
}
func (m *CommitState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommitState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommitState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommitState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitState.Merge(m, src)
}
func (m *CommitState) XXX_Size() int {
	return m.Size()
}
func (m *CommitState) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitState.DiscardUnknown(m)
}

var xxx_messageInfo_CommitState proto.InternalMessageInfo

func (m *CommitState) GetCommitKey() []byte {
	if m != nil {
		return m.CommitKey
	}
	return nil
}

func (m *CommitState) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *CommitState) GetVerifyRound() uint32 {
	if m != nil {
		return m.VerifyRound
	}
	return 0
}

func (m *CommitState) GetVerifierOperatorAddress() string {
	if m != nil {
		return m.VerifierOperatorAddress
	}
	return ""
}

func (m *CommitState) GetCommitHash() []byte {
	if m != nil {
		return m.CommitHash
	}
	return nil
}

func (m *CommitState) GetCommitSigningDigest() []byte {
	if m != nil {
		return m.CommitSigningDigest
	}
	return nil
}

func (m *CommitState) GetSignatureDigest() []byte {
	if m != nil {
		return m.SignatureDigest
	}
	return nil
}

func (m *CommitState) GetCommitHeight() uint64 {
	if m != nil {
		return m.CommitHeight
	}
	return 0
}

func (m *CommitState) GetStatus() CommitStatusV1 {
	if m != nil {
		return m.Status
	}
	return CommitStatusV1_COMMIT_STATUS_V1_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("task.v1.CommitStatusV1", CommitStatusV1_name, CommitStatusV1_value)
	proto.RegisterType((*VerifyCommitV1)(nil), "task.v1.VerifyCommitV1")
	proto.RegisterType((*CommitState)(nil), "task.v1.CommitState")
}

func init() { proto.RegisterFile("task/v1/commit.proto", fileDescriptor_2ce2aa1b30c68d91) }

var fileDescriptor_2ce2aa1b30c68d91 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0xb5, 0xeb, 0x36, 0x6f, 0x2d, 0xc5, 0x0c, 0x2d, 0x1d, 0xac, 0x2a, 0x9b, 0x26,
	0x55, 0x48, 0x34, 0x2a, 0x5c, 0x38, 0x81, 0xba, 0xae, 0x68, 0x15, 0xda, 0x1f, 0x92, 0xac, 0x07,
	0x2e, 0x96, 0x97, 0x98, 0xc4, 0x9a, 0x6a, 0x57, 0xb6, 0x53, 0xad, 0x7c, 0x0a, 0xbe, 0x06, 0x57,
	0xc4, 0x87, 0xd8, 0x71, 0xe2, 0xc4, 0x11, 0x6d, 0x1f, 0x81, 0x2f, 0x80, 0x62, 0x27, 0xa5, 0x03,
	0x21, 0x01, 0x47, 0x3f, 0xcf, 0xf3, 0xbe, 0x7e, 0xf3, 0xfe, 0xe4, 0x80, 0x75, 0x85, 0xe5, 0xb9,
	0x33, 0xe9, 0x38, 0x01, 0x1f, 0x8d, 0xa8, 0x6a, 0x8f, 0x05, 0x57, 0x1c, 0x2e, 0xa5, 0x6a, 0x7b,
	0xd2, 0xd9, 0xac, 0x07, 0x5c, 0x8e, 0xb8, 0x44, 0x5a, 0x76, 0xcc, 0xc1, 0x64, 0x36, 0xb7, 0x64,
	0x8c, 0x05, 0x09, 0xd3, 0x5a, 0x41, 0xa4, 0x42, 0x84, 0x05, 0x3c, 0xa4, 0x2c, 0x32, 0xf6, 0xf6,
	0xc7, 0x22, 0xa8, 0x0e, 0x89, 0xa0, 0xef, 0xa6, 0x3d, 0xdd, 0x79, 0xd8, 0x81, 0xbb, 0xa0, 0x2a,
	0x83, 0x98, 0x8c, 0x30, 0x9a, 0x10, 0x21, 0x29, 0x67, 0xb6, 0xd5, 0xb4, 0x5a, 0x15, 0xb7, 0x62,
	0xd4, 0xa1, 0x11, 0x61, 0x1d, 0x2c, 0x07, 0x31, 0xa6, 0x0c, 0xd1, 0xd0, 0x5e, 0x68, 0x5a, 0xad,
	0x15, 0x77, 0x49, 0x9f, 0x07, 0x21, 0xdc, 0x02, 0x7a, 0xb2, 0xd4, 0x29, 0x36, 0xad, 0xd6, 0xda,
	0x5e, 0xe9, 0xf2, 0xbb, 0xbd, 0xe0, 0x96, 0x53, 0x71, 0x10, 0xc2, 0x47, 0x60, 0x6d, 0xa2, 0xaf,
	0x44, 0x82, 0x27, 0x2c, 0xb4, 0x4b, 0xba, 0xfd, 0xaa, 0xd1, 0xdc, 0x54, 0x82, 0x3e, 0xa8, 0xeb,
	0x23, 0x25, 0x02, 0xf1, 0x31, 0x11, 0x58, 0x71, 0x81, 0x70, 0x18, 0x0a, 0x22, 0xa5, 0xbd, 0x98,
	0xde, 0xb6, 0x67, 0x7f, 0xf9, 0xfc, 0x64, 0x3d, 0xfb, 0xd4, 0xae, 0x71, 0x3c, 0x25, 0x28, 0x8b,
	0xdc, 0x8d, 0xbc, 0xf4, 0x38, 0xab, 0xcc, 0x6c, 0xf8, 0x02, 0x3c, 0x90, 0x44, 0x4c, 0x68, 0x40,
	0x10, 0x4e, 0x54, 0xcc, 0x05, 0x7d, 0x8f, 0x15, 0xe5, 0x0c, 0x31, 0xce, 0x02, 0x62, 0x97, 0x9b,
	0x56, 0xab, 0xe4, 0xd6, 0xb3, 0x48, 0x77, 0x3e, 0x71, 0x94, 0x06, 0xe0, 0x2e, 0x58, 0x35, 0xfb,
	0x47, 0x31, 0x96, 0xb1, 0xbd, 0x34, 0xf7, 0x6d, 0xc0, 0x18, 0x07, 0x58, 0xc6, 0x70, 0x07, 0x54,
	0xc8, 0xc5, 0x98, 0x8a, 0x29, 0x8a, 0x09, 0x8d, 0x62, 0x65, 0x2f, 0xeb, 0xc6, 0x6b, 0x46, 0x3c,
	0xd0, 0x1a, 0xec, 0x80, 0xbb, 0xf9, 0x2c, 0x92, 0x46, 0x0c, 0xab, 0x44, 0x10, 0x7b, 0x65, 0xd6,
	0xd1, 0x72, 0x6b, 0x99, 0xed, 0xe5, 0xee, 0xf6, 0xa7, 0x22, 0x58, 0x35, 0x94, 0x3c, 0x85, 0x15,
	0x81, 0x3b, 0x20, 0xbb, 0x15, 0x9d, 0x93, 0xa9, 0x86, 0x94, 0x4f, 0xb3, 0x62, 0xf4, 0xd7, 0x64,
	0x3a, 0xcf, 0x62, 0xe1, 0x2f, 0x58, 0x14, 0xff, 0x91, 0x45, 0xe9, 0x7f, 0x59, 0xfc, 0xb2, 0xcb,
	0xc5, 0x3f, 0xec, 0xf2, 0x39, 0xb8, 0x9f, 0xc5, 0xd2, 0x2d, 0x51, 0x16, 0xa1, 0x90, 0x46, 0x44,
	0x2a, 0x0d, 0x2b, 0x2f, 0xb8, 0x67, 0x22, 0x9e, 0x49, 0xec, 0xeb, 0x00, 0x74, 0x40, 0x6d, 0xb6,
	0xd8, 0xbc, 0x68, 0x9e, 0xd8, 0x9d, 0x99, 0x9b, 0x15, 0xec, 0x80, 0x4a, 0x3e, 0xd1, 0x2d, 0x6c,
	0xd9, 0x34, 0x06, 0x9b, 0x03, 0xca, 0x52, 0x61, 0x95, 0x48, 0xcd, 0xaa, 0xfa, 0x74, 0xa3, 0x9d,
	0xbd, 0xc1, 0xf6, 0x4f, 0x32, 0x89, 0x1c, 0x76, 0xdc, 0x2c, 0xf6, 0xf8, 0x0d, 0xa8, 0xde, 0x76,
	0x60, 0x13, 0x3c, 0xec, 0x1d, 0x1f, 0x1e, 0x0e, 0x7c, 0xe4, 0xf9, 0x5d, 0xff, 0xd4, 0x43, 0xc3,
	0x0e, 0x3a, 0x3d, 0xf2, 0x4e, 0xfa, 0xbd, 0xc1, 0xab, 0x41, 0x7f, 0xbf, 0x56, 0x80, 0x5b, 0xa0,
	0xfe, 0x5b, 0xa2, 0xdb, 0xeb, 0xf5, 0x4f, 0xfc, 0xfe, 0x7e, 0xcd, 0xda, 0x7b, 0x79, 0x79, 0xdd,
	0xb0, 0xae, 0xae, 0x1b, 0xd6, 0xb7, 0xeb, 0x86, 0xf5, 0xe1, 0xa6, 0x51, 0xb8, 0xba, 0x69, 0x14,
	0xbe, 0xde, 0x34, 0x0a, 0x6f, 0x77, 0x23, 0xaa, 0xe2, 0xe4, 0xac, 0x1d, 0xf0, 0x91, 0xe3, 0x8b,
	0x84, 0x1c, 0x8f, 0x09, 0x73, 0x18, 0x0f, 0x89, 0x73, 0xe1, 0xe8, 0x3f, 0x88, 0x9a, 0x8e, 0x89,
	0x3c, 0x2b, 0xeb, 0xb7, 0xff, 0xec, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x9b, 0xf2, 0xcf,
	0x56, 0x04, 0x00, 0x00,
}

func (m *VerifyCommitV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyCommitV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifyCommitV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServiceSignature) > 0 {
		i -= len(m.ServiceSignature)
		copy(dAtA[i:], m.ServiceSignature)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.ServiceSignature)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ExpiryHeight != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.CommitHash) > 0 {
		i -= len(m.CommitHash)
		copy(dAtA[i:], m.CommitHash)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.CommitHash)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ServiceAuthorizationNonce != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.ServiceAuthorizationNonce))
		i--
		dAtA[i] = 0x30
	}
	if len(m.VerifierOperatorAddress) > 0 {
		i -= len(m.VerifierOperatorAddress)
		copy(dAtA[i:], m.VerifierOperatorAddress)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.VerifierOperatorAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.VerifyRound != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.VerifyRound))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if m.SchemaVersion != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.SchemaVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CommitState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommitState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommitState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	if m.CommitHeight != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.CommitHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.SignatureDigest) > 0 {
		i -= len(m.SignatureDigest)
		copy(dAtA[i:], m.SignatureDigest)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.SignatureDigest)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CommitSigningDigest) > 0 {
		i -= len(m.CommitSigningDigest)
		copy(dAtA[i:], m.CommitSigningDigest)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.CommitSigningDigest)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CommitHash) > 0 {
		i -= len(m.CommitHash)
		copy(dAtA[i:], m.CommitHash)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.CommitHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.VerifierOperatorAddress) > 0 {
		i -= len(m.VerifierOperatorAddress)
		copy(dAtA[i:], m.VerifierOperatorAddress)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.VerifierOperatorAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.VerifyRound != 0 {
		i = encodeVarintCommit(dAtA, i, uint64(m.VerifyRound))
		i--
		dAtA[i] = 0x18
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CommitKey) > 0 {
		i -= len(m.CommitKey)
		copy(dAtA[i:], m.CommitKey)
		i = encodeVarintCommit(dAtA, i, uint64(len(m.CommitKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommit(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VerifyCommitV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SchemaVersion != 0 {
		n += 1 + sovCommit(uint64(m.SchemaVersion))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	if m.VerifyRound != 0 {
		n += 1 + sovCommit(uint64(m.VerifyRound))
	}
	l = len(m.VerifierOperatorAddress)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	if m.ServiceAuthorizationNonce != 0 {
		n += 1 + sovCommit(uint64(m.ServiceAuthorizationNonce))
	}
	l = len(m.CommitHash)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovCommit(uint64(m.ExpiryHeight))
	}
	l = len(m.ServiceSignature)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	return n
}

func (m *CommitState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CommitKey)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	if m.VerifyRound != 0 {
		n += 1 + sovCommit(uint64(m.VerifyRound))
	}
	l = len(m.VerifierOperatorAddress)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	l = len(m.CommitHash)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	l = len(m.CommitSigningDigest)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	l = len(m.SignatureDigest)
	if l > 0 {
		n += 1 + l + sovCommit(uint64(l))
	}
	if m.CommitHeight != 0 {
		n += 1 + sovCommit(uint64(m.CommitHeight))
	}
	if m.Status != 0 {
		n += 1 + sovCommit(uint64(m.Status))
	}
	return n
}

func sovCommit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommit(x uint64) (n int) {
	return sovCommit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VerifyCommitV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyCommitV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyCommitV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaVersion", wireType)
			}
			m.SchemaVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyRound", wireType)
			}
			m.VerifyRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifyRound |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierOperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifierOperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceAuthorizationNonce", wireType)
			}
			m.ServiceAuthorizationNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServiceAuthorizationNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHash = append(m.CommitHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitHash == nil {
				m.CommitHash = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceSignature = append(m.ServiceSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.ServiceSignature == nil {
				m.ServiceSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommitState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommitState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommitState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitKey = append(m.CommitKey[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitKey == nil {
				m.CommitKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyRound", wireType)
			}
			m.VerifyRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifyRound |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierOperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifierOperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHash = append(m.CommitHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitHash == nil {
				m.CommitHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitSigningDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitSigningDigest = append(m.CommitSigningDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitSigningDigest == nil {
				m.CommitSigningDigest = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignatureDigest = append(m.SignatureDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.SignatureDigest == nil {
				m.SignatureDigest = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHeight", wireType)
			}
			m.CommitHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CommitStatusV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommit = fmt.Errorf("proto: unexpected end of group")
)
