// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task/v1/deadline.proto

package types

import (
	fmt "fmt"
	types "github.com/TrueOpen/node/x/shared/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DeadlineKindV1 selects which deadline of a primary object is being swept.
//
// the API contract is the ONLY numeric definition of this enum in the
// whole contract: the sweep locator, the Query projection
// TaskStageViewV1.next_deadline_kind and §5.11 event code 20 `deadline_swept`
// all share these numbers. The values are bound column-by-column to the locator
// type and the same-height kind_priority of that table and are copied verbatim.
//
// DeadlineKindV1 defines the DeadlineKindV1 wire type.
type DeadlineKindV1 int32

const (
	// Never written; rejects zero-value rows and locators.
	// DEADLINE_KIND_V1_UNSPECIFIED identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_UNSPECIFIED DeadlineKindV1 = 0
	// Optimistic finality window of one task; kind_priority 30.
	// DEADLINE_KIND_V1_TASK_FINALITY identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_TASK_FINALITY DeadlineKindV1 = 1
	// Settlement deadline of one task; kind_priority 40.
	// DEADLINE_KIND_V1_TASK_SETTLEMENT identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_TASK_SETTLEMENT DeadlineKindV1 = 2
	// Verification-round close deadline; kind_priority 20.
	// DEADLINE_KIND_V1_VERIFY_ROUND_CLOSE identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_VERIFY_ROUND_CLOSE DeadlineKindV1 = 4
	// Verifier result reveal deadline; kind_priority 50.
	// DEADLINE_KIND_V1_VERIFY_REVEAL identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_VERIFY_REVEAL DeadlineKindV1 = 5
	// Verifier commit deadline; kind_priority 60.
	// DEADLINE_KIND_V1_VERIFY_COMMIT identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_VERIFY_COMMIT DeadlineKindV1 = 6
	// Open Verify handraise window deadline; kind_priority 70.
	// DEADLINE_KIND_V1_VERIFY_OPEN identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_VERIFY_OPEN DeadlineKindV1 = 7
	// Winner worker inference deadline; kind_priority 80.
	// DEADLINE_KIND_V1_WORKER_INFER identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_WORKER_INFER DeadlineKindV1 = 8
	// Assignment randomness expiry; kind_priority 90.
	// DEADLINE_KIND_V1_WORKER_ASSIGNMENT identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_WORKER_ASSIGNMENT DeadlineKindV1 = 9
	// Session idle / close lifecycle sweep; kind_priority 100.
	// DEADLINE_KIND_V1_SESSION_LIFECYCLE identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_SESSION_LIFECYCLE DeadlineKindV1 = 10
	// Final verification deadline; kind_priority 45.
	// DEADLINE_KIND_V1_VERIFY_FINAL identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_VERIFY_FINAL DeadlineKindV1 = 11
	// Window in which the funded second verification round may be opened.
	// DEADLINE_KIND_V1_CHALLENGE_WINDOW_CLOSE identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_CHALLENGE_WINDOW_CLOSE DeadlineKindV1 = 12
	// EvidenceCleanupIndex bounded cursor; kind_priority 110.
	// DEADLINE_KIND_V1_EVIDENCE_CLEANUP identifies the corresponding protocol value.
	DeadlineKindV1_DEADLINE_KIND_V1_EVIDENCE_CLEANUP DeadlineKindV1 = 13
)

var DeadlineKindV1_name = map[int32]string{
	0:  "DEADLINE_KIND_V1_UNSPECIFIED",
	1:  "DEADLINE_KIND_V1_TASK_FINALITY",
	2:  "DEADLINE_KIND_V1_TASK_SETTLEMENT",
	4:  "DEADLINE_KIND_V1_VERIFY_ROUND_CLOSE",
	5:  "DEADLINE_KIND_V1_VERIFY_REVEAL",
	6:  "DEADLINE_KIND_V1_VERIFY_COMMIT",
	7:  "DEADLINE_KIND_V1_VERIFY_OPEN",
	8:  "DEADLINE_KIND_V1_WORKER_INFER",
	9:  "DEADLINE_KIND_V1_WORKER_ASSIGNMENT",
	10: "DEADLINE_KIND_V1_SESSION_LIFECYCLE",
	11: "DEADLINE_KIND_V1_VERIFY_FINAL",
	12: "DEADLINE_KIND_V1_CHALLENGE_WINDOW_CLOSE",
	13: "DEADLINE_KIND_V1_EVIDENCE_CLEANUP",
}

var DeadlineKindV1_value = map[string]int32{
	"DEADLINE_KIND_V1_UNSPECIFIED":            0,
	"DEADLINE_KIND_V1_TASK_FINALITY":          1,
	"DEADLINE_KIND_V1_TASK_SETTLEMENT":        2,
	"DEADLINE_KIND_V1_VERIFY_ROUND_CLOSE":     4,
	"DEADLINE_KIND_V1_VERIFY_REVEAL":          5,
	"DEADLINE_KIND_V1_VERIFY_COMMIT":          6,
	"DEADLINE_KIND_V1_VERIFY_OPEN":            7,
	"DEADLINE_KIND_V1_WORKER_INFER":           8,
	"DEADLINE_KIND_V1_WORKER_ASSIGNMENT":      9,
	"DEADLINE_KIND_V1_SESSION_LIFECYCLE":      10,
	"DEADLINE_KIND_V1_VERIFY_FINAL":           11,
	"DEADLINE_KIND_V1_CHALLENGE_WINDOW_CLOSE": 12,
	"DEADLINE_KIND_V1_EVIDENCE_CLEANUP":       13,
}

func (x DeadlineKindV1) String() string {
	return proto.EnumName(DeadlineKindV1_name, int32(x))
}

func (DeadlineKindV1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{0}
}

// DeadlineTransitionCode is the closed transition reason carried by §5.11 event
// code 20 `deadline_swept`. Numbers come from the §9.6b enum registry.
//
// DeadlineTransitionCode defines the DeadlineTransitionCode wire type.
type DeadlineTransitionCode int32

const (
	// Never written; rejects zero-value transitions.
	// DEADLINE_TRANSITION_CODE_UNSPECIFIED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_UNSPECIFIED DeadlineTransitionCode = 0
	// StreamState moved ACTIVE -> IDLE.
	// DEADLINE_TRANSITION_CODE_SESSION_ACTIVE_TO_IDLE identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_SESSION_ACTIVE_TO_IDLE DeadlineTransitionCode = 1
	// StreamState moved IDLE -> CLOSED.
	// DEADLINE_TRANSITION_CODE_SESSION_IDLE_TO_CLOSED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_SESSION_IDLE_TO_CLOSED DeadlineTransitionCode = 2
	// Worker assignment could not be completed.
	// DEADLINE_TRANSITION_CODE_ASSIGNMENT_FAILED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_ASSIGNMENT_FAILED DeadlineTransitionCode = 3
	// Winner worker missed the inference deadline.
	// DEADLINE_TRANSITION_CODE_WORKER_TIMEOUT identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_WORKER_TIMEOUT DeadlineTransitionCode = 4
	// Open Verify window closed without a usable verifier set.
	// DEADLINE_TRANSITION_CODE_VERIFY_OPEN_TIMEOUT identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_VERIFY_OPEN_TIMEOUT DeadlineTransitionCode = 5
	// Commit window closed and reveal started or verification failed.
	// DEADLINE_TRANSITION_CODE_COMMIT_CLOSED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_COMMIT_CLOSED DeadlineTransitionCode = 6
	// Reveal window closed.
	// DEADLINE_TRANSITION_CODE_REVEAL_CLOSED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_REVEAL_CLOSED DeadlineTransitionCode = 7
	// One verification round closed.
	// DEADLINE_TRANSITION_CODE_VERIFY_ROUND_CLOSED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_VERIFY_ROUND_CLOSED DeadlineTransitionCode = 8
	// The round-2 open window closed.
	// DEADLINE_TRANSITION_CODE_CHALLENGE_WINDOW_CLOSED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_CHALLENGE_WINDOW_CLOSED DeadlineTransitionCode = 9
	// Settlement completed through the shared deadline/settlement runner.
	// DEADLINE_TRANSITION_CODE_SETTLEMENT_EXECUTED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_SETTLEMENT_EXECUTED DeadlineTransitionCode = 10
	// Evidence cleanup advanced its bounded cursor.
	// DEADLINE_TRANSITION_CODE_EVIDENCE_CLEANUP_ADVANCED identifies the corresponding protocol value.
	DeadlineTransitionCode_DEADLINE_TRANSITION_CODE_EVIDENCE_CLEANUP_ADVANCED DeadlineTransitionCode = 11
)

var DeadlineTransitionCode_name = map[int32]string{
	0:  "DEADLINE_TRANSITION_CODE_UNSPECIFIED",
	1:  "DEADLINE_TRANSITION_CODE_SESSION_ACTIVE_TO_IDLE",
	2:  "DEADLINE_TRANSITION_CODE_SESSION_IDLE_TO_CLOSED",
	3:  "DEADLINE_TRANSITION_CODE_ASSIGNMENT_FAILED",
	4:  "DEADLINE_TRANSITION_CODE_WORKER_TIMEOUT",
	5:  "DEADLINE_TRANSITION_CODE_VERIFY_OPEN_TIMEOUT",
	6:  "DEADLINE_TRANSITION_CODE_COMMIT_CLOSED",
	7:  "DEADLINE_TRANSITION_CODE_REVEAL_CLOSED",
	8:  "DEADLINE_TRANSITION_CODE_VERIFY_ROUND_CLOSED",
	9:  "DEADLINE_TRANSITION_CODE_CHALLENGE_WINDOW_CLOSED",
	10: "DEADLINE_TRANSITION_CODE_SETTLEMENT_EXECUTED",
	11: "DEADLINE_TRANSITION_CODE_EVIDENCE_CLEANUP_ADVANCED",
}

var DeadlineTransitionCode_value = map[string]int32{
	"DEADLINE_TRANSITION_CODE_UNSPECIFIED":               0,
	"DEADLINE_TRANSITION_CODE_SESSION_ACTIVE_TO_IDLE":    1,
	"DEADLINE_TRANSITION_CODE_SESSION_IDLE_TO_CLOSED":    2,
	"DEADLINE_TRANSITION_CODE_ASSIGNMENT_FAILED":         3,
	"DEADLINE_TRANSITION_CODE_WORKER_TIMEOUT":            4,
	"DEADLINE_TRANSITION_CODE_VERIFY_OPEN_TIMEOUT":       5,
	"DEADLINE_TRANSITION_CODE_COMMIT_CLOSED":             6,
	"DEADLINE_TRANSITION_CODE_REVEAL_CLOSED":             7,
	"DEADLINE_TRANSITION_CODE_VERIFY_ROUND_CLOSED":       8,
	"DEADLINE_TRANSITION_CODE_CHALLENGE_WINDOW_CLOSED":   9,
	"DEADLINE_TRANSITION_CODE_SETTLEMENT_EXECUTED":       10,
	"DEADLINE_TRANSITION_CODE_EVIDENCE_CLEANUP_ADVANCED": 11,
}

func (x DeadlineTransitionCode) String() string {
	return proto.EnumName(DeadlineTransitionCode_name, int32(x))
}

func (DeadlineTransitionCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{1}
}

// TaskDeadlineLocator selects one task-scoped deadline (§5.9).
type TaskDeadlineLocator struct {
	// task_id is the canonical 32-byte Task ID.
	TaskId []byte `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// deadline_kind must be a TaskDeadlineLocator kind of the §5.9 table.
	DeadlineKind DeadlineKindV1 `protobuf:"varint,2,opt,name=deadline_kind,json=deadlineKind,proto3,enum=task.v1.DeadlineKindV1" json:"deadline_kind,omitempty"`
}

func (m *TaskDeadlineLocator) Reset()         { *m = TaskDeadlineLocator{} }
func (m *TaskDeadlineLocator) String() string { return proto.CompactTextString(m) }
func (*TaskDeadlineLocator) ProtoMessage()    {}
func (*TaskDeadlineLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{0}
}
func (m *TaskDeadlineLocator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskDeadlineLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskDeadlineLocator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskDeadlineLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDeadlineLocator.Merge(m, src)
}
func (m *TaskDeadlineLocator) XXX_Size() int {
	return m.Size()
}
func (m *TaskDeadlineLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDeadlineLocator.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDeadlineLocator proto.InternalMessageInfo

func (m *TaskDeadlineLocator) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *TaskDeadlineLocator) GetDeadlineKind() DeadlineKindV1 {
	if m != nil {
		return m.DeadlineKind
	}
	return DeadlineKindV1_DEADLINE_KIND_V1_UNSPECIFIED
}

// TaskRoundDeadlineLocator selects a deadline owned by one Task verification round.
type TaskRoundDeadlineLocator struct {
	TaskId       []byte         `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VerifyRound  uint32         `protobuf:"varint,2,opt,name=verify_round,json=verifyRound,proto3" json:"verify_round,omitempty"`
	DeadlineKind DeadlineKindV1 `protobuf:"varint,3,opt,name=deadline_kind,json=deadlineKind,proto3,enum=task.v1.DeadlineKindV1" json:"deadline_kind,omitempty"`
}

func (m *TaskRoundDeadlineLocator) Reset()         { *m = TaskRoundDeadlineLocator{} }
func (m *TaskRoundDeadlineLocator) String() string { return proto.CompactTextString(m) }
func (*TaskRoundDeadlineLocator) ProtoMessage()    {}
func (*TaskRoundDeadlineLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{1}
}
func (m *TaskRoundDeadlineLocator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskRoundDeadlineLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskRoundDeadlineLocator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskRoundDeadlineLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRoundDeadlineLocator.Merge(m, src)
}
func (m *TaskRoundDeadlineLocator) XXX_Size() int {
	return m.Size()
}
func (m *TaskRoundDeadlineLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRoundDeadlineLocator.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRoundDeadlineLocator proto.InternalMessageInfo

func (m *TaskRoundDeadlineLocator) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *TaskRoundDeadlineLocator) GetVerifyRound() uint32 {
	if m != nil {
		return m.VerifyRound
	}
	return 0
}

func (m *TaskRoundDeadlineLocator) GetDeadlineKind() DeadlineKindV1 {
	if m != nil {
		return m.DeadlineKind
	}
	return DeadlineKindV1_DEADLINE_KIND_V1_UNSPECIFIED
}

// SessionLifecycleLocator selects the session idle/close sweep (§5.9). §5.9
// freezes exactly this shape: a message-typed oneof reusing the §9.6b ByIDV1 /
// BatchV1 base types. No second scalar oneof shape exists and §10.0b1 only
// references this one.
// SessionLifecycleLocator defines the SessionLifecycleLocator wire type.
type SessionLifecycleLocator struct {
	// Exactly one target must be set.
	// target selects one supported variant.
	//
	// Types that are valid to be assigned to Target:
	//	*SessionLifecycleLocator_ById
	//	*SessionLifecycleLocator_Batch
	Target isSessionLifecycleLocator_Target `protobuf_oneof:"target"`
}

func (m *SessionLifecycleLocator) Reset()         { *m = SessionLifecycleLocator{} }
func (m *SessionLifecycleLocator) String() string { return proto.CompactTextString(m) }
func (*SessionLifecycleLocator) ProtoMessage()    {}
func (*SessionLifecycleLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{2}
}
func (m *SessionLifecycleLocator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SessionLifecycleLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SessionLifecycleLocator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SessionLifecycleLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionLifecycleLocator.Merge(m, src)
}
func (m *SessionLifecycleLocator) XXX_Size() int {
	return m.Size()
}
func (m *SessionLifecycleLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionLifecycleLocator.DiscardUnknown(m)
}

var xxx_messageInfo_SessionLifecycleLocator proto.InternalMessageInfo

type isSessionLifecycleLocator_Target interface {
	isSessionLifecycleLocator_Target()
	MarshalTo([]byte) (int, error)
	Size() int
}

type SessionLifecycleLocator_ById struct {
	ById *types.ByIDV1 `protobuf:"bytes,1,opt,name=by_id,json=byId,proto3,oneof" json:"by_id,omitempty"`
}
type SessionLifecycleLocator_Batch struct {
	Batch *types.BatchV1 `protobuf:"bytes,2,opt,name=batch,proto3,oneof" json:"batch,omitempty"`
}

func (*SessionLifecycleLocator_ById) isSessionLifecycleLocator_Target()  {}
func (*SessionLifecycleLocator_Batch) isSessionLifecycleLocator_Target() {}

func (m *SessionLifecycleLocator) GetTarget() isSessionLifecycleLocator_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SessionLifecycleLocator) GetById() *types.ByIDV1 {
	if x, ok := m.GetTarget().(*SessionLifecycleLocator_ById); ok {
		return x.ById
	}
	return nil
}

func (m *SessionLifecycleLocator) GetBatch() *types.BatchV1 {
	if x, ok := m.GetTarget().(*SessionLifecycleLocator_Batch); ok {
		return x.Batch
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SessionLifecycleLocator) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SessionLifecycleLocator_ById)(nil),
		(*SessionLifecycleLocator_Batch)(nil),
	}
}

// DeadlineLocatorV1 identifies exactly one primary object and one of its
// deadlines (§5.9). The locator must uniquely hit one primary state and its
// deadline: a scope mismatch is InvalidArgument, a not-yet-due deadline is
// FailedPrecondition and an already completed transition is a noop. The deadline
// is inclusive, so current_height >= deadline_height is executable.
// DeadlineLocatorV1 defines the DeadlineLocatorV1 wire type.
type DeadlineLocatorV1 struct {
	// Exactly one locator must be set.
	// locator selects one supported variant.
	//
	// Types that are valid to be assigned to Locator:
	//	*DeadlineLocatorV1_Task
	//	*DeadlineLocatorV1_TaskRound
	//	*DeadlineLocatorV1_SessionLifecycle
	Locator isDeadlineLocatorV1_Locator `protobuf_oneof:"locator"`
}

func (m *DeadlineLocatorV1) Reset()         { *m = DeadlineLocatorV1{} }
func (m *DeadlineLocatorV1) String() string { return proto.CompactTextString(m) }
func (*DeadlineLocatorV1) ProtoMessage()    {}
func (*DeadlineLocatorV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{3}
}
func (m *DeadlineLocatorV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeadlineLocatorV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeadlineLocatorV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeadlineLocatorV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeadlineLocatorV1.Merge(m, src)
}
func (m *DeadlineLocatorV1) XXX_Size() int {
	return m.Size()
}
func (m *DeadlineLocatorV1) XXX_DiscardUnknown() {
	xxx_messageInfo_DeadlineLocatorV1.DiscardUnknown(m)
}

var xxx_messageInfo_DeadlineLocatorV1 proto.InternalMessageInfo

type isDeadlineLocatorV1_Locator interface {
	isDeadlineLocatorV1_Locator()
	MarshalTo([]byte) (int, error)
	Size() int
}

type DeadlineLocatorV1_Task struct {
	Task *TaskDeadlineLocator `protobuf:"bytes,1,opt,name=task,proto3,oneof" json:"task,omitempty"`
}
type DeadlineLocatorV1_TaskRound struct {
	TaskRound *TaskRoundDeadlineLocator `protobuf:"bytes,2,opt,name=task_round,json=taskRound,proto3,oneof" json:"task_round,omitempty"`
}
type DeadlineLocatorV1_SessionLifecycle struct {
	SessionLifecycle *SessionLifecycleLocator `protobuf:"bytes,4,opt,name=session_lifecycle,json=sessionLifecycle,proto3,oneof" json:"session_lifecycle,omitempty"`
}

func (*DeadlineLocatorV1_Task) isDeadlineLocatorV1_Locator()             {}
func (*DeadlineLocatorV1_TaskRound) isDeadlineLocatorV1_Locator()        {}
func (*DeadlineLocatorV1_SessionLifecycle) isDeadlineLocatorV1_Locator() {}

func (m *DeadlineLocatorV1) GetLocator() isDeadlineLocatorV1_Locator {
	if m != nil {
		return m.Locator
	}
	return nil
}

func (m *DeadlineLocatorV1) GetTask() *TaskDeadlineLocator {
	if x, ok := m.GetLocator().(*DeadlineLocatorV1_Task); ok {
		return x.Task
	}
	return nil
}

func (m *DeadlineLocatorV1) GetTaskRound() *TaskRoundDeadlineLocator {
	if x, ok := m.GetLocator().(*DeadlineLocatorV1_TaskRound); ok {
		return x.TaskRound
	}
	return nil
}

func (m *DeadlineLocatorV1) GetSessionLifecycle() *SessionLifecycleLocator {
	if x, ok := m.GetLocator().(*DeadlineLocatorV1_SessionLifecycle); ok {
		return x.SessionLifecycle
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeadlineLocatorV1) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeadlineLocatorV1_Task)(nil),
		(*DeadlineLocatorV1_TaskRound)(nil),
		(*DeadlineLocatorV1_SessionLifecycle)(nil),
	}
}

// MsgSweepDeadline is the single ACTIVE public deadline runner (§9.6a,
// BOUNDED_RUNNER). It replaces the deleted MsgSweepExpiredTask and
// MsgSessionSweep. The public Msg and EndBlock share one internal executor and
// one same-height order (deadline_height, kind_priority, primary_id). The public
// runner pays its own gas; there is no automatic reimbursement unless the
// parameter table registers one.
// MsgSweepDeadline defines the MsgSweepDeadline wire type.
type MsgSweepDeadline struct {
	// locator selects exactly one primary object and deadline (§5.9).
	Locator *DeadlineLocatorV1 `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
	// submitter_address is the Cosmos signer only; it never enters the locator
	// digest, business facts, hashes or Store.
	SubmitterAddress string `protobuf:"bytes,2,opt,name=submitter_address,json=submitterAddress,proto3" json:"submitter_address,omitempty"`
}

func (m *MsgSweepDeadline) Reset()         { *m = MsgSweepDeadline{} }
func (m *MsgSweepDeadline) String() string { return proto.CompactTextString(m) }
func (*MsgSweepDeadline) ProtoMessage()    {}
func (*MsgSweepDeadline) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{4}
}
func (m *MsgSweepDeadline) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSweepDeadline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSweepDeadline.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSweepDeadline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSweepDeadline.Merge(m, src)
}
func (m *MsgSweepDeadline) XXX_Size() int {
	return m.Size()
}
func (m *MsgSweepDeadline) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSweepDeadline.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSweepDeadline proto.InternalMessageInfo

func (m *MsgSweepDeadline) GetLocator() *DeadlineLocatorV1 {
	if m != nil {
		return m.Locator
	}
	return nil
}

func (m *MsgSweepDeadline) GetSubmitterAddress() string {
	if m != nil {
		return m.SubmitterAddress
	}
	return ""
}

// MsgSweepDeadlineResponse reports this invocation's bounded work (§9.6a). It
// counts visited work, not successful mutations, and never pretends to be a
// first-time receipt.
// MsgSweepDeadlineResponse defines the MsgSweepDeadlineResponse wire type.
type MsgSweepDeadlineResponse struct {
	// visited is the number of items this call examined.
	Visited uint32 `protobuf:"varint,1,opt,name=visited,proto3" json:"visited,omitempty"`
	// advanced is the number of items whose state actually moved.
	Advanced uint32 `protobuf:"varint,2,opt,name=advanced,proto3" json:"advanced,omitempty"`
	// status is APPLIED or NOOP; rejects use gRPC errors.
	Status types.MutationStatusV1 `protobuf:"varint,3,opt,name=status,proto3,enum=shared.v1.MutationStatusV1" json:"status,omitempty"`
}

func (m *MsgSweepDeadlineResponse) Reset()         { *m = MsgSweepDeadlineResponse{} }
func (m *MsgSweepDeadlineResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSweepDeadlineResponse) ProtoMessage()    {}
func (*MsgSweepDeadlineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3f545e8d5184fe3, []int{5}
}
func (m *MsgSweepDeadlineResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSweepDeadlineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSweepDeadlineResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSweepDeadlineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSweepDeadlineResponse.Merge(m, src)
}
func (m *MsgSweepDeadlineResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSweepDeadlineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSweepDeadlineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSweepDeadlineResponse proto.InternalMessageInfo

func (m *MsgSweepDeadlineResponse) GetVisited() uint32 {
	if m != nil {
		return m.Visited
	}
	return 0
}

func (m *MsgSweepDeadlineResponse) GetAdvanced() uint32 {
	if m != nil {
		return m.Advanced
	}
	return 0
}

func (m *MsgSweepDeadlineResponse) GetStatus() types.MutationStatusV1 {
	if m != nil {
		return m.Status
	}
	return types.MutationStatusV1_MUTATION_STATUS_V1_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("task.v1.DeadlineKindV1", DeadlineKindV1_name, DeadlineKindV1_value)
	proto.RegisterEnum("task.v1.DeadlineTransitionCode", DeadlineTransitionCode_name, DeadlineTransitionCode_value)
	proto.RegisterType((*TaskDeadlineLocator)(nil), "task.v1.TaskDeadlineLocator")
	proto.RegisterType((*TaskRoundDeadlineLocator)(nil), "task.v1.TaskRoundDeadlineLocator")
	proto.RegisterType((*SessionLifecycleLocator)(nil), "task.v1.SessionLifecycleLocator")
	proto.RegisterType((*DeadlineLocatorV1)(nil), "task.v1.DeadlineLocatorV1")
	proto.RegisterType((*MsgSweepDeadline)(nil), "task.v1.MsgSweepDeadline")
	proto.RegisterType((*MsgSweepDeadlineResponse)(nil), "task.v1.MsgSweepDeadlineResponse")
}

func init() { proto.RegisterFile("task/v1/deadline.proto", fileDescriptor_f3f545e8d5184fe3) }

var fileDescriptor_f3f545e8d5184fe3 = []byte{
	// 1038 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4f, 0x4f, 0xe3, 0xc6,
	0x1b, 0x8e, 0xd9, 0x10, 0x60, 0x02, 0xab, 0x61, 0x7e, 0x3f, 0x2d, 0x29, 0x5d, 0xa2, 0x90, 0xee,
	0x1f, 0x94, 0xb6, 0xc9, 0x26, 0xac, 0x7a, 0x68, 0x2b, 0x55, 0x8e, 0x3d, 0x59, 0x46, 0x38, 0x36,
	0xb2, 0x4d, 0x28, 0xbd, 0x8c, 0x9c, 0x78, 0x36, 0x58, 0x10, 0x1b, 0x79, 0x1c, 0xda, 0x5c, 0x2b,
	0xf5, 0xd2, 0x53, 0xcf, 0xfd, 0x14, 0x7b, 0xe8, 0x87, 0xd8, 0x43, 0x0f, 0xab, 0x9e, 0x7a, 0xac,
	0x40, 0x15, 0x1f, 0xa0, 0xa7, 0xde, 0x2a, 0xff, 0x0b, 0x90, 0x3f, 0x68, 0xf7, 0x12, 0x69, 0xde,
	0xf7, 0x79, 0xdf, 0xf7, 0x79, 0x9f, 0x79, 0xc6, 0x0a, 0x78, 0x14, 0x58, 0xfc, 0xb4, 0x76, 0x51,
	0xaf, 0xd9, 0xcc, 0xb2, 0xcf, 0x1c, 0x97, 0x55, 0xcf, 0x7d, 0x2f, 0xf0, 0xd0, 0x52, 0x18, 0xaf,
	0x5e, 0xd4, 0x37, 0xd7, 0xad, 0x81, 0xe3, 0x7a, 0xb5, 0xe8, 0x37, 0xce, 0x6d, 0x6e, 0xf4, 0x3c,
	0x3e, 0xf0, 0x78, 0x6d, 0xc0, 0xfb, 0x61, 0xe5, 0x80, 0xf7, 0x93, 0xc4, 0x47, 0x71, 0x82, 0x46,
	0xa7, 0x5a, 0x7c, 0x48, 0x52, 0x8f, 0xf8, 0x89, 0xe5, 0x33, 0x3b, 0xc4, 0xf7, 0xbc, 0xc1, 0xc0,
	0x73, 0x93, 0xf8, 0xd6, 0x4d, 0xdc, 0x67, 0x3c, 0xa0, 0xcc, 0xed, 0x79, 0xb6, 0xe3, 0x26, 0x1d,
	0xcb, 0x3e, 0xf8, 0x9f, 0x69, 0xf1, 0x53, 0x39, 0x21, 0xa7, 0x78, 0x3d, 0x2b, 0xf0, 0x7c, 0xb4,
	0x05, 0x22, 0x7e, 0xd4, 0xb1, 0x0b, 0x42, 0x49, 0xd8, 0x59, 0x6d, 0x66, 0xdf, 0xfe, 0x53, 0x58,
	0xd0, 0x73, 0x61, 0x90, 0xd8, 0xe8, 0x6b, 0xb0, 0x96, 0xae, 0x43, 0x4f, 0x1d, 0xd7, 0x2e, 0x2c,
	0x94, 0x84, 0x9d, 0x87, 0x8d, 0x8d, 0x6a, 0xb2, 0x54, 0x35, 0xed, 0xb7, 0xef, 0xb8, 0x76, 0xa7,
	0xae, 0xaf, 0xda, 0xb7, 0xce, 0xe5, 0x5f, 0x05, 0x50, 0x08, 0x87, 0xea, 0xde, 0xd0, 0xb5, 0x3f,
	0x70, 0xf2, 0x36, 0x58, 0xbd, 0x60, 0xbe, 0xf3, 0x7a, 0x44, 0xfd, 0xb0, 0x3a, 0x1a, 0xbc, 0xa6,
	0xe7, 0xe3, 0x58, 0xd4, 0x70, 0x9a, 0xdc, 0x83, 0x0f, 0x21, 0x37, 0x02, 0x1b, 0x06, 0xe3, 0xdc,
	0xf1, 0x5c, 0xc5, 0x79, 0xcd, 0x7a, 0xa3, 0xde, 0xd9, 0x98, 0xda, 0x0e, 0x58, 0xec, 0x8e, 0x52,
	0x62, 0xf9, 0xc6, 0x7a, 0x35, 0x96, 0x36, 0x6c, 0xd9, 0x1c, 0x11, 0xb9, 0x53, 0xdf, 0xcb, 0xe8,
	0xd9, 0xee, 0x88, 0xd8, 0xa8, 0x02, 0x16, 0xbb, 0x56, 0xd0, 0x3b, 0x89, 0xe8, 0xe5, 0x1b, 0xe8,
	0x36, 0x32, 0x8c, 0x47, 0xd0, 0x18, 0xd2, 0x5c, 0x06, 0xb9, 0xc0, 0xf2, 0xfb, 0x2c, 0x28, 0x5f,
	0x0b, 0x60, 0x7d, 0x42, 0x8e, 0x4e, 0x1d, 0x35, 0x40, 0x36, 0x24, 0x9e, 0x0c, 0x7d, 0x3c, 0xde,
	0x62, 0xc6, 0xb5, 0x85, 0xf3, 0xc3, 0x34, 0x6a, 0x02, 0x10, 0x89, 0x78, 0xa3, 0x51, 0xbe, 0xb1,
	0x7d, 0xa7, 0x72, 0x96, 0xf6, 0x7b, 0x19, 0x7d, 0x25, 0x48, 0x73, 0x48, 0x03, 0xeb, 0x3c, 0x16,
	0x82, 0x9e, 0xa5, 0x4a, 0x14, 0xb2, 0x51, 0xab, 0xd2, 0xb8, 0xd5, 0x1c, 0xa9, 0xf6, 0x32, 0x3a,
	0xe4, 0x13, 0xa9, 0xe6, 0x0a, 0x58, 0x3a, 0x8b, 0xd3, 0xe5, 0xdf, 0x05, 0x00, 0xdb, 0xbc, 0x6f,
	0x7c, 0xcf, 0xd8, 0x79, 0x4a, 0x02, 0xbd, 0x1c, 0xe7, 0x93, 0x5d, 0x37, 0xa7, 0x6e, 0x6c, 0xac,
	0x8a, 0x9e, 0x42, 0x11, 0x06, 0xeb, 0x7c, 0xd8, 0x1d, 0x38, 0x41, 0xc0, 0x7c, 0x6a, 0xd9, 0xb6,
	0xcf, 0x38, 0x8f, 0x36, 0x5e, 0x69, 0x16, 0xfe, 0xf8, 0xed, 0xf3, 0xff, 0x27, 0x8f, 0x44, 0x8c,
	0x33, 0x46, 0xe0, 0x3b, 0x6e, 0x5f, 0x87, 0xe3, 0x92, 0x24, 0xfe, 0xe5, 0x57, 0x3f, 0x5e, 0xbf,
	0xa9, 0x4c, 0x77, 0xfa, 0xf9, 0xfa, 0x4d, 0xa5, 0x14, 0xf8, 0x43, 0xe6, 0x9d, 0x33, 0xb7, 0xf6,
	0x43, 0x2d, 0x7a, 0xcc, 0x93, 0xcc, 0xcb, 0x3f, 0x09, 0xa0, 0x30, 0x19, 0xd4, 0x19, 0x3f, 0xf7,
	0x5c, 0xce, 0x50, 0x01, 0x2c, 0x5d, 0x38, 0xdc, 0x09, 0x58, 0xec, 0x9b, 0x35, 0x3d, 0x3d, 0xa2,
	0x4d, 0xb0, 0x6c, 0xd9, 0x17, 0x96, 0xdb, 0x63, 0xa9, 0x8f, 0xc7, 0x67, 0xb4, 0x0b, 0x72, 0x3c,
	0xb0, 0x82, 0x21, 0x4f, 0xdc, 0xfb, 0xf1, 0x2d, 0x0b, 0xb5, 0x87, 0x81, 0x15, 0x38, 0x9e, 0x6b,
	0x44, 0x80, 0x4e, 0x5d, 0x4f, 0xa0, 0x95, 0x7f, 0x1f, 0x80, 0x87, 0x77, 0xcd, 0x8d, 0x4a, 0xe0,
	0xb1, 0x8c, 0x45, 0x59, 0x21, 0x2a, 0xa6, 0xfb, 0x44, 0x95, 0x69, 0xa7, 0x4e, 0x0f, 0x55, 0xe3,
	0x00, 0x4b, 0xa4, 0x45, 0xb0, 0x0c, 0x33, 0xa8, 0x0c, 0x8a, 0x53, 0x08, 0x53, 0x34, 0xf6, 0x69,
	0x8b, 0xa8, 0xa2, 0x42, 0xcc, 0x63, 0x28, 0xa0, 0x27, 0xa0, 0x34, 0x1b, 0x63, 0x60, 0xd3, 0x54,
	0x70, 0x1b, 0xab, 0x26, 0x5c, 0x40, 0xcf, 0xc1, 0x27, 0x53, 0xa8, 0x0e, 0xd6, 0x49, 0xeb, 0x98,
	0xea, 0xda, 0xa1, 0x2a, 0x53, 0x49, 0xd1, 0x0c, 0x0c, 0xb3, 0x33, 0x47, 0xa6, 0x40, 0xdc, 0xc1,
	0xa2, 0x02, 0x17, 0xef, 0xc3, 0x48, 0x5a, 0xbb, 0x4d, 0x4c, 0x98, 0x9b, 0xb9, 0x5c, 0x82, 0xd1,
	0x0e, 0xb0, 0x0a, 0x97, 0xd0, 0x36, 0xd8, 0x9a, 0x42, 0x1c, 0x69, 0xfa, 0x3e, 0xd6, 0x29, 0x51,
	0x5b, 0x58, 0x87, 0xcb, 0xe8, 0x19, 0x28, 0xcf, 0x83, 0x88, 0x86, 0x41, 0x5e, 0xa9, 0xd1, 0x76,
	0x2b, 0x33, 0x71, 0x06, 0x36, 0x0c, 0xa2, 0xa9, 0x54, 0x21, 0x2d, 0x2c, 0x1d, 0x4b, 0x0a, 0x86,
	0x60, 0xe6, 0xc8, 0x84, 0x54, 0xa4, 0x28, 0xcc, 0xa3, 0x4f, 0xc1, 0xf3, 0x29, 0x88, 0xb4, 0x27,
	0x2a, 0x0a, 0x56, 0x5f, 0x61, 0x7a, 0x44, 0x54, 0x59, 0x3b, 0x4a, 0xc4, 0x5a, 0x45, 0x4f, 0xc1,
	0xf6, 0x14, 0x18, 0x77, 0x88, 0x8c, 0x55, 0x09, 0x53, 0x49, 0xc1, 0xa2, 0x7a, 0x78, 0x00, 0xd7,
	0x2a, 0x7f, 0x67, 0xc1, 0xa3, 0xf4, 0xee, 0x4d, 0xdf, 0x72, 0xb9, 0x13, 0x5a, 0x44, 0xf2, 0x6c,
	0x86, 0x76, 0xc0, 0x93, 0x71, 0x07, 0x53, 0x17, 0x55, 0x83, 0x98, 0x21, 0x69, 0x49, 0x93, 0xf1,
	0x84, 0x17, 0x76, 0x41, 0x6d, 0x2e, 0x32, 0xdd, 0x55, 0x94, 0x4c, 0xd2, 0xc1, 0xd4, 0xd4, 0x28,
	0x91, 0x15, 0x0c, 0x85, 0xf7, 0x2a, 0x0a, 0xa1, 0x61, 0x49, 0xb4, 0x94, 0x0c, 0x17, 0x50, 0x15,
	0x54, 0xe6, 0x16, 0xdd, 0xc8, 0x4e, 0x5b, 0x22, 0x51, 0xb0, 0x0c, 0x1f, 0xdc, 0x91, 0x6c, 0x12,
	0x9f, 0xdc, 0x96, 0x49, 0xda, 0x58, 0x3b, 0x34, 0x61, 0x16, 0xbd, 0x00, 0x9f, 0xcd, 0x05, 0xdf,
	0xf2, 0xc7, 0xb8, 0x62, 0x11, 0x55, 0xc0, 0xb3, 0xb9, 0x15, 0xb1, 0xdd, 0x52, 0xea, 0xb9, 0x7b,
	0xb1, 0xb1, 0x7d, 0x53, 0xec, 0xd2, 0xfb, 0x30, 0xb9, 0xf5, 0x34, 0x64, 0xb8, 0x8c, 0x5e, 0x82,
	0x17, 0xf3, 0x99, 0xcc, 0xf4, 0x88, 0x0c, 0x57, 0xee, 0x9d, 0x73, 0xf3, 0x46, 0x29, 0xfe, 0x16,
	0x4b, 0x87, 0x26, 0x96, 0x21, 0x40, 0x5f, 0x80, 0xc6, 0xdc, 0x8a, 0x49, 0x7b, 0x51, 0x51, 0xee,
	0x88, 0xaa, 0x84, 0x65, 0x98, 0x6f, 0x7e, 0xf3, 0xf6, 0xb2, 0x28, 0xbc, 0xbb, 0x2c, 0x0a, 0x7f,
	0x5d, 0x16, 0x85, 0x5f, 0xae, 0x8a, 0x99, 0x77, 0x57, 0xc5, 0xcc, 0x9f, 0x57, 0xc5, 0xcc, 0x77,
	0x4f, 0xfb, 0x4e, 0x70, 0x32, 0xec, 0x56, 0x7b, 0xde, 0xa0, 0x66, 0xfa, 0x43, 0xa6, 0x85, 0x9f,
	0x4c, 0xd7, 0xb3, 0x59, 0xfa, 0xdd, 0x0c, 0x46, 0xe7, 0x8c, 0x77, 0x73, 0xd1, 0x1f, 0x8f, 0xdd,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x72, 0x38, 0xce, 0xc5, 0x19, 0x09, 0x00, 0x00,
}

func (m *TaskDeadlineLocator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskDeadlineLocator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskDeadlineLocator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeadlineKind != 0 {
		i = encodeVarintDeadline(dAtA, i, uint64(m.DeadlineKind))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintDeadline(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaskRoundDeadlineLocator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskRoundDeadlineLocator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskRoundDeadlineLocator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeadlineKind != 0 {
		i = encodeVarintDeadline(dAtA, i, uint64(m.DeadlineKind))
		i--
		dAtA[i] = 0x18
	}
	if m.VerifyRound != 0 {
		i = encodeVarintDeadline(dAtA, i, uint64(m.VerifyRound))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintDeadline(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SessionLifecycleLocator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SessionLifecycleLocator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionLifecycleLocator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Target != nil {
		{
			size := m.Target.Size()
			i -= size
			if _, err := m.Target.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *SessionLifecycleLocator_ById) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionLifecycleLocator_ById) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ById != nil {
		{
			size, err := m.ById.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeadline(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *SessionLifecycleLocator_Batch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionLifecycleLocator_Batch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Batch != nil {
		{
			size, err := m.Batch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeadline(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *DeadlineLocatorV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeadlineLocatorV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeadlineLocatorV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Locator != nil {
		{
			size := m.Locator.Size()
			i -= size
			if _, err := m.Locator.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *DeadlineLocatorV1_Task) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeadlineLocatorV1_Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Task != nil {
		{
			size, err := m.Task.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeadline(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *DeadlineLocatorV1_TaskRound) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeadlineLocatorV1_TaskRound) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.TaskRound != nil {
		{
			size, err := m.TaskRound.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeadline(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *DeadlineLocatorV1_SessionLifecycle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeadlineLocatorV1_SessionLifecycle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SessionLifecycle != nil {
		{
			size, err := m.SessionLifecycle.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeadline(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *MsgSweepDeadline) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSweepDeadline) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSweepDeadline) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubmitterAddress) > 0 {
		i -= len(m.SubmitterAddress)
		copy(dAtA[i:], m.SubmitterAddress)
		i = encodeVarintDeadline(dAtA, i, uint64(len(m.SubmitterAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Locator != nil {
		{
			size, err := m.Locator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeadline(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSweepDeadlineResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSweepDeadlineResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSweepDeadlineResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintDeadline(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.Advanced != 0 {
		i = encodeVarintDeadline(dAtA, i, uint64(m.Advanced))
		i--
		dAtA[i] = 0x10
	}
	if m.Visited != 0 {
		i = encodeVarintDeadline(dAtA, i, uint64(m.Visited))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeadline(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeadline(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TaskDeadlineLocator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovDeadline(uint64(l))
	}
	if m.DeadlineKind != 0 {
		n += 1 + sovDeadline(uint64(m.DeadlineKind))
	}
	return n
}

func (m *TaskRoundDeadlineLocator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovDeadline(uint64(l))
	}
	if m.VerifyRound != 0 {
		n += 1 + sovDeadline(uint64(m.VerifyRound))
	}
	if m.DeadlineKind != 0 {
		n += 1 + sovDeadline(uint64(m.DeadlineKind))
	}
	return n
}

func (m *SessionLifecycleLocator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Target != nil {
		n += m.Target.Size()
	}
	return n
}

func (m *SessionLifecycleLocator_ById) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ById != nil {
		l = m.ById.Size()
		n += 1 + l + sovDeadline(uint64(l))
	}
	return n
}
func (m *SessionLifecycleLocator_Batch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Batch != nil {
		l = m.Batch.Size()
		n += 1 + l + sovDeadline(uint64(l))
	}
	return n
}
func (m *DeadlineLocatorV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Locator != nil {
		n += m.Locator.Size()
	}
	return n
}

func (m *DeadlineLocatorV1_Task) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Task != nil {
		l = m.Task.Size()
		n += 1 + l + sovDeadline(uint64(l))
	}
	return n
}
func (m *DeadlineLocatorV1_TaskRound) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskRound != nil {
		l = m.TaskRound.Size()
		n += 1 + l + sovDeadline(uint64(l))
	}
	return n
}
func (m *DeadlineLocatorV1_SessionLifecycle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SessionLifecycle != nil {
		l = m.SessionLifecycle.Size()
		n += 1 + l + sovDeadline(uint64(l))
	}
	return n
}
func (m *MsgSweepDeadline) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Locator != nil {
		l = m.Locator.Size()
		n += 1 + l + sovDeadline(uint64(l))
	}
	l = len(m.SubmitterAddress)
	if l > 0 {
		n += 1 + l + sovDeadline(uint64(l))
	}
	return n
}

func (m *MsgSweepDeadlineResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Visited != 0 {
		n += 1 + sovDeadline(uint64(m.Visited))
	}
	if m.Advanced != 0 {
		n += 1 + sovDeadline(uint64(m.Advanced))
	}
	if m.Status != 0 {
		n += 1 + sovDeadline(uint64(m.Status))
	}
	return n
}

func sovDeadline(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeadline(x uint64) (n int) {
	return sovDeadline(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TaskDeadlineLocator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskDeadlineLocator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskDeadlineLocator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadlineKind", wireType)
			}
			m.DeadlineKind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeadlineKind |= DeadlineKindV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDeadline(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeadline
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskRoundDeadlineLocator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskRoundDeadlineLocator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskRoundDeadlineLocator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyRound", wireType)
			}
			m.VerifyRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifyRound |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadlineKind", wireType)
			}
			m.DeadlineKind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeadlineKind |= DeadlineKindV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDeadline(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeadline
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SessionLifecycleLocator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SessionLifecycleLocator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SessionLifecycleLocator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ById", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.ByIDV1{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Target = &SessionLifecycleLocator_ById{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.BatchV1{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Target = &SessionLifecycleLocator_Batch{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeadline(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeadline
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeadlineLocatorV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeadlineLocatorV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeadlineLocatorV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Task", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TaskDeadlineLocator{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Locator = &DeadlineLocatorV1_Task{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskRound", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TaskRoundDeadlineLocator{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Locator = &DeadlineLocatorV1_TaskRound{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionLifecycle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &SessionLifecycleLocator{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Locator = &DeadlineLocatorV1_SessionLifecycle{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeadline(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeadline
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSweepDeadline) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSweepDeadline: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSweepDeadline: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Locator == nil {
				m.Locator = &DeadlineLocatorV1{}
			}
			if err := m.Locator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeadline
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeadline
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubmitterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeadline(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeadline
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSweepDeadlineResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSweepDeadlineResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSweepDeadlineResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Visited", wireType)
			}
			m.Visited = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Visited |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advanced", wireType)
			}
			m.Advanced = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Advanced |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types.MutationStatusV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDeadline(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeadline
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeadline(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeadline
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeadline
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeadline
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeadline
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeadline
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeadline        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeadline          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeadline = fmt.Errorf("proto: unexpected end of group")
)
