// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/TrueOpen/node/x/shared/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("task/v1/tx.proto", fileDescriptor_68feb0c89782b8e7) }

var fileDescriptor_68feb0c89782b8e7 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xdf, 0x4e, 0xd4, 0x4e,
	0x14, 0xc7, 0xd9, 0xfc, 0xf2, 0xd3, 0x64, 0xd4, 0x84, 0x4c, 0x04, 0x64, 0x20, 0x55, 0x14, 0x45,
	0x81, 0x6c, 0x03, 0x3e, 0x80, 0x09, 0x8b, 0x51, 0x2f, 0x08, 0x66, 0x17, 0xd6, 0xc4, 0x98, 0x90,
	0x69, 0x7b, 0xe8, 0x8e, 0xdb, 0xce, 0x34, 0x33, 0xd3, 0x05, 0xee, 0x7c, 0x04, 0x1f, 0xc5, 0xc7,
	0xf0, 0x92, 0x4b, 0x2f, 0x0d, 0x5c, 0x78, 0xe1, 0x4b, 0x98, 0x6e, 0xdb, 0x61, 0xca, 0x76, 0xff,
	0xdc, 0x9e, 0xcf, 0x77, 0xbe, 0x67, 0xce, 0xe9, 0xe9, 0x19, 0x34, 0xaf, 0xa9, 0xea, 0xbb, 0x83,
	0x1d, 0x57, 0x9f, 0x37, 0x13, 0x29, 0xb4, 0xc0, 0x77, 0xb3, 0x48, 0x73, 0xb0, 0x43, 0x96, 0x7c,
	0xa1, 0x62, 0xa1, 0xdc, 0x58, 0x85, 0x99, 0x20, 0x56, 0x61, 0xae, 0x20, 0x1b, 0xaa, 0x47, 0x25,
	0x04, 0x59, 0x10, 0x06, 0x2c, 0x00, 0xee, 0xc3, 0x89, 0x04, 0x95, 0x08, 0xae, 0x98, 0xc7, 0x22,
	0xa6, 0x2f, 0x0a, 0xa1, 0x53, 0x9a, 0x7b, 0x29, 0x8b, 0x02, 0x90, 0x27, 0xa5, 0xbc, 0xe0, 0x8b,
	0x25, 0x0f, 0x80, 0x06, 0x11, 0xe3, 0x65, 0x7c, 0xb5, 0x8c, 0xc7, 0x2a, 0x3c, 0xa1, 0x4a, 0xb1,
	0x90, 0xc7, 0xc0, 0x75, 0x41, 0x57, 0x6c, 0xea, 0xf7, 0x68, 0x14, 0x01, 0x0f, 0xcb, 0xa3, 0xcb,
	0x36, 0x54, 0xa0, 0x14, 0x13, 0xbc, 0xce, 0x55, 0x81, 0xd6, 0x11, 0x58, 0xae, 0x8e, 0x4d, 0x07,
	0x20, 0xd9, 0x29, 0xf3, 0xa9, 0x36, 0xa7, 0x77, 0xff, 0xde, 0x47, 0xff, 0x1d, 0xa8, 0x10, 0x77,
	0xd1, 0xfc, 0x71, 0x12, 0x50, 0x0d, 0x47, 0x54, 0xf5, 0x3f, 0x52, 0x49, 0x63, 0x85, 0x57, 0x9b,
	0x45, 0xcf, 0x9a, 0x07, 0x2a, 0xbc, 0x4d, 0xc9, 0xfa, 0x24, 0xda, 0xce, 0xfb, 0x06, 0xf8, 0x00,
	0x3d, 0x68, 0x49, 0xa0, 0x1a, 0x3a, 0xf9, 0xa5, 0xf1, 0xb2, 0x7d, 0xac, 0x82, 0xc8, 0xda, 0x58,
	0x64, 0xec, 0xde, 0xa1, 0x7b, 0x2d, 0xca, 0x7d, 0x88, 0x0e, 0x65, 0x00, 0x12, 0x2f, 0x55, 0x4e,
	0xdc, 0x00, 0xf2, 0x78, 0x0c, 0x30, 0x46, 0x3d, 0xb4, 0xd8, 0x49, 0xbd, 0x98, 0xe9, 0x4f, 0x42,
	0xf6, 0x41, 0xbe, 0xa7, 0x3c, 0x90, 0x94, 0x29, 0x50, 0xf8, 0xa9, 0x7d, 0xb4, 0x5e, 0x43, 0x36,
	0xa7, 0x6b, 0x4c, 0xa6, 0x2f, 0x08, 0xe7, 0x8a, 0x0f, 0xfc, 0x34, 0xbb, 0x80, 0x0f, 0x2c, 0xd1,
	0xd8, 0x19, 0x75, 0xb0, 0x39, 0x79, 0x31, 0x99, 0x1b, 0x77, 0x0f, 0x3d, 0xb4, 0xf3, 0xbf, 0x2d,
	0x26, 0x11, 0x3f, 0x19, 0x77, 0xc3, 0x52, 0x41, 0x5e, 0x4e, 0x53, 0x98, 0x1c, 0x67, 0x68, 0x25,
	0xe7, 0xdd, 0xe1, 0xfc, 0x80, 0xec, 0xd2, 0x28, 0x05, 0x93, 0x6a, 0x63, 0xd4, 0xa8, 0x56, 0x48,
	0xdc, 0x19, 0x85, 0x26, 0x31, 0x47, 0x8f, 0xaa, 0x32, 0xeb, 0x33, 0xad, 0x8f, 0x37, 0xb3, 0x3e,
	0xd4, 0xf6, 0x2c, 0x2a, 0x93, 0x0f, 0xd0, 0x42, 0x1b, 0x12, 0x21, 0xf5, 0x3e, 0xd5, 0xf4, 0x98,
	0xd3, 0x01, 0x65, 0x11, 0xf5, 0x22, 0xc0, 0x95, 0xc9, 0xac, 0x95, 0x90, 0x57, 0x53, 0x25, 0xd6,
	0xec, 0x2d, 0xe4, 0x57, 0xd9, 0xcb, 0xf7, 0x87, 0xe9, 0xe4, 0xda, 0xe8, 0x6d, 0x6f, 0x49, 0xc8,
	0x76, 0x33, 0xdf, 0x52, 0x99, 0xa8, 0x60, 0x87, 0xde, 0x57, 0xf0, 0x35, 0x1b, 0x58, 0xfd, 0x1b,
	0xce, 0x48, 0x77, 0xf7, 0x66, 0xf6, 0x86, 0x45, 0x5f, 0xb4, 0x44, 0x1c, 0xb3, 0xda, 0xd9, 0xb3,
	0x79, 0xdd, 0xec, 0xd9, 0xdc, 0xd4, 0xd1, 0x47, 0x4b, 0x7b, 0x54, 0xfb, 0xbd, 0x9a, 0x14, 0xcf,
	0x6c, 0x8b, 0x31, 0x22, 0xb2, 0x35, 0x83, 0x68, 0xf4, 0x37, 0xca, 0x69, 0x1b, 0x54, 0x1a, 0x4d,
	0x28, 0x25, 0xe7, 0xe3, 0x4b, 0xc9, 0xf9, 0xc4, 0x52, 0x8a, 0x14, 0x93, 0x4b, 0x29, 0xf2, 0x6c,
	0xcd, 0x20, 0xb2, 0x4b, 0x39, 0x4c, 0x80, 0xb7, 0xca, 0x1d, 0xdf, 0x16, 0x29, 0x0f, 0xaa, 0xa5,
	0x8c, 0xf2, 0x6a, 0x29, 0xa3, 0xdc, 0xb8, 0xef, 0x23, 0xd4, 0x19, 0xbe, 0x02, 0xd9, 0x36, 0xc6,
	0x8b, 0x95, 0x06, 0x98, 0x38, 0x71, 0xea, 0xe3, 0xf6, 0xde, 0xee, 0x9c, 0x01, 0x24, 0xfb, 0xc5,
	0x13, 0x56, 0xdd, 0xdb, 0x15, 0x54, 0xdd, 0xdb, 0x15, 0x54, 0xda, 0x91, 0xff, 0xbf, 0xfd, 0xf9,
	0xb1, 0xd9, 0xd8, 0x7b, 0xf3, 0xf3, 0xca, 0x69, 0x5c, 0x5e, 0x39, 0x8d, 0xdf, 0x57, 0x4e, 0xe3,
	0xfb, 0xb5, 0x33, 0x77, 0x79, 0xed, 0xcc, 0xfd, 0xba, 0x76, 0xe6, 0x3e, 0x3f, 0x0f, 0x99, 0xee,
	0xa5, 0x5e, 0xd3, 0x17, 0xb1, 0x7b, 0x24, 0x53, 0xc8, 0x0a, 0x74, 0xb9, 0x08, 0xc0, 0x3d, 0x77,
	0x87, 0x4f, 0x98, 0xbe, 0x48, 0x40, 0x79, 0x77, 0x86, 0xaf, 0xd6, 0xeb, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x29, 0xa3, 0xf4, 0xab, 0xe0, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateTaskParams applies one governance Task params version.
	UpdateTaskParams(ctx context.Context, in *MsgUpdateTaskParams, opts ...grpc.CallOption) (*MsgUpdateTaskParamsResponse, error)
	// CreateSession derives one new session from the signer's SessionNonce.
	CreateSession(ctx context.Context, in *MsgCreateSession, opts ...grpc.CallOption) (*MsgCreateSessionResponse, error)
	// CancelOrder skips one unused order sequence.
	CancelOrder(ctx context.Context, in *MsgCancelOrder, opts ...grpc.CallOption) (*MsgCancelOrderResponse, error)
	// SubmitWorkerHandraises is the single Task admission and Worker candidate
	// entry; it replaces the deleted MsgAssign.
	// SubmitWorkerHandraises executes the SubmitWorkerHandraises operation.
	SubmitWorkerHandraises(ctx context.Context, in *MsgSubmitWorkerHandraises, opts ...grpc.CallOption) (*MsgSubmitWorkerHandraisesResponse, error)
	// SubmitInferReceipt accepts the winner Worker's inference receipt; it
	// replaces the deleted MsgInferReceiptCommitOnly.
	// SubmitInferReceipt executes the SubmitInferReceipt operation.
	SubmitInferReceipt(ctx context.Context, in *MsgSubmitInferReceipt, opts ...grpc.CallOption) (*MsgSubmitInferReceiptResponse, error)
	// SubmitWorkerEvidence accepts one strict-encoded objective Worker proof.
	SubmitWorkerEvidence(ctx context.Context, in *MsgSubmitWorkerEvidence, opts ...grpc.CallOption) (*MsgSubmitWorkerEvidenceResponse, error)
	// SubmitVerifierValueEvidence is registered but returns ERR_NOT_ACTIVATED.
	SubmitVerifierValueEvidence(ctx context.Context, in *MsgSubmitVerifierValueEvidence, opts ...grpc.CallOption) (*MsgSubmitVerifierValueEvidenceResponse, error)
	// SubmitVerifierHandraises is the single Open Verify entry; it replaces the
	// deleted MsgOpenVerify.
	// SubmitVerifierHandraises executes the SubmitVerifierHandraises operation.
	SubmitVerifierHandraises(ctx context.Context, in *MsgSubmitVerifierHandraises, opts ...grpc.CallOption) (*MsgSubmitVerifierHandraisesResponse, error)
	// ReportDataUnavailable records one selected Verifier's data-availability report.
	ReportDataUnavailable(ctx context.Context, in *MsgReportDataUnavailable, opts ...grpc.CallOption) (*MsgReportDataUnavailableResponse, error)
	// SubmitBuilderEvidence accepts one closed typed objective Builder proof.
	// It moved here from hub.v1.Msg: the Task module owns the
	// envelope payload and the Task authority, and it returns the shared receipt
	// directly instead of a module-local Response wrapper.
	// SubmitBuilderEvidence executes the SubmitBuilderEvidence operation.
	SubmitBuilderEvidence(ctx context.Context, in *MsgSubmitBuilderEvidence, opts ...grpc.CallOption) (*types.BuilderObjectiveEvidenceReceiptV2, error)
	// SubmitVerifyCommit replaces the deleted MsgCommit.
	SubmitVerifyCommit(ctx context.Context, in *MsgSubmitVerifyCommit, opts ...grpc.CallOption) (*MsgSubmitVerifyCommitResponse, error)
	// BatchSubmitVerifyCommit replaces the deleted MsgBatchCommit.
	BatchSubmitVerifyCommit(ctx context.Context, in *MsgBatchSubmitVerifyCommit, opts ...grpc.CallOption) (*MsgBatchSubmitVerifyCommitResponse, error)
	// SubmitVerifyResult replaces the deleted MsgResult.
	SubmitVerifyResult(ctx context.Context, in *MsgSubmitVerifyResult, opts ...grpc.CallOption) (*MsgSubmitVerifyResultResponse, error)
	// BatchSubmitVerifyResult replaces the deleted MsgBatchResult.
	BatchSubmitVerifyResult(ctx context.Context, in *MsgBatchSubmitVerifyResult, opts ...grpc.CallOption) (*MsgBatchSubmitVerifyResultResponse, error)
	// OpenChallengeRound opens the fixed funded verification round 2.
	OpenChallengeRound(ctx context.Context, in *MsgOpenChallengeRound, opts ...grpc.CallOption) (*MsgOpenChallengeRoundResponse, error)
	// SettleTask derives and atomically applies the sole Phase 0 settlement plan.
	SettleTask(ctx context.Context, in *MsgSettleTask, opts ...grpc.CallOption) (*MsgSettleTaskResponse, error)
	// SweepDeadline is the single bounded deadline runner; it replaces the deleted
	// MsgSweepExpiredTask and MsgSessionSweep.
	// SweepDeadline executes the SweepDeadline operation.
	SweepDeadline(ctx context.Context, in *MsgSweepDeadline, opts ...grpc.CallOption) (*MsgSweepDeadlineResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateTaskParams(ctx context.Context, in *MsgUpdateTaskParams, opts ...grpc.CallOption) (*MsgUpdateTaskParamsResponse, error) {
	out := new(MsgUpdateTaskParamsResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/UpdateTaskParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSession(ctx context.Context, in *MsgCreateSession, opts ...grpc.CallOption) (*MsgCreateSessionResponse, error) {
	out := new(MsgCreateSessionResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelOrder(ctx context.Context, in *MsgCancelOrder, opts ...grpc.CallOption) (*MsgCancelOrderResponse, error) {
	out := new(MsgCancelOrderResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitWorkerHandraises(ctx context.Context, in *MsgSubmitWorkerHandraises, opts ...grpc.CallOption) (*MsgSubmitWorkerHandraisesResponse, error) {
	out := new(MsgSubmitWorkerHandraisesResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitWorkerHandraises", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitInferReceipt(ctx context.Context, in *MsgSubmitInferReceipt, opts ...grpc.CallOption) (*MsgSubmitInferReceiptResponse, error) {
	out := new(MsgSubmitInferReceiptResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitInferReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitWorkerEvidence(ctx context.Context, in *MsgSubmitWorkerEvidence, opts ...grpc.CallOption) (*MsgSubmitWorkerEvidenceResponse, error) {
	out := new(MsgSubmitWorkerEvidenceResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitWorkerEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitVerifierValueEvidence(ctx context.Context, in *MsgSubmitVerifierValueEvidence, opts ...grpc.CallOption) (*MsgSubmitVerifierValueEvidenceResponse, error) {
	out := new(MsgSubmitVerifierValueEvidenceResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitVerifierValueEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitVerifierHandraises(ctx context.Context, in *MsgSubmitVerifierHandraises, opts ...grpc.CallOption) (*MsgSubmitVerifierHandraisesResponse, error) {
	out := new(MsgSubmitVerifierHandraisesResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitVerifierHandraises", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReportDataUnavailable(ctx context.Context, in *MsgReportDataUnavailable, opts ...grpc.CallOption) (*MsgReportDataUnavailableResponse, error) {
	out := new(MsgReportDataUnavailableResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/ReportDataUnavailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitBuilderEvidence(ctx context.Context, in *MsgSubmitBuilderEvidence, opts ...grpc.CallOption) (*types.BuilderObjectiveEvidenceReceiptV2, error) {
	out := new(types.BuilderObjectiveEvidenceReceiptV2)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitBuilderEvidence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitVerifyCommit(ctx context.Context, in *MsgSubmitVerifyCommit, opts ...grpc.CallOption) (*MsgSubmitVerifyCommitResponse, error) {
	out := new(MsgSubmitVerifyCommitResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitVerifyCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BatchSubmitVerifyCommit(ctx context.Context, in *MsgBatchSubmitVerifyCommit, opts ...grpc.CallOption) (*MsgBatchSubmitVerifyCommitResponse, error) {
	out := new(MsgBatchSubmitVerifyCommitResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/BatchSubmitVerifyCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitVerifyResult(ctx context.Context, in *MsgSubmitVerifyResult, opts ...grpc.CallOption) (*MsgSubmitVerifyResultResponse, error) {
	out := new(MsgSubmitVerifyResultResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SubmitVerifyResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BatchSubmitVerifyResult(ctx context.Context, in *MsgBatchSubmitVerifyResult, opts ...grpc.CallOption) (*MsgBatchSubmitVerifyResultResponse, error) {
	out := new(MsgBatchSubmitVerifyResultResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/BatchSubmitVerifyResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) OpenChallengeRound(ctx context.Context, in *MsgOpenChallengeRound, opts ...grpc.CallOption) (*MsgOpenChallengeRoundResponse, error) {
	out := new(MsgOpenChallengeRoundResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/OpenChallengeRound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SettleTask(ctx context.Context, in *MsgSettleTask, opts ...grpc.CallOption) (*MsgSettleTaskResponse, error) {
	out := new(MsgSettleTaskResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SettleTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SweepDeadline(ctx context.Context, in *MsgSweepDeadline, opts ...grpc.CallOption) (*MsgSweepDeadlineResponse, error) {
	out := new(MsgSweepDeadlineResponse)
	err := c.cc.Invoke(ctx, "/task.v1.Msg/SweepDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateTaskParams applies one governance Task params version.
	UpdateTaskParams(context.Context, *MsgUpdateTaskParams) (*MsgUpdateTaskParamsResponse, error)
	// CreateSession derives one new session from the signer's SessionNonce.
	CreateSession(context.Context, *MsgCreateSession) (*MsgCreateSessionResponse, error)
	// CancelOrder skips one unused order sequence.
	CancelOrder(context.Context, *MsgCancelOrder) (*MsgCancelOrderResponse, error)
	// SubmitWorkerHandraises is the single Task admission and Worker candidate
	// entry; it replaces the deleted MsgAssign.
	// SubmitWorkerHandraises executes the SubmitWorkerHandraises operation.
	SubmitWorkerHandraises(context.Context, *MsgSubmitWorkerHandraises) (*MsgSubmitWorkerHandraisesResponse, error)
	// SubmitInferReceipt accepts the winner Worker's inference receipt; it
	// replaces the deleted MsgInferReceiptCommitOnly.
	// SubmitInferReceipt executes the SubmitInferReceipt operation.
	SubmitInferReceipt(context.Context, *MsgSubmitInferReceipt) (*MsgSubmitInferReceiptResponse, error)
	// SubmitWorkerEvidence accepts one strict-encoded objective Worker proof.
	SubmitWorkerEvidence(context.Context, *MsgSubmitWorkerEvidence) (*MsgSubmitWorkerEvidenceResponse, error)
	// SubmitVerifierValueEvidence is registered but returns ERR_NOT_ACTIVATED.
	SubmitVerifierValueEvidence(context.Context, *MsgSubmitVerifierValueEvidence) (*MsgSubmitVerifierValueEvidenceResponse, error)
	// SubmitVerifierHandraises is the single Open Verify entry; it replaces the
	// deleted MsgOpenVerify.
	// SubmitVerifierHandraises executes the SubmitVerifierHandraises operation.
	SubmitVerifierHandraises(context.Context, *MsgSubmitVerifierHandraises) (*MsgSubmitVerifierHandraisesResponse, error)
	// ReportDataUnavailable records one selected Verifier's data-availability report.
	ReportDataUnavailable(context.Context, *MsgReportDataUnavailable) (*MsgReportDataUnavailableResponse, error)
	// SubmitBuilderEvidence accepts one closed typed objective Builder proof.
	// It moved here from hub.v1.Msg: the Task module owns the
	// envelope payload and the Task authority, and it returns the shared receipt
	// directly instead of a module-local Response wrapper.
	// SubmitBuilderEvidence executes the SubmitBuilderEvidence operation.
	SubmitBuilderEvidence(context.Context, *MsgSubmitBuilderEvidence) (*types.BuilderObjectiveEvidenceReceiptV2, error)
	// SubmitVerifyCommit replaces the deleted MsgCommit.
	SubmitVerifyCommit(context.Context, *MsgSubmitVerifyCommit) (*MsgSubmitVerifyCommitResponse, error)
	// BatchSubmitVerifyCommit replaces the deleted MsgBatchCommit.
	BatchSubmitVerifyCommit(context.Context, *MsgBatchSubmitVerifyCommit) (*MsgBatchSubmitVerifyCommitResponse, error)
	// SubmitVerifyResult replaces the deleted MsgResult.
	SubmitVerifyResult(context.Context, *MsgSubmitVerifyResult) (*MsgSubmitVerifyResultResponse, error)
	// BatchSubmitVerifyResult replaces the deleted MsgBatchResult.
	BatchSubmitVerifyResult(context.Context, *MsgBatchSubmitVerifyResult) (*MsgBatchSubmitVerifyResultResponse, error)
	// OpenChallengeRound opens the fixed funded verification round 2.
	OpenChallengeRound(context.Context, *MsgOpenChallengeRound) (*MsgOpenChallengeRoundResponse, error)
	// SettleTask derives and atomically applies the sole Phase 0 settlement plan.
	SettleTask(context.Context, *MsgSettleTask) (*MsgSettleTaskResponse, error)
	// SweepDeadline is the single bounded deadline runner; it replaces the deleted
	// MsgSweepExpiredTask and MsgSessionSweep.
	// SweepDeadline executes the SweepDeadline operation.
	SweepDeadline(context.Context, *MsgSweepDeadline) (*MsgSweepDeadlineResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateTaskParams(ctx context.Context, req *MsgUpdateTaskParams) (*MsgUpdateTaskParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskParams not implemented")
}
func (*UnimplementedMsgServer) CreateSession(ctx context.Context, req *MsgCreateSession) (*MsgCreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (*UnimplementedMsgServer) CancelOrder(ctx context.Context, req *MsgCancelOrder) (*MsgCancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (*UnimplementedMsgServer) SubmitWorkerHandraises(ctx context.Context, req *MsgSubmitWorkerHandraises) (*MsgSubmitWorkerHandraisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWorkerHandraises not implemented")
}
func (*UnimplementedMsgServer) SubmitInferReceipt(ctx context.Context, req *MsgSubmitInferReceipt) (*MsgSubmitInferReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitInferReceipt not implemented")
}
func (*UnimplementedMsgServer) SubmitWorkerEvidence(ctx context.Context, req *MsgSubmitWorkerEvidence) (*MsgSubmitWorkerEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWorkerEvidence not implemented")
}
func (*UnimplementedMsgServer) SubmitVerifierValueEvidence(ctx context.Context, req *MsgSubmitVerifierValueEvidence) (*MsgSubmitVerifierValueEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVerifierValueEvidence not implemented")
}
func (*UnimplementedMsgServer) SubmitVerifierHandraises(ctx context.Context, req *MsgSubmitVerifierHandraises) (*MsgSubmitVerifierHandraisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVerifierHandraises not implemented")
}
func (*UnimplementedMsgServer) ReportDataUnavailable(ctx context.Context, req *MsgReportDataUnavailable) (*MsgReportDataUnavailableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportDataUnavailable not implemented")
}
func (*UnimplementedMsgServer) SubmitBuilderEvidence(ctx context.Context, req *MsgSubmitBuilderEvidence) (*types.BuilderObjectiveEvidenceReceiptV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBuilderEvidence not implemented")
}
func (*UnimplementedMsgServer) SubmitVerifyCommit(ctx context.Context, req *MsgSubmitVerifyCommit) (*MsgSubmitVerifyCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVerifyCommit not implemented")
}
func (*UnimplementedMsgServer) BatchSubmitVerifyCommit(ctx context.Context, req *MsgBatchSubmitVerifyCommit) (*MsgBatchSubmitVerifyCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSubmitVerifyCommit not implemented")
}
func (*UnimplementedMsgServer) SubmitVerifyResult(ctx context.Context, req *MsgSubmitVerifyResult) (*MsgSubmitVerifyResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVerifyResult not implemented")
}
func (*UnimplementedMsgServer) BatchSubmitVerifyResult(ctx context.Context, req *MsgBatchSubmitVerifyResult) (*MsgBatchSubmitVerifyResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSubmitVerifyResult not implemented")
}
func (*UnimplementedMsgServer) OpenChallengeRound(ctx context.Context, req *MsgOpenChallengeRound) (*MsgOpenChallengeRoundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChallengeRound not implemented")
}
func (*UnimplementedMsgServer) SettleTask(ctx context.Context, req *MsgSettleTask) (*MsgSettleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleTask not implemented")
}
func (*UnimplementedMsgServer) SweepDeadline(ctx context.Context, req *MsgSweepDeadline) (*MsgSweepDeadlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SweepDeadline not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateTaskParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateTaskParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateTaskParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/UpdateTaskParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateTaskParams(ctx, req.(*MsgUpdateTaskParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSession(ctx, req.(*MsgCreateSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelOrder(ctx, req.(*MsgCancelOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitWorkerHandraises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitWorkerHandraises)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitWorkerHandraises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitWorkerHandraises",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitWorkerHandraises(ctx, req.(*MsgSubmitWorkerHandraises))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitInferReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitInferReceipt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitInferReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitInferReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitInferReceipt(ctx, req.(*MsgSubmitInferReceipt))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitWorkerEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitWorkerEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitWorkerEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitWorkerEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitWorkerEvidence(ctx, req.(*MsgSubmitWorkerEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitVerifierValueEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitVerifierValueEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitVerifierValueEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitVerifierValueEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitVerifierValueEvidence(ctx, req.(*MsgSubmitVerifierValueEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitVerifierHandraises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitVerifierHandraises)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitVerifierHandraises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitVerifierHandraises",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitVerifierHandraises(ctx, req.(*MsgSubmitVerifierHandraises))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReportDataUnavailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReportDataUnavailable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReportDataUnavailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/ReportDataUnavailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReportDataUnavailable(ctx, req.(*MsgReportDataUnavailable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitBuilderEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitBuilderEvidence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitBuilderEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitBuilderEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitBuilderEvidence(ctx, req.(*MsgSubmitBuilderEvidence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitVerifyCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitVerifyCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitVerifyCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitVerifyCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitVerifyCommit(ctx, req.(*MsgSubmitVerifyCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BatchSubmitVerifyCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBatchSubmitVerifyCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BatchSubmitVerifyCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/BatchSubmitVerifyCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BatchSubmitVerifyCommit(ctx, req.(*MsgBatchSubmitVerifyCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitVerifyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitVerifyResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitVerifyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SubmitVerifyResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitVerifyResult(ctx, req.(*MsgSubmitVerifyResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BatchSubmitVerifyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBatchSubmitVerifyResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BatchSubmitVerifyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/BatchSubmitVerifyResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BatchSubmitVerifyResult(ctx, req.(*MsgBatchSubmitVerifyResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_OpenChallengeRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenChallengeRound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenChallengeRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/OpenChallengeRound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenChallengeRound(ctx, req.(*MsgOpenChallengeRound))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SettleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSettleTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SettleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SettleTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SettleTask(ctx, req.(*MsgSettleTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SweepDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSweepDeadline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SweepDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.Msg/SweepDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SweepDeadline(ctx, req.(*MsgSweepDeadline))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTaskParams",
			Handler:    _Msg_UpdateTaskParams_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Msg_CreateSession_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Msg_CancelOrder_Handler,
		},
		{
			MethodName: "SubmitWorkerHandraises",
			Handler:    _Msg_SubmitWorkerHandraises_Handler,
		},
		{
			MethodName: "SubmitInferReceipt",
			Handler:    _Msg_SubmitInferReceipt_Handler,
		},
		{
			MethodName: "SubmitWorkerEvidence",
			Handler:    _Msg_SubmitWorkerEvidence_Handler,
		},
		{
			MethodName: "SubmitVerifierValueEvidence",
			Handler:    _Msg_SubmitVerifierValueEvidence_Handler,
		},
		{
			MethodName: "SubmitVerifierHandraises",
			Handler:    _Msg_SubmitVerifierHandraises_Handler,
		},
		{
			MethodName: "ReportDataUnavailable",
			Handler:    _Msg_ReportDataUnavailable_Handler,
		},
		{
			MethodName: "SubmitBuilderEvidence",
			Handler:    _Msg_SubmitBuilderEvidence_Handler,
		},
		{
			MethodName: "SubmitVerifyCommit",
			Handler:    _Msg_SubmitVerifyCommit_Handler,
		},
		{
			MethodName: "BatchSubmitVerifyCommit",
			Handler:    _Msg_BatchSubmitVerifyCommit_Handler,
		},
		{
			MethodName: "SubmitVerifyResult",
			Handler:    _Msg_SubmitVerifyResult_Handler,
		},
		{
			MethodName: "BatchSubmitVerifyResult",
			Handler:    _Msg_BatchSubmitVerifyResult_Handler,
		},
		{
			MethodName: "OpenChallengeRound",
			Handler:    _Msg_OpenChallengeRound_Handler,
		},
		{
			MethodName: "SettleTask",
			Handler:    _Msg_SettleTask_Handler,
		},
		{
			MethodName: "SweepDeadline",
			Handler:    _Msg_SweepDeadline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task/v1/tx.proto",
}
