// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shared/v1/payload.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProfilePriceSampleV1 is the sole typed Task-to-Hub input to the transient
// Profile reference-price sampler. Direction and counters are Hub-derived.
// ProfilePriceSampleV1 defines the ProfilePriceSampleV1 wire type.
type ProfilePriceSampleV1 struct {
	TaskId         []byte `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ModelId        []byte `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProfileVersion uint32 `protobuf:"varint,3,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	PriceBid       uint64 `protobuf:"varint,4,opt,name=price_bid,json=priceBid,proto3" json:"price_bid,omitempty"`
}

func (m *ProfilePriceSampleV1) Reset()         { *m = ProfilePriceSampleV1{} }
func (m *ProfilePriceSampleV1) String() string { return proto.CompactTextString(m) }
func (*ProfilePriceSampleV1) ProtoMessage()    {}
func (*ProfilePriceSampleV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd8aa1127fbf1b85, []int{0}
}
func (m *ProfilePriceSampleV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfilePriceSampleV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfilePriceSampleV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfilePriceSampleV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePriceSampleV1.Merge(m, src)
}
func (m *ProfilePriceSampleV1) XXX_Size() int {
	return m.Size()
}
func (m *ProfilePriceSampleV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePriceSampleV1.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePriceSampleV1 proto.InternalMessageInfo

func (m *ProfilePriceSampleV1) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *ProfilePriceSampleV1) GetModelId() []byte {
	if m != nil {
		return m.ModelId
	}
	return nil
}

func (m *ProfilePriceSampleV1) GetProfileVersion() uint32 {
	if m != nil {
		return m.ProfileVersion
	}
	return 0
}

func (m *ProfilePriceSampleV1) GetPriceBid() uint64 {
	if m != nil {
		return m.PriceBid
	}
	return 0
}

// EpochTaskSummary is the bounded U1 summary emitted by Task at epoch close.
// It is the only legacy cross-module payload still consumed by the Phase 0
// contract. Round economics and settlement are Task-owned and use their typed
// state, plans and receipts instead of cross-module optimistic-settlement
// payloads.
// EpochTaskSummary defines the EpochTaskSummary wire type.
type EpochTaskSummary struct {
	Epoch          uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	TaskCount      uint64   `protobuf:"varint,2,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	ValidTaskCount uint64   `protobuf:"varint,3,opt,name=valid_task_count,json=validTaskCount,proto3" json:"valid_task_count,omitempty"`
	Histogram      []uint64 `protobuf:"varint,4,rep,packed,name=histogram,proto3" json:"histogram,omitempty"`
	// Raw Hash32 model identifiers in strictly ascending byte order.
	// Every model appears at most once; composite model/profile strings are invalid.
	SupportCandidates [][]byte `protobuf:"bytes,5,rep,name=support_candidates,json=supportCandidates,proto3" json:"support_candidates,omitempty"`
}

func (m *EpochTaskSummary) Reset()         { *m = EpochTaskSummary{} }
func (m *EpochTaskSummary) String() string { return proto.CompactTextString(m) }
func (*EpochTaskSummary) ProtoMessage()    {}
func (*EpochTaskSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd8aa1127fbf1b85, []int{1}
}
func (m *EpochTaskSummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochTaskSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochTaskSummary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochTaskSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochTaskSummary.Merge(m, src)
}
func (m *EpochTaskSummary) XXX_Size() int {
	return m.Size()
}
func (m *EpochTaskSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochTaskSummary.DiscardUnknown(m)
}

var xxx_messageInfo_EpochTaskSummary proto.InternalMessageInfo

func (m *EpochTaskSummary) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochTaskSummary) GetTaskCount() uint64 {
	if m != nil {
		return m.TaskCount
	}
	return 0
}

func (m *EpochTaskSummary) GetValidTaskCount() uint64 {
	if m != nil {
		return m.ValidTaskCount
	}
	return 0
}

func (m *EpochTaskSummary) GetHistogram() []uint64 {
	if m != nil {
		return m.Histogram
	}
	return nil
}

func (m *EpochTaskSummary) GetSupportCandidates() [][]byte {
	if m != nil {
		return m.SupportCandidates
	}
	return nil
}

func init() {
	proto.RegisterType((*ProfilePriceSampleV1)(nil), "shared.v1.ProfilePriceSampleV1")
	proto.RegisterType((*EpochTaskSummary)(nil), "shared.v1.EpochTaskSummary")
}

func init() { proto.RegisterFile("shared/v1/payload.proto", fileDescriptor_bd8aa1127fbf1b85) }

var fileDescriptor_bd8aa1127fbf1b85 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xb1, 0xae, 0xda, 0x30,
	0x14, 0x86, 0xf1, 0x4d, 0xee, 0xbd, 0xc4, 0x6a, 0x29, 0xb5, 0x90, 0x1a, 0xb5, 0x25, 0x8d, 0x58,
	0xc8, 0x44, 0x84, 0x78, 0x82, 0x82, 0x3a, 0x30, 0x15, 0x05, 0xc4, 0xd0, 0x25, 0x32, 0xb1, 0x4b,
	0x2c, 0x92, 0xd8, 0xb2, 0x9d, 0xa8, 0xbc, 0x45, 0x1f, 0xa0, 0x8f, 0xd3, 0x81, 0x91, 0xb1, 0x63,
	0x05, 0x8f, 0xd0, 0x17, 0xa8, 0xe2, 0xa0, 0x5c, 0x46, 0x7f, 0xff, 0xa7, 0xe3, 0x5f, 0xe7, 0xc0,
	0x77, 0x2a, 0xc5, 0x92, 0x92, 0xb0, 0x9a, 0x86, 0x02, 0x1f, 0x33, 0x8e, 0xc9, 0x44, 0x48, 0xae,
	0x39, 0x72, 0x9a, 0x60, 0x52, 0x4d, 0xdf, 0x0f, 0x5f, 0x1c, 0x49, 0x95, 0x8e, 0x69, 0x91, 0x70,
	0xc2, 0x8a, 0x7d, 0x63, 0x8e, 0x7e, 0x01, 0x38, 0x58, 0x49, 0xfe, 0x9d, 0x65, 0x74, 0x25, 0x59,
	0x42, 0xd7, 0x38, 0x17, 0x19, 0xdd, 0x4e, 0xd1, 0x10, 0x3e, 0x6b, 0xac, 0x0e, 0x31, 0x23, 0x2e,
	0xf0, 0x41, 0xf0, 0x6a, 0x6e, 0x9f, 0xfe, 0xb9, 0x0f, 0xd1, 0x53, 0x0d, 0x97, 0x04, 0x7d, 0x82,
	0xdd, 0x9c, 0x13, 0x9a, 0xd5, 0xf9, 0xc3, 0x5d, 0xfe, 0x6c, 0xe8, 0x92, 0xa0, 0x31, 0x7c, 0x23,
	0x9a, 0xb9, 0x71, 0x45, 0xa5, 0x62, 0xbc, 0x70, 0x2d, 0x1f, 0x04, 0xaf, 0xa3, 0xde, 0x0d, 0x6f,
	0x1b, 0x8a, 0x3e, 0x40, 0x47, 0xd4, 0x3f, 0xc7, 0x3b, 0x46, 0x5c, 0xdb, 0x07, 0x81, 0x1d, 0x75,
	0x0d, 0x98, 0x33, 0x32, 0xfa, 0x0d, 0x60, 0xff, 0x8b, 0xe0, 0x49, 0xba, 0xc1, 0xea, 0xb0, 0x2e,
	0xf3, 0x1c, 0xcb, 0x23, 0x1a, 0xc0, 0x47, 0x5a, 0x33, 0x53, 0xcc, 0x8e, 0x9a, 0x07, 0x1a, 0x42,
	0x68, 0x0a, 0x27, 0xbc, 0x2c, 0xb4, 0xe9, 0x64, 0x47, 0x4e, 0x4d, 0x16, 0x35, 0x40, 0x01, 0xec,
	0x57, 0x38, 0x63, 0x24, 0xbe, 0x93, 0x2c, 0x23, 0xf5, 0x0c, 0xdf, 0xb4, 0xe6, 0x47, 0xe8, 0xa4,
	0x4c, 0x69, 0xbe, 0x97, 0x38, 0x77, 0x6d, 0xdf, 0xaa, 0xe7, 0xb4, 0x00, 0xcd, 0x20, 0x52, 0xa5,
	0x10, 0x5c, 0xea, 0x38, 0xc1, 0x05, 0x61, 0x04, 0x6b, 0xaa, 0xdc, 0x47, 0xdf, 0x6a, 0x57, 0xf0,
	0xf6, 0x96, 0x2f, 0xda, 0x78, 0xfe, 0xf9, 0x74, 0xf1, 0xc0, 0xf9, 0xe2, 0x81, 0xbf, 0x17, 0x0f,
	0xfc, 0xbc, 0x7a, 0x9d, 0xf3, 0xd5, 0xeb, 0xfc, 0xb9, 0x7a, 0x9d, 0x6f, 0xe3, 0x3d, 0xd3, 0x69,
	0xb9, 0x9b, 0x24, 0x3c, 0x0f, 0x37, 0xb2, 0xa4, 0x5f, 0x05, 0x2d, 0xc2, 0x82, 0x13, 0x1a, 0xfe,
	0x08, 0x6f, 0x97, 0xd3, 0x47, 0x41, 0xd5, 0xee, 0xc9, 0xdc, 0x6b, 0xf6, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x32, 0x91, 0x48, 0xf4, 0x01, 0x00, 0x00,
}

func (m *ProfilePriceSampleV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfilePriceSampleV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfilePriceSampleV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PriceBid != 0 {
		i = encodeVarintPayload(dAtA, i, uint64(m.PriceBid))
		i--
		dAtA[i] = 0x20
	}
	if m.ProfileVersion != 0 {
		i = encodeVarintPayload(dAtA, i, uint64(m.ProfileVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintPayload(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintPayload(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochTaskSummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochTaskSummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochTaskSummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SupportCandidates) > 0 {
		for iNdEx := len(m.SupportCandidates) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SupportCandidates[iNdEx])
			copy(dAtA[i:], m.SupportCandidates[iNdEx])
			i = encodeVarintPayload(dAtA, i, uint64(len(m.SupportCandidates[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Histogram) > 0 {
		dAtA2 := make([]byte, len(m.Histogram)*10)
		var j1 int
		for _, num := range m.Histogram {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintPayload(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if m.ValidTaskCount != 0 {
		i = encodeVarintPayload(dAtA, i, uint64(m.ValidTaskCount))
		i--
		dAtA[i] = 0x18
	}
	if m.TaskCount != 0 {
		i = encodeVarintPayload(dAtA, i, uint64(m.TaskCount))
		i--
		dAtA[i] = 0x10
	}
	if m.Epoch != 0 {
		i = encodeVarintPayload(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPayload(dAtA []byte, offset int, v uint64) int {
	offset -= sovPayload(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProfilePriceSampleV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovPayload(uint64(l))
	}
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovPayload(uint64(l))
	}
	if m.ProfileVersion != 0 {
		n += 1 + sovPayload(uint64(m.ProfileVersion))
	}
	if m.PriceBid != 0 {
		n += 1 + sovPayload(uint64(m.PriceBid))
	}
	return n
}

func (m *EpochTaskSummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovPayload(uint64(m.Epoch))
	}
	if m.TaskCount != 0 {
		n += 1 + sovPayload(uint64(m.TaskCount))
	}
	if m.ValidTaskCount != 0 {
		n += 1 + sovPayload(uint64(m.ValidTaskCount))
	}
	if len(m.Histogram) > 0 {
		l = 0
		for _, e := range m.Histogram {
			l += sovPayload(uint64(e))
		}
		n += 1 + sovPayload(uint64(l)) + l
	}
	if len(m.SupportCandidates) > 0 {
		for _, b := range m.SupportCandidates {
			l = len(b)
			n += 1 + l + sovPayload(uint64(l))
		}
	}
	return n
}

func sovPayload(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPayload(x uint64) (n int) {
	return sovPayload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProfilePriceSampleV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfilePriceSampleV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfilePriceSampleV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPayload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPayload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = append(m.ModelId[:0], dAtA[iNdEx:postIndex]...)
			if m.ModelId == nil {
				m.ModelId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfileVersion", wireType)
			}
			m.ProfileVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProfileVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceBid", wireType)
			}
			m.PriceBid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceBid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochTaskSummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochTaskSummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochTaskSummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskCount", wireType)
			}
			m.TaskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidTaskCount", wireType)
			}
			m.ValidTaskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidTaskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPayload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Histogram = append(m.Histogram, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPayload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPayload
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPayload
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Histogram) == 0 {
					m.Histogram = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Histogram = append(m.Histogram, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Histogram", wireType)
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportCandidates", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPayload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportCandidates = append(m.SupportCandidates, make([]byte, postIndex-iNdEx))
			copy(m.SupportCandidates[len(m.SupportCandidates)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPayload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPayload
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPayload
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPayload
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPayload        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayload          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPayload = fmt.Errorf("proto: unexpected end of group")
)
