// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/v1/common.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ServiceKeyStatus is the lifecycle of one current Cortex service key binding (9.6b).
type ServiceKeyStatus int32

const (
	// Never written; rejects zero-value bindings.
	// SERVICE_KEY_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	ServiceKeyStatus_SERVICE_KEY_STATUS_UNSPECIFIED ServiceKeyStatus = 0
	// Binding may authorize service submissions.
	// SERVICE_KEY_STATUS_ACTIVE identifies the corresponding protocol value.
	ServiceKeyStatus_SERVICE_KEY_STATUS_ACTIVE ServiceKeyStatus = 1
	// Binding is revoked and authorizes nothing.
	// SERVICE_KEY_STATUS_REVOKED identifies the corresponding protocol value.
	ServiceKeyStatus_SERVICE_KEY_STATUS_REVOKED ServiceKeyStatus = 2
)

var ServiceKeyStatus_name = map[int32]string{
	0: "SERVICE_KEY_STATUS_UNSPECIFIED",
	1: "SERVICE_KEY_STATUS_ACTIVE",
	2: "SERVICE_KEY_STATUS_REVOKED",
}

var ServiceKeyStatus_value = map[string]int32{
	"SERVICE_KEY_STATUS_UNSPECIFIED": 0,
	"SERVICE_KEY_STATUS_ACTIVE":      1,
	"SERVICE_KEY_STATUS_REVOKED":     2,
}

func (x ServiceKeyStatus) String() string {
	return proto.EnumName(ServiceKeyStatus_name, int32(x))
}

func (ServiceKeyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{0}
}

// ServiceKeyRevocationReason is the closed reason set of MsgRevokeServiceKey (9.6b).
type ServiceKeyRevocationReason int32

const (
	// Never written.
	// SERVICE_KEY_REVOCATION_REASON_UNSPECIFIED identifies the corresponding protocol value.
	ServiceKeyRevocationReason_SERVICE_KEY_REVOCATION_REASON_UNSPECIFIED ServiceKeyRevocationReason = 0
	// Key material is believed compromised.
	// SERVICE_KEY_REVOCATION_REASON_COMPROMISED identifies the corresponding protocol value.
	ServiceKeyRevocationReason_SERVICE_KEY_REVOCATION_REASON_COMPROMISED ServiceKeyRevocationReason = 1
	// Operator is shutting the service down.
	// SERVICE_KEY_REVOCATION_REASON_OPERATOR_SHUTDOWN identifies the corresponding protocol value.
	ServiceKeyRevocationReason_SERVICE_KEY_REVOCATION_REASON_OPERATOR_SHUTDOWN ServiceKeyRevocationReason = 2
	// Revoked by a governance emergency action.
	// SERVICE_KEY_REVOCATION_REASON_GOVERNANCE_EMERGENCY identifies the corresponding protocol value.
	ServiceKeyRevocationReason_SERVICE_KEY_REVOCATION_REASON_GOVERNANCE_EMERGENCY ServiceKeyRevocationReason = 3
)

var ServiceKeyRevocationReason_name = map[int32]string{
	0: "SERVICE_KEY_REVOCATION_REASON_UNSPECIFIED",
	1: "SERVICE_KEY_REVOCATION_REASON_COMPROMISED",
	2: "SERVICE_KEY_REVOCATION_REASON_OPERATOR_SHUTDOWN",
	3: "SERVICE_KEY_REVOCATION_REASON_GOVERNANCE_EMERGENCY",
}

var ServiceKeyRevocationReason_value = map[string]int32{
	"SERVICE_KEY_REVOCATION_REASON_UNSPECIFIED":          0,
	"SERVICE_KEY_REVOCATION_REASON_COMPROMISED":          1,
	"SERVICE_KEY_REVOCATION_REASON_OPERATOR_SHUTDOWN":    2,
	"SERVICE_KEY_REVOCATION_REASON_GOVERNANCE_EMERGENCY": 3,
}

func (x ServiceKeyRevocationReason) String() string {
	return proto.EnumName(ServiceKeyRevocationReason_name, int32(x))
}

func (ServiceKeyRevocationReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{1}
}

// ServiceKeyResponsibilityKind is the closed set of online responsibilities that
// block MsgRotateServiceKey. The builder
// stage kinds feed BuilderState/CortexNodeState.pending_stage_duty_count and the
// challenge/evidence kinds feed pending_evidence_submission_count; task duty
// liability is counted by active_task_liability_count and no longer stored as a
// responsibility row.
//
// Value 4 was reassigned in the fresh Phase 0 schema. The removed evidence
// request protocol has no compatibility alias or writer.
// ServiceKeyResponsibilityKind defines the ServiceKeyResponsibilityKind wire type.
type ServiceKeyResponsibilityKind int32

const (
	// Never written; rejects zero-value rows.
	// SERVICE_KEY_RESPONSIBILITY_KIND_UNSPECIFIED identifies the corresponding protocol value.
	ServiceKeyResponsibilityKind_SERVICE_KEY_RESPONSIBILITY_KIND_UNSPECIFIED ServiceKeyResponsibilityKind = 0
	// Selected builder owes an Open Verify stage submission for one task.
	// SERVICE_KEY_RESPONSIBILITY_KIND_OPEN_VERIFY_BUILDER identifies the corresponding protocol value.
	ServiceKeyResponsibilityKind_SERVICE_KEY_RESPONSIBILITY_KIND_OPEN_VERIFY_BUILDER ServiceKeyResponsibilityKind = 1
	// Selected builder owes a settlement stage submission for one task.
	// SERVICE_KEY_RESPONSIBILITY_KIND_SETTLE_BUILDER identifies the corresponding protocol value.
	ServiceKeyResponsibilityKind_SERVICE_KEY_RESPONSIBILITY_KIND_SETTLE_BUILDER ServiceKeyResponsibilityKind = 2
	// Cortex node is assigned as verifier on an open challenge round.
	// SERVICE_KEY_RESPONSIBILITY_KIND_CHALLENGE_VERIFIER identifies the corresponding protocol value.
	ServiceKeyResponsibilityKind_SERVICE_KEY_RESPONSIBILITY_KIND_CHALLENGE_VERIFIER ServiceKeyResponsibilityKind = 3
	// The selected Worker key remains provable through the output-evidence window.
	// SERVICE_KEY_RESPONSIBILITY_KIND_WORKER_OUTPUT_EVIDENCE identifies the corresponding protocol value.
	ServiceKeyResponsibilityKind_SERVICE_KEY_RESPONSIBILITY_KIND_WORKER_OUTPUT_EVIDENCE ServiceKeyResponsibilityKind = 4
	// Locked Task Builder is still exposed to objective BusEnvelope evidence for
	// one task, so its service key must stay verifiable.
	//
	// Lifecycle, all inside one cache transaction
	// with the participant counter and the ByTask index:
	//   create  - when the first Task proposal is accepted and the Task Builders
	//             are locked, exactly one row per Builder is created for that
	//             Builder's current (operator, authorization_nonce) and
	//             pending_evidence_submission_count is checked +1. An exact replay
	//             of the accepted proposal creates nothing a second time.
	//   keep    - ReleaseTaskTerminalRefsOnce on the terminal transition deletes
	//             every other ServiceKeyResponsibilityState row of the task but
	//             must preserve this one; the terminal transition may not
	//             decrement the counter early.
	//   release - only the EvidenceCleanupIndex sweep, once it reaches
	//             task_finality_height + max_evidence_retention_blocks and the
	//             evidence bodies are pruned, deletes the row/index and does the
	//             checked -1. It is the only first-time decrement of this kind.
	// Therefore MsgRotateServiceKey stays blocked for the whole objective-evidence
	// admissibility window: an operator cannot clear the counter first and rotate
	// the accusable key away afterwards.
	// SERVICE_KEY_RESPONSIBILITY_KIND_BUS_OBJECTIVE_EVIDENCE identifies the corresponding protocol value.
	ServiceKeyResponsibilityKind_SERVICE_KEY_RESPONSIBILITY_KIND_BUS_OBJECTIVE_EVIDENCE ServiceKeyResponsibilityKind = 5
)

var ServiceKeyResponsibilityKind_name = map[int32]string{
	0: "SERVICE_KEY_RESPONSIBILITY_KIND_UNSPECIFIED",
	1: "SERVICE_KEY_RESPONSIBILITY_KIND_OPEN_VERIFY_BUILDER",
	2: "SERVICE_KEY_RESPONSIBILITY_KIND_SETTLE_BUILDER",
	3: "SERVICE_KEY_RESPONSIBILITY_KIND_CHALLENGE_VERIFIER",
	4: "SERVICE_KEY_RESPONSIBILITY_KIND_WORKER_OUTPUT_EVIDENCE",
	5: "SERVICE_KEY_RESPONSIBILITY_KIND_BUS_OBJECTIVE_EVIDENCE",
}

var ServiceKeyResponsibilityKind_value = map[string]int32{
	"SERVICE_KEY_RESPONSIBILITY_KIND_UNSPECIFIED":            0,
	"SERVICE_KEY_RESPONSIBILITY_KIND_OPEN_VERIFY_BUILDER":    1,
	"SERVICE_KEY_RESPONSIBILITY_KIND_SETTLE_BUILDER":         2,
	"SERVICE_KEY_RESPONSIBILITY_KIND_CHALLENGE_VERIFIER":     3,
	"SERVICE_KEY_RESPONSIBILITY_KIND_WORKER_OUTPUT_EVIDENCE": 4,
	"SERVICE_KEY_RESPONSIBILITY_KIND_BUS_OBJECTIVE_EVIDENCE": 5,
}

func (x ServiceKeyResponsibilityKind) String() string {
	return proto.EnumName(ServiceKeyResponsibilityKind_name, int32(x))
}

func (ServiceKeyResponsibilityKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{2}
}

// GovernanceReason is the closed reason set of a governance model or profile status transition (9.6b).
type GovernanceReason int32

const (
	// Never written.
	// GOVERNANCE_REASON_UNSPECIFIED identifies the corresponding protocol value.
	GovernanceReason_GOVERNANCE_REASON_UNSPECIFIED GovernanceReason = 0
	// Freeze the model or profile.
	// GOVERNANCE_REASON_FREEZE identifies the corresponding protocol value.
	GovernanceReason_GOVERNANCE_REASON_FREEZE GovernanceReason = 1
	// Unfreeze back to REGISTERED.
	// GOVERNANCE_REASON_UNFREEZE identifies the corresponding protocol value.
	GovernanceReason_GOVERNANCE_REASON_UNFREEZE GovernanceReason = 2
	// Terminal delisting.
	// GOVERNANCE_REASON_DELIST identifies the corresponding protocol value.
	GovernanceReason_GOVERNANCE_REASON_DELIST GovernanceReason = 3
	// Recovery action after an emergency freeze.
	// GOVERNANCE_REASON_EMERGENCY_RECOVERY identifies the corresponding protocol value.
	GovernanceReason_GOVERNANCE_REASON_EMERGENCY_RECOVERY GovernanceReason = 4
)

var GovernanceReason_name = map[int32]string{
	0: "GOVERNANCE_REASON_UNSPECIFIED",
	1: "GOVERNANCE_REASON_FREEZE",
	2: "GOVERNANCE_REASON_UNFREEZE",
	3: "GOVERNANCE_REASON_DELIST",
	4: "GOVERNANCE_REASON_EMERGENCY_RECOVERY",
}

var GovernanceReason_value = map[string]int32{
	"GOVERNANCE_REASON_UNSPECIFIED":        0,
	"GOVERNANCE_REASON_FREEZE":             1,
	"GOVERNANCE_REASON_UNFREEZE":           2,
	"GOVERNANCE_REASON_DELIST":             3,
	"GOVERNANCE_REASON_EMERGENCY_RECOVERY": 4,
}

func (x GovernanceReason) String() string {
	return proto.EnumName(GovernanceReason_name, int32(x))
}

func (GovernanceReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{3}
}

// ServiceBondStatus is the operator-global service bond lifecycle.
type ServiceBondStatus int32

const (
	// Never written; rejects zero-value rows.
	// SERVICE_BOND_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_UNSPECIFIED ServiceBondStatus = 0
	// Bond row created but not yet effective.
	// SERVICE_BOND_STATUS_REGISTERED identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_REGISTERED ServiceBondStatus = 1
	// Bond is effective and may back duties.
	// SERVICE_BOND_STATUS_ACTIVE identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_ACTIVE ServiceBondStatus = 2
	// Operator is jailed; no new duty is assigned.
	// SERVICE_BOND_STATUS_JAILED identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_JAILED ServiceBondStatus = 3
	// Operator is unbonding to zero.
	// SERVICE_BOND_STATUS_UNBONDING identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_UNBONDING ServiceBondStatus = 4
	// Bond reached zero with no outstanding liability.
	// SERVICE_BOND_STATUS_EXITED identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_EXITED ServiceBondStatus = 5
	// Permanently excluded.
	// SERVICE_BOND_STATUS_TOMBSTONED identifies the corresponding protocol value.
	ServiceBondStatus_SERVICE_BOND_STATUS_TOMBSTONED ServiceBondStatus = 6
)

var ServiceBondStatus_name = map[int32]string{
	0: "SERVICE_BOND_STATUS_UNSPECIFIED",
	1: "SERVICE_BOND_STATUS_REGISTERED",
	2: "SERVICE_BOND_STATUS_ACTIVE",
	3: "SERVICE_BOND_STATUS_JAILED",
	4: "SERVICE_BOND_STATUS_UNBONDING",
	5: "SERVICE_BOND_STATUS_EXITED",
	6: "SERVICE_BOND_STATUS_TOMBSTONED",
}

var ServiceBondStatus_value = map[string]int32{
	"SERVICE_BOND_STATUS_UNSPECIFIED": 0,
	"SERVICE_BOND_STATUS_REGISTERED":  1,
	"SERVICE_BOND_STATUS_ACTIVE":      2,
	"SERVICE_BOND_STATUS_JAILED":      3,
	"SERVICE_BOND_STATUS_UNBONDING":   4,
	"SERVICE_BOND_STATUS_EXITED":      5,
	"SERVICE_BOND_STATUS_TOMBSTONED":  6,
}

func (x ServiceBondStatus) String() string {
	return proto.EnumName(ServiceBondStatus_name, int32(x))
}

func (ServiceBondStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{4}
}

// UnbondingStatus is the lifecycle of one service unbonding row. The numeric
// values are frozen, which is the sole authority for
// closed enum values; this contract QueryServiceUnbondings filters on this exact set.
// UnbondingStatus defines the UnbondingStatus wire type.
type UnbondingStatus int32

const (
	// Never written; rejects zero-value rows.
	// UNBONDING_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	UnbondingStatus_UNBONDING_STATUS_UNSPECIFIED UnbondingStatus = 0
	// Created by MsgBeginServiceUnstake and still before mature_height.
	// UNBONDING_STATUS_OPEN identifies the corresponding protocol value.
	UnbondingStatus_UNBONDING_STATUS_OPEN UnbondingStatus = 1
	// mature_height reached; withdrawable via MsgWithdrawServiceUnbonded.
	// UNBONDING_STATUS_MATURE identifies the corresponding protocol value.
	UnbondingStatus_UNBONDING_STATUS_MATURE UnbondingStatus = 2
	// Fully withdrawn to the operator; row is replaced by UnbondingReceiptState.
	// UNBONDING_STATUS_WITHDRAWN identifies the corresponding protocol value.
	UnbondingStatus_UNBONDING_STATUS_WITHDRAWN UnbondingStatus = 3
	// Fully consumed by ApplyServiceSlash; row is replaced by a receipt.
	// UNBONDING_STATUS_SLASHED identifies the corresponding protocol value.
	UnbondingStatus_UNBONDING_STATUS_SLASHED UnbondingStatus = 4
)

var UnbondingStatus_name = map[int32]string{
	0: "UNBONDING_STATUS_UNSPECIFIED",
	1: "UNBONDING_STATUS_OPEN",
	2: "UNBONDING_STATUS_MATURE",
	3: "UNBONDING_STATUS_WITHDRAWN",
	4: "UNBONDING_STATUS_SLASHED",
}

var UnbondingStatus_value = map[string]int32{
	"UNBONDING_STATUS_UNSPECIFIED": 0,
	"UNBONDING_STATUS_OPEN":        1,
	"UNBONDING_STATUS_MATURE":      2,
	"UNBONDING_STATUS_WITHDRAWN":   3,
	"UNBONDING_STATUS_SLASHED":     4,
}

func (x UnbondingStatus) String() string {
	return proto.EnumName(UnbondingStatus_name, int32(x))
}

func (UnbondingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{5}
}

// UnbondingReceiptTerminalStatus is the terminal outcome recorded on an unbonding receipt (6.4).
type UnbondingReceiptTerminalStatus int32

const (
	// Never written.
	// UNBONDING_RECEIPT_TERMINAL_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	UnbondingReceiptTerminalStatus_UNBONDING_RECEIPT_TERMINAL_STATUS_UNSPECIFIED UnbondingReceiptTerminalStatus = 0
	// Entry was fully withdrawn to the operator.
	// UNBONDING_RECEIPT_TERMINAL_STATUS_WITHDRAWN identifies the corresponding protocol value.
	UnbondingReceiptTerminalStatus_UNBONDING_RECEIPT_TERMINAL_STATUS_WITHDRAWN UnbondingReceiptTerminalStatus = 1
	// Entry was fully consumed by a slash.
	// UNBONDING_RECEIPT_TERMINAL_STATUS_FULLY_SLASHED identifies the corresponding protocol value.
	UnbondingReceiptTerminalStatus_UNBONDING_RECEIPT_TERMINAL_STATUS_FULLY_SLASHED UnbondingReceiptTerminalStatus = 2
)

var UnbondingReceiptTerminalStatus_name = map[int32]string{
	0: "UNBONDING_RECEIPT_TERMINAL_STATUS_UNSPECIFIED",
	1: "UNBONDING_RECEIPT_TERMINAL_STATUS_WITHDRAWN",
	2: "UNBONDING_RECEIPT_TERMINAL_STATUS_FULLY_SLASHED",
}

var UnbondingReceiptTerminalStatus_value = map[string]int32{
	"UNBONDING_RECEIPT_TERMINAL_STATUS_UNSPECIFIED":   0,
	"UNBONDING_RECEIPT_TERMINAL_STATUS_WITHDRAWN":     1,
	"UNBONDING_RECEIPT_TERMINAL_STATUS_FULLY_SLASHED": 2,
}

func (x UnbondingReceiptTerminalStatus) String() string {
	return proto.EnumName(UnbondingReceiptTerminalStatus_name, int32(x))
}

func (UnbondingReceiptTerminalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{6}
}

// LiabilityStatus is the lifecycle of one per-task bond reservation (6.4).
type LiabilityStatus int32

const (
	// Never written; rejects zero-value rows.
	// LIABILITY_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	LiabilityStatus_LIABILITY_STATUS_UNSPECIFIED LiabilityStatus = 0
	// Reservation is held against the active bond.
	// LIABILITY_STATUS_RESERVED identifies the corresponding protocol value.
	LiabilityStatus_LIABILITY_STATUS_RESERVED LiabilityStatus = 1
	// Duty ended without fault; reservation released.
	// LIABILITY_STATUS_RELEASED identifies the corresponding protocol value.
	LiabilityStatus_LIABILITY_STATUS_RELEASED LiabilityStatus = 2
	// Reservation was consumed by a slash.
	// LIABILITY_STATUS_SLASHED identifies the corresponding protocol value.
	LiabilityStatus_LIABILITY_STATUS_SLASHED LiabilityStatus = 3
)

var LiabilityStatus_name = map[int32]string{
	0: "LIABILITY_STATUS_UNSPECIFIED",
	1: "LIABILITY_STATUS_RESERVED",
	2: "LIABILITY_STATUS_RELEASED",
	3: "LIABILITY_STATUS_SLASHED",
}

var LiabilityStatus_value = map[string]int32{
	"LIABILITY_STATUS_UNSPECIFIED": 0,
	"LIABILITY_STATUS_RESERVED":    1,
	"LIABILITY_STATUS_RELEASED":    2,
	"LIABILITY_STATUS_SLASHED":     3,
}

func (x LiabilityStatus) String() string {
	return proto.EnumName(LiabilityStatus_name, int32(x))
}

func (LiabilityStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{7}
}

// ModelSupportActivationKind records which task fact first activated one support row (6.1).
type ModelSupportActivationKind int32

const (
	// Never written.
	// MODEL_SUPPORT_ACTIVATION_KIND_UNSPECIFIED identifies the corresponding protocol value.
	ModelSupportActivationKind_MODEL_SUPPORT_ACTIVATION_KIND_UNSPECIFIED ModelSupportActivationKind = 0
	// Support row has not been activated by any task fact.
	// MODEL_SUPPORT_ACTIVATION_KIND_NONE identifies the corresponding protocol value.
	ModelSupportActivationKind_MODEL_SUPPORT_ACTIVATION_KIND_NONE ModelSupportActivationKind = 1
	// Activated by a worker task at or above the P30 order value cutoff.
	// MODEL_SUPPORT_ACTIVATION_KIND_WORKER_P30_ORDER_VALUE identifies the corresponding protocol value.
	ModelSupportActivationKind_MODEL_SUPPORT_ACTIVATION_KIND_WORKER_P30_ORDER_VALUE ModelSupportActivationKind = 2
	// Activated by an assigned verifier duty on a valid task.
	// MODEL_SUPPORT_ACTIVATION_KIND_VERIFIER_ASSIGNED_VALID identifies the corresponding protocol value.
	ModelSupportActivationKind_MODEL_SUPPORT_ACTIVATION_KIND_VERIFIER_ASSIGNED_VALID ModelSupportActivationKind = 3
)

var ModelSupportActivationKind_name = map[int32]string{
	0: "MODEL_SUPPORT_ACTIVATION_KIND_UNSPECIFIED",
	1: "MODEL_SUPPORT_ACTIVATION_KIND_NONE",
	2: "MODEL_SUPPORT_ACTIVATION_KIND_WORKER_P30_ORDER_VALUE",
	3: "MODEL_SUPPORT_ACTIVATION_KIND_VERIFIER_ASSIGNED_VALID",
}

var ModelSupportActivationKind_value = map[string]int32{
	"MODEL_SUPPORT_ACTIVATION_KIND_UNSPECIFIED":             0,
	"MODEL_SUPPORT_ACTIVATION_KIND_NONE":                    1,
	"MODEL_SUPPORT_ACTIVATION_KIND_WORKER_P30_ORDER_VALUE":  2,
	"MODEL_SUPPORT_ACTIVATION_KIND_VERIFIER_ASSIGNED_VALID": 3,
}

func (x ModelSupportActivationKind) String() string {
	return proto.EnumName(ModelSupportActivationKind_name, int32(x))
}

func (ModelSupportActivationKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{8}
}

// ModelSupportStatus is the single roleless support row lifecycle (9.6b).
type ModelSupportStatus int32

const (
	// Never written; rejects zero-value rows.
	// MODEL_SUPPORT_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	ModelSupportStatus_MODEL_SUPPORT_STATUS_UNSPECIFIED ModelSupportStatus = 0
	// Declared but not yet activated by a task fact.
	// MODEL_SUPPORT_STATUS_DECLARED identifies the corresponding protocol value.
	ModelSupportStatus_MODEL_SUPPORT_STATUS_DECLARED ModelSupportStatus = 1
	// Active and fresh.
	// MODEL_SUPPORT_STATUS_ACTIVE identifies the corresponding protocol value.
	ModelSupportStatus_MODEL_SUPPORT_STATUS_ACTIVE ModelSupportStatus = 2
	// Freshness window elapsed without a heartbeat.
	// MODEL_SUPPORT_STATUS_STALE identifies the corresponding protocol value.
	ModelSupportStatus_MODEL_SUPPORT_STATUS_STALE ModelSupportStatus = 3
	// Deactivated; the operator no longer supports the profile.
	// MODEL_SUPPORT_STATUS_INACTIVE identifies the corresponding protocol value.
	ModelSupportStatus_MODEL_SUPPORT_STATUS_INACTIVE ModelSupportStatus = 4
)

var ModelSupportStatus_name = map[int32]string{
	0: "MODEL_SUPPORT_STATUS_UNSPECIFIED",
	1: "MODEL_SUPPORT_STATUS_DECLARED",
	2: "MODEL_SUPPORT_STATUS_ACTIVE",
	3: "MODEL_SUPPORT_STATUS_STALE",
	4: "MODEL_SUPPORT_STATUS_INACTIVE",
}

var ModelSupportStatus_value = map[string]int32{
	"MODEL_SUPPORT_STATUS_UNSPECIFIED": 0,
	"MODEL_SUPPORT_STATUS_DECLARED":    1,
	"MODEL_SUPPORT_STATUS_ACTIVE":      2,
	"MODEL_SUPPORT_STATUS_STALE":       3,
	"MODEL_SUPPORT_STATUS_INACTIVE":    4,
}

func (x ModelSupportStatus) String() string {
	return proto.EnumName(ModelSupportStatus_name, int32(x))
}

func (ModelSupportStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{9}
}

// ModelSupportSuspendReason distinguishes a suspended declaration from one
// that has not yet been activated by a task.
type ModelSupportSuspendReason int32

const (
	// Never written.
	ModelSupportSuspendReason_MODEL_SUPPORT_SUSPEND_REASON_UNSPECIFIED ModelSupportSuspendReason = 0
	// The declaration is not suspended.
	ModelSupportSuspendReason_MODEL_SUPPORT_SUSPEND_REASON_NONE ModelSupportSuspendReason = 1
	// The operator is jailed.
	ModelSupportSuspendReason_MODEL_SUPPORT_SUSPEND_REASON_JAIL ModelSupportSuspendReason = 2
	// The effective bond is below the active model threshold.
	ModelSupportSuspendReason_MODEL_SUPPORT_SUSPEND_REASON_BOND_BELOW_MIN ModelSupportSuspendReason = 3
	// A raised model threshold became effective before the bond caught up.
	ModelSupportSuspendReason_MODEL_SUPPORT_SUSPEND_REASON_MIN_STAKE_RAISED ModelSupportSuspendReason = 4
)

var ModelSupportSuspendReason_name = map[int32]string{
	0: "MODEL_SUPPORT_SUSPEND_REASON_UNSPECIFIED",
	1: "MODEL_SUPPORT_SUSPEND_REASON_NONE",
	2: "MODEL_SUPPORT_SUSPEND_REASON_JAIL",
	3: "MODEL_SUPPORT_SUSPEND_REASON_BOND_BELOW_MIN",
	4: "MODEL_SUPPORT_SUSPEND_REASON_MIN_STAKE_RAISED",
}

var ModelSupportSuspendReason_value = map[string]int32{
	"MODEL_SUPPORT_SUSPEND_REASON_UNSPECIFIED":      0,
	"MODEL_SUPPORT_SUSPEND_REASON_NONE":             1,
	"MODEL_SUPPORT_SUSPEND_REASON_JAIL":             2,
	"MODEL_SUPPORT_SUSPEND_REASON_BOND_BELOW_MIN":   3,
	"MODEL_SUPPORT_SUSPEND_REASON_MIN_STAKE_RAISED": 4,
}

func (x ModelSupportSuspendReason) String() string {
	return proto.EnumName(ModelSupportSuspendReason_name, int32(x))
}

func (ModelSupportSuspendReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{10}
}

// RoleFaultStatus is the lifecycle of one recorded role fault receipt (6.4).
type RoleFaultStatus int32

const (
	// Never written; rejects zero-value rows.
	// ROLE_FAULT_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	RoleFaultStatus_ROLE_FAULT_STATUS_UNSPECIFIED RoleFaultStatus = 0
	// Fault receipt is the current attribution.
	// ROLE_FAULT_STATUS_CONFIRMED identifies the corresponding protocol value.
	RoleFaultStatus_ROLE_FAULT_STATUS_CONFIRMED RoleFaultStatus = 1
	// Replaced by a later attribution.
	// ROLE_FAULT_STATUS_SUPERSEDED identifies the corresponding protocol value.
	RoleFaultStatus_ROLE_FAULT_STATUS_SUPERSEDED RoleFaultStatus = 2
)

var RoleFaultStatus_name = map[int32]string{
	0: "ROLE_FAULT_STATUS_UNSPECIFIED",
	1: "ROLE_FAULT_STATUS_CONFIRMED",
	2: "ROLE_FAULT_STATUS_SUPERSEDED",
}

var RoleFaultStatus_value = map[string]int32{
	"ROLE_FAULT_STATUS_UNSPECIFIED": 0,
	"ROLE_FAULT_STATUS_CONFIRMED":   1,
	"ROLE_FAULT_STATUS_SUPERSEDED":  2,
}

func (x RoleFaultStatus) String() string {
	return proto.EnumName(RoleFaultStatus_name, int32(x))
}

func (RoleFaultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{11}
}

// FaultKind is the closed objective fault kind of one role fault receipt (9.6b).
type FaultKind int32

const (
	// Never written; rejects zero-value receipts.
	// FAULT_KIND_UNSPECIFIED identifies the corresponding protocol value.
	FaultKind_FAULT_KIND_UNSPECIFIED FaultKind = 0
	// Assigned duty missed its deadline.
	// FAULT_KIND_TIMEOUT identifies the corresponding protocol value.
	FaultKind_FAULT_KIND_TIMEOUT FaultKind = 1
	// Submitted material was objectively invalid.
	// FAULT_KIND_INVALID_RESULT identifies the corresponding protocol value.
	FaultKind_FAULT_KIND_INVALID_RESULT FaultKind = 2
	// Two conflicting accepted submissions for one scope.
	// FAULT_KIND_EQUIVOCATION identifies the corresponding protocol value.
	FaultKind_FAULT_KIND_EQUIVOCATION FaultKind = 3
	// Builder objective evidence was accepted against the operator.
	// FAULT_KIND_BUILDER_OBJECTIVE_FAULT identifies the corresponding protocol value.
	FaultKind_FAULT_KIND_BUILDER_OBJECTIVE_FAULT FaultKind = 5
	// Reserved for the later verifier value-evidence admission upgrade.
	FaultKind_FAULT_KIND_VERIFIER_VALUE_MISMATCH FaultKind = 6
	// Reserved for objectively invalid Worker value evidence after activation.
	FaultKind_FAULT_KIND_WORKER_VALUES_INVALID FaultKind = 7
)

var FaultKind_name = map[int32]string{
	0: "FAULT_KIND_UNSPECIFIED",
	1: "FAULT_KIND_TIMEOUT",
	2: "FAULT_KIND_INVALID_RESULT",
	3: "FAULT_KIND_EQUIVOCATION",
	5: "FAULT_KIND_BUILDER_OBJECTIVE_FAULT",
	6: "FAULT_KIND_VERIFIER_VALUE_MISMATCH",
	7: "FAULT_KIND_WORKER_VALUES_INVALID",
}

var FaultKind_value = map[string]int32{
	"FAULT_KIND_UNSPECIFIED":             0,
	"FAULT_KIND_TIMEOUT":                 1,
	"FAULT_KIND_INVALID_RESULT":          2,
	"FAULT_KIND_EQUIVOCATION":            3,
	"FAULT_KIND_BUILDER_OBJECTIVE_FAULT": 5,
	"FAULT_KIND_VERIFIER_VALUE_MISMATCH": 6,
	"FAULT_KIND_WORKER_VALUES_INVALID":   7,
}

func (x FaultKind) String() string {
	return proto.EnumName(FaultKind_name, int32(x))
}

func (FaultKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{12}
}

// ParamsModuleV1 selects the owner of a parameter-update event.
type ParamsModuleV1 int32

const (
	// Never emitted; rejects an unset parameter owner.
	// PARAMS_MODULE_V1_UNSPECIFIED identifies the corresponding protocol value.
	ParamsModuleV1_PARAMS_MODULE_V1_UNSPECIFIED ParamsModuleV1 = 0
	// Hub-owned parameter version.
	// PARAMS_MODULE_V1_HUB identifies the corresponding protocol value.
	ParamsModuleV1_PARAMS_MODULE_V1_HUB ParamsModuleV1 = 1
	// Task-owned parameter version.
	// PARAMS_MODULE_V1_TASK identifies the corresponding protocol value.
	ParamsModuleV1_PARAMS_MODULE_V1_TASK ParamsModuleV1 = 2
)

var ParamsModuleV1_name = map[int32]string{
	0: "PARAMS_MODULE_V1_UNSPECIFIED",
	1: "PARAMS_MODULE_V1_HUB",
	2: "PARAMS_MODULE_V1_TASK",
}

var ParamsModuleV1_value = map[string]int32{
	"PARAMS_MODULE_V1_UNSPECIFIED": 0,
	"PARAMS_MODULE_V1_HUB":         1,
	"PARAMS_MODULE_V1_TASK":        2,
}

func (x ParamsModuleV1) String() string {
	return proto.EnumName(ParamsModuleV1_name, int32(x))
}

func (ParamsModuleV1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{13}
}

// EventLifecycleReason is the closed lifecycle reason carried by jail, slash and exit events (9.6b).
type EventLifecycleReason int32

const (
	// Never written.
	// EVENT_LIFECYCLE_REASON_UNSPECIFIED identifies the corresponding protocol value.
	EventLifecycleReason_EVENT_LIFECYCLE_REASON_UNSPECIFIED EventLifecycleReason = 0
	// Triggered by a missed deadline.
	// EVENT_LIFECYCLE_REASON_TIMEOUT identifies the corresponding protocol value.
	EventLifecycleReason_EVENT_LIFECYCLE_REASON_TIMEOUT EventLifecycleReason = 1
	// Triggered by an accepted objective fault.
	// EVENT_LIFECYCLE_REASON_OBJECTIVE_FAULT identifies the corresponding protocol value.
	EventLifecycleReason_EVENT_LIFECYCLE_REASON_OBJECTIVE_FAULT EventLifecycleReason = 2
	// Triggered by a governance action.
	// EVENT_LIFECYCLE_REASON_GOVERNANCE identifies the corresponding protocol value.
	EventLifecycleReason_EVENT_LIFECYCLE_REASON_GOVERNANCE EventLifecycleReason = 3
	// Triggered by a service key revocation.
	// EVENT_LIFECYCLE_REASON_KEY_REVOKED identifies the corresponding protocol value.
	EventLifecycleReason_EVENT_LIFECYCLE_REASON_KEY_REVOKED EventLifecycleReason = 4
	// Triggered by the bond dropping below the minimum.
	// EVENT_LIFECYCLE_REASON_BOND_BELOW_MIN identifies the corresponding protocol value.
	EventLifecycleReason_EVENT_LIFECYCLE_REASON_BOND_BELOW_MIN EventLifecycleReason = 5
)

var EventLifecycleReason_name = map[int32]string{
	0: "EVENT_LIFECYCLE_REASON_UNSPECIFIED",
	1: "EVENT_LIFECYCLE_REASON_TIMEOUT",
	2: "EVENT_LIFECYCLE_REASON_OBJECTIVE_FAULT",
	3: "EVENT_LIFECYCLE_REASON_GOVERNANCE",
	4: "EVENT_LIFECYCLE_REASON_KEY_REVOKED",
	5: "EVENT_LIFECYCLE_REASON_BOND_BELOW_MIN",
}

var EventLifecycleReason_value = map[string]int32{
	"EVENT_LIFECYCLE_REASON_UNSPECIFIED":     0,
	"EVENT_LIFECYCLE_REASON_TIMEOUT":         1,
	"EVENT_LIFECYCLE_REASON_OBJECTIVE_FAULT": 2,
	"EVENT_LIFECYCLE_REASON_GOVERNANCE":      3,
	"EVENT_LIFECYCLE_REASON_KEY_REVOKED":     4,
	"EVENT_LIFECYCLE_REASON_BOND_BELOW_MIN":  5,
}

func (x EventLifecycleReason) String() string {
	return proto.EnumName(EventLifecycleReason_name, int32(x))
}

func (EventLifecycleReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77b62cd5ea6bd12d, []int{14}
}

func init() {
	proto.RegisterEnum("hub.v1.ServiceKeyStatus", ServiceKeyStatus_name, ServiceKeyStatus_value)
	proto.RegisterEnum("hub.v1.ServiceKeyRevocationReason", ServiceKeyRevocationReason_name, ServiceKeyRevocationReason_value)
	proto.RegisterEnum("hub.v1.ServiceKeyResponsibilityKind", ServiceKeyResponsibilityKind_name, ServiceKeyResponsibilityKind_value)
	proto.RegisterEnum("hub.v1.GovernanceReason", GovernanceReason_name, GovernanceReason_value)
	proto.RegisterEnum("hub.v1.ServiceBondStatus", ServiceBondStatus_name, ServiceBondStatus_value)
	proto.RegisterEnum("hub.v1.UnbondingStatus", UnbondingStatus_name, UnbondingStatus_value)
	proto.RegisterEnum("hub.v1.UnbondingReceiptTerminalStatus", UnbondingReceiptTerminalStatus_name, UnbondingReceiptTerminalStatus_value)
	proto.RegisterEnum("hub.v1.LiabilityStatus", LiabilityStatus_name, LiabilityStatus_value)
	proto.RegisterEnum("hub.v1.ModelSupportActivationKind", ModelSupportActivationKind_name, ModelSupportActivationKind_value)
	proto.RegisterEnum("hub.v1.ModelSupportStatus", ModelSupportStatus_name, ModelSupportStatus_value)
	proto.RegisterEnum("hub.v1.ModelSupportSuspendReason", ModelSupportSuspendReason_name, ModelSupportSuspendReason_value)
	proto.RegisterEnum("hub.v1.RoleFaultStatus", RoleFaultStatus_name, RoleFaultStatus_value)
	proto.RegisterEnum("hub.v1.FaultKind", FaultKind_name, FaultKind_value)
	proto.RegisterEnum("hub.v1.ParamsModuleV1", ParamsModuleV1_name, ParamsModuleV1_value)
	proto.RegisterEnum("hub.v1.EventLifecycleReason", EventLifecycleReason_name, EventLifecycleReason_value)
}

func init() { proto.RegisterFile("hub/v1/common.proto", fileDescriptor_77b62cd5ea6bd12d) }

var fileDescriptor_77b62cd5ea6bd12d = []byte{
	// 1253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0x3d, 0x93, 0xdb, 0x54,
	0x17, 0x5e, 0xd9, 0xde, 0x7d, 0x5f, 0x4e, 0x41, 0x2e, 0x22, 0x84, 0x64, 0x3f, 0x9c, 0xec, 0x92,
	0x64, 0x12, 0x85, 0x8d, 0xd9, 0x2c, 0x84, 0x8f, 0x82, 0x19, 0x59, 0x3a, 0xf6, 0xde, 0x58, 0x5f,
	0xdc, 0x7b, 0xe5, 0xc5, 0x69, 0x34, 0x5e, 0x5b, 0x24, 0x9e, 0xf1, 0x4a, 0x1e, 0x7f, 0xc1, 0xd6,
	0x34, 0x74, 0x50, 0xf0, 0x27, 0xf8, 0x09, 0x0c, 0x15, 0x1d, 0x65, 0x4a, 0x4a, 0x26, 0x29, 0xa0,
	0xe0, 0x1f, 0xd0, 0x30, 0x92, 0xe5, 0xb5, 0x62, 0xcb, 0x36, 0xa5, 0xfd, 0x3c, 0xcf, 0xd5, 0xb9,
	0xe7, 0x9c, 0xe7, 0xe8, 0x08, 0xde, 0x7e, 0x3e, 0x3a, 0x2b, 0x8d, 0x8f, 0x4a, 0xad, 0xf0, 0xfc,
	0x3c, 0x0c, 0x1e, 0xf6, 0xfa, 0xe1, 0x30, 0x94, 0xb7, 0x9e, 0x8f, 0xce, 0x1e, 0x8e, 0x8f, 0x94,
	0x11, 0x10, 0xee, 0xf7, 0xc7, 0x9d, 0x96, 0x5f, 0xf3, 0x2f, 0xf8, 0xb0, 0x39, 0x1c, 0x0d, 0xe4,
	0x03, 0x28, 0x72, 0x64, 0x75, 0xaa, 0xa1, 0x57, 0xc3, 0x86, 0xc7, 0x85, 0x2a, 0x5c, 0xee, 0xb9,
	0x16, 0x77, 0x50, 0xa3, 0x15, 0x8a, 0x3a, 0xd9, 0x90, 0xf7, 0xe0, 0x46, 0x06, 0x47, 0xd5, 0x04,
	0xad, 0x23, 0x91, 0xe4, 0x22, 0x6c, 0x67, 0xc0, 0x0c, 0xeb, 0x76, 0x0d, 0x75, 0x92, 0x53, 0xfe,
	0x94, 0x60, 0x7b, 0xf6, 0x5c, 0xe6, 0x8f, 0xc3, 0x56, 0x73, 0xd8, 0x09, 0x03, 0xe6, 0x37, 0x07,
	0x61, 0x20, 0x1f, 0xc2, 0xfd, 0xb4, 0x3c, 0xd2, 0x69, 0xaa, 0xa0, 0xb6, 0xe5, 0x31, 0x54, 0xb9,
	0x6d, 0xcd, 0x05, 0xb3, 0x96, 0xae, 0xd9, 0xa6, 0xc3, 0x6c, 0x93, 0x72, 0xd4, 0x89, 0x24, 0x1f,
	0x43, 0x69, 0x35, 0xdd, 0x76, 0x90, 0xa9, 0xc2, 0x66, 0x1e, 0x3f, 0x71, 0x85, 0x6e, 0x9f, 0x5a,
	0x24, 0x27, 0x3f, 0x86, 0x47, 0xab, 0x45, 0x55, 0xbb, 0x8e, 0xcc, 0x52, 0x2d, 0x0d, 0x3d, 0x34,
	0x91, 0x55, 0xd1, 0xd2, 0x1a, 0x24, 0xaf, 0xfc, 0x9d, 0x83, 0xdd, 0xf4, 0x4d, 0x07, 0xbd, 0x30,
	0x18, 0x74, 0xce, 0x3a, 0xdd, 0xce, 0xf0, 0xa2, 0xd6, 0x09, 0xda, 0x72, 0x09, 0x1e, 0xbc, 0x7e,
	0x30, 0x77, 0x6c, 0x8b, 0xd3, 0x32, 0x35, 0xa8, 0x68, 0x78, 0x35, 0x6a, 0xe9, 0x73, 0xb7, 0xfd,
	0x18, 0x8e, 0xd7, 0x09, 0x6c, 0x07, 0x2d, 0xaf, 0x8e, 0x8c, 0x56, 0x1a, 0x5e, 0xd9, 0xa5, 0x86,
	0x8e, 0x8c, 0x48, 0xf2, 0x23, 0x78, 0xb8, 0x4e, 0xc8, 0x51, 0x08, 0x03, 0x2f, 0x35, 0x19, 0xd7,
	0x5e, 0xd4, 0x68, 0x27, 0xaa, 0x61, 0xa0, 0x55, 0xc5, 0xc9, 0x13, 0x29, 0x32, 0x92, 0x97, 0x3f,
	0x83, 0xc7, 0xeb, 0x74, 0xa7, 0x36, 0xab, 0x21, 0xf3, 0x6c, 0x57, 0x38, 0xae, 0xf0, 0xb0, 0x4e,
	0x75, 0xb4, 0x34, 0x24, 0x85, 0xff, 0xa2, 0x2d, 0xbb, 0xdc, 0xb3, 0xcb, 0x4f, 0x30, 0xee, 0xb7,
	0x99, 0x76, 0x53, 0xf9, 0x45, 0x02, 0x52, 0x0d, 0xc7, 0x7e, 0x3f, 0x68, 0x06, 0x2d, 0x3f, 0x69,
	0xa7, 0x7d, 0xd8, 0x4b, 0x55, 0x27, 0xb3, 0x85, 0x76, 0xe1, 0xfa, 0x22, 0xa5, 0xc2, 0x10, 0x9f,
	0x26, 0xed, 0x9c, 0x75, 0x40, 0x82, 0xe7, 0xb2, 0xd5, 0x3a, 0x1a, 0x94, 0x0b, 0x92, 0x97, 0xef,
	0xc1, 0xed, 0x45, 0xf4, 0xb2, 0x47, 0x3c, 0x86, 0x5a, 0x84, 0x36, 0x48, 0x41, 0xf9, 0x36, 0x07,
	0x6f, 0x25, 0xcd, 0x52, 0x0e, 0x83, 0x76, 0xe2, 0xc7, 0xf7, 0xe0, 0xe6, 0x34, 0x1f, 0x65, 0x3b,
	0x2a, 0x52, 0x96, 0x21, 0x53, 0xa6, 0x4d, 0x93, 0x18, 0x56, 0x29, 0x17, 0xc8, 0xe2, 0xc6, 0x4f,
	0xb9, 0x32, 0xcd, 0x49, 0x5c, 0x9b, 0x5b, 0x86, 0x3f, 0x51, 0xa9, 0x81, 0x3a, 0xc9, 0x47, 0x79,
	0xcc, 0x0e, 0x24, 0xfa, 0x45, 0xad, 0x2a, 0x29, 0x2c, 0x3b, 0x02, 0xbf, 0xa4, 0x02, 0x75, 0xb2,
	0xb9, 0x2c, 0x4c, 0x61, 0x9b, 0x65, 0x2e, 0x6c, 0x0b, 0x75, 0xb2, 0xa5, 0xfc, 0x24, 0xc1, 0x15,
	0x37, 0x38, 0x0b, 0x83, 0x76, 0x27, 0x78, 0x96, 0xe4, 0xe0, 0x16, 0xec, 0x5e, 0x3e, 0x26, 0x3b,
	0x01, 0x37, 0xe0, 0x9d, 0x05, 0x46, 0xe4, 0x03, 0x22, 0xc9, 0x3b, 0xf0, 0xee, 0x02, 0x64, 0xaa,
	0xc2, 0x65, 0xc9, 0xa5, 0x17, 0xc0, 0x53, 0x2a, 0x4e, 0x74, 0xa6, 0x9e, 0x5a, 0x24, 0x1f, 0xd5,
	0x76, 0x01, 0xe7, 0x86, 0xca, 0x4f, 0x50, 0x27, 0x05, 0xe5, 0x67, 0x09, 0x8a, 0x97, 0xb1, 0x32,
	0xbf, 0xe5, 0x77, 0x7a, 0x43, 0xe1, 0xf7, 0xcf, 0x3b, 0x41, 0xb3, 0x9b, 0x84, 0x7e, 0x04, 0x87,
	0xb3, 0x03, 0x18, 0x6a, 0x48, 0x1d, 0xe1, 0x09, 0x64, 0x26, 0xb5, 0x54, 0x23, 0xfb, 0x2e, 0x25,
	0x78, 0xb0, 0x5e, 0x32, 0x0b, 0x32, 0x1e, 0x69, 0xeb, 0x05, 0x15, 0xd7, 0x30, 0x1a, 0x97, 0xb1,
	0xe7, 0x94, 0xef, 0x25, 0xb8, 0x62, 0x74, 0x9a, 0x93, 0x59, 0x34, 0xcb, 0xb3, 0x41, 0xd5, 0xc4,
	0x6a, 0xcb, 0x26, 0xff, 0x02, 0x83, 0x61, 0x54, 0xd4, 0xb8, 0xc7, 0xb2, 0x61, 0x03, 0xd5, 0x68,
	0xf6, 0xc6, 0x4e, 0x59, 0x80, 0xa7, 0x11, 0xe5, 0x95, 0xbf, 0x24, 0xd8, 0x36, 0xc3, 0xb6, 0xdf,
	0xe5, 0xa3, 0x5e, 0x2f, 0xec, 0x0f, 0xd5, 0xd6, 0xb0, 0x33, 0x8e, 0x5f, 0x0c, 0xf1, 0xa8, 0x3c,
	0x84, 0xfb, 0xa6, 0xad, 0xa3, 0xe1, 0x71, 0xd7, 0x71, 0x6c, 0x26, 0x26, 0x9d, 0x3b, 0x99, 0xc2,
	0x19, 0x83, 0xf2, 0x2e, 0x1c, 0xac, 0xa6, 0x5b, 0xb6, 0x15, 0xb9, 0xfb, 0x13, 0xf8, 0x70, 0x35,
	0x2f, 0x99, 0x54, 0xce, 0xf1, 0x07, 0x9e, 0xcd, 0x74, 0x64, 0x5e, 0x5d, 0x35, 0xdc, 0xa8, 0x77,
	0x3e, 0x85, 0x8f, 0x56, 0x2b, 0xa7, 0x13, 0xd1, 0x53, 0x39, 0xa7, 0x55, 0x0b, 0xf5, 0x48, 0x4a,
	0xa3, 0xab, 0xfe, 0x2a, 0x81, 0x9c, 0xbe, 0x6a, 0x92, 0xff, 0xdb, 0x70, 0xeb, 0xf5, 0x13, 0x33,
	0x6b, 0xb0, 0x0f, 0x7b, 0x99, 0x2c, 0x1d, 0x35, 0x43, 0x9d, 0x78, 0xfd, 0x26, 0xec, 0x64, 0x52,
	0xd2, 0x66, 0xcf, 0x24, 0x70, 0xa1, 0x1a, 0x38, 0x31, 0x7b, 0x26, 0x4e, 0xad, 0xe4, 0x88, 0x82,
	0xf2, 0x8f, 0x04, 0x37, 0x5e, 0xbb, 0xc3, 0x68, 0xd0, 0xf3, 0x83, 0x76, 0x32, 0x75, 0xdf, 0x87,
	0x7b, 0x73, 0x07, 0xb8, 0xdc, 0x41, 0x4b, 0xcf, 0x1e, 0xc0, 0x77, 0x60, 0x7f, 0x25, 0x3b, 0xa9,
	0xd5, 0x3a, 0x5a, 0x34, 0xab, 0x48, 0x2e, 0x32, 0xd0, 0x4a, 0x5a, 0x3c, 0x7b, 0xca, 0x68, 0xd8,
	0xa7, 0x9e, 0x49, 0x23, 0x97, 0x1f, 0xc1, 0xe1, 0x4a, 0x81, 0x49, 0xad, 0x28, 0x01, 0x35, 0xf4,
	0x98, 0x1a, 0xaf, 0x11, 0x05, 0xe5, 0x6b, 0xb8, 0xc2, 0xc2, 0xae, 0x5f, 0x69, 0x8e, 0xba, 0xd3,
	0xea, 0xed, 0xc3, 0x1e, 0xb3, 0x0d, 0xf4, 0x2a, 0xaa, 0x6b, 0x2c, 0x29, 0xdd, 0x4d, 0xd8, 0x59,
	0xa4, 0x68, 0xb6, 0x55, 0xa1, 0xcc, 0x8c, 0x0b, 0x77, 0x0b, 0x76, 0x17, 0x09, 0xdc, 0x75, 0x90,
	0x71, 0xd4, 0x63, 0xdf, 0xfe, 0x98, 0x83, 0x37, 0xe2, 0xa7, 0xc6, 0xa6, 0xd8, 0x86, 0x6b, 0x13,
	0x6a, 0x86, 0x03, 0xae, 0x81, 0x9c, 0xc2, 0x04, 0x35, 0xd1, 0x76, 0xc5, 0xc4, 0xa4, 0xa9, 0xff,
	0xa9, 0x15, 0x37, 0x65, 0xe4, 0x62, 0xd7, 0x10, 0x24, 0x17, 0xcd, 0xcb, 0x14, 0x8c, 0x5f, 0xb8,
	0x74, 0xba, 0xec, 0x90, 0x7c, 0xe4, 0xaa, 0x14, 0x98, 0x6c, 0x0a, 0xa9, 0x97, 0x71, 0x0c, 0x92,
	0xcd, 0x39, 0xde, 0xa5, 0x11, 0x62, 0xeb, 0x78, 0x26, 0xe5, 0xa6, 0x2a, 0xb4, 0x13, 0xb2, 0x15,
	0x75, 0x7c, 0x8a, 0x97, 0x58, 0x2d, 0x66, 0xf1, 0x69, 0x64, 0xe4, 0x7f, 0x07, 0x85, 0xff, 0x17,
	0x48, 0x41, 0xd9, 0x49, 0x87, 0x95, 0xbc, 0xf4, 0x3d, 0x1d, 0xe3, 0x7f, 0x95, 0x67, 0xf0, 0xa6,
	0xd3, 0xec, 0x37, 0xcf, 0x07, 0x66, 0xd8, 0x1e, 0x75, 0xfd, 0xfa, 0x51, 0x94, 0x4a, 0x47, 0x65,
	0xaa, 0xc9, 0x3d, 0xd3, 0xd6, 0x5d, 0x03, 0xbd, 0xfa, 0xd1, 0x5c, 0x82, 0xae, 0xc3, 0xd5, 0x05,
	0xc6, 0x89, 0x5b, 0x26, 0x52, 0xf4, 0x3a, 0x59, 0x40, 0x84, 0xca, 0x6b, 0x24, 0xa7, 0x7c, 0x97,
	0x83, 0xab, 0x38, 0xf6, 0x83, 0xa1, 0xd1, 0xf9, 0xca, 0x6f, 0x5d, 0xb4, 0xba, 0xd3, 0x3d, 0xe3,
	0x2e, 0x1c, 0x60, 0x1d, 0x2d, 0xe1, 0x19, 0xb4, 0x82, 0x5a, 0x43, 0x33, 0x96, 0x2c, 0x1b, 0x07,
	0x50, 0x5c, 0xc2, 0x9b, 0x95, 0x48, 0x81, 0xbb, 0x4b, 0x38, 0xf3, 0xa9, 0xce, 0x45, 0xa6, 0x58,
	0xc2, 0x9d, 0xed, 0x1d, 0x93, 0xca, 0x2d, 0xa1, 0x4d, 0x37, 0xda, 0x68, 0x39, 0x2f, 0xc8, 0xf7,
	0xe1, 0xce, 0x12, 0xde, 0x9c, 0x6d, 0x36, 0xcb, 0x9f, 0xff, 0xf6, 0xb2, 0x28, 0xbd, 0x78, 0x59,
	0x94, 0xfe, 0x78, 0x59, 0x94, 0x7e, 0x78, 0x55, 0xdc, 0x78, 0xf1, 0xaa, 0xb8, 0xf1, 0xfb, 0xab,
	0xe2, 0xc6, 0xd3, 0xdb, 0xcf, 0x3a, 0xc3, 0xe8, 0x1b, 0xa3, 0x15, 0x9e, 0x97, 0x44, 0x7f, 0xe4,
	0xdb, 0x3d, 0x3f, 0x28, 0x05, 0x61, 0xdb, 0x2f, 0x7d, 0x53, 0x8a, 0x3e, 0x48, 0x86, 0x17, 0x3d,
	0x7f, 0x70, 0xb6, 0x15, 0x7f, 0x8d, 0x1c, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xd2, 0x75,
	0xe4, 0xa4, 0x0c, 0x00, 0x00,
}
