// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/v1/fault.proto

package types

import (
	fmt "fmt"
	types "github.com/TrueOpen/node/x/shared/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SlashSourceKind is the closed idempotency namespace for one unified service
// slash. The primary key is (source_kind, source_id, effect_index).
// SlashSourceKind defines the SlashSourceKind wire type.
type SlashSourceKind int32

const (
	// Never written.
	// SLASH_SOURCE_KIND_UNSPECIFIED identifies the corresponding protocol value.
	SlashSourceKind_SLASH_SOURCE_KIND_UNSPECIFIED SlashSourceKind = 0
	// Sourced by a role fault receipt; source_id is the raw fault Hash32 and
	// effect_index is always 0.
	// SLASH_SOURCE_KIND_ROLE_FAULT identifies the corresponding protocol value.
	SlashSourceKind_SLASH_SOURCE_KIND_ROLE_FAULT SlashSourceKind = 1
	// Sourced by an applied challenge economic effect; source_id is the raw
	// challenge Hash32 and effect_index starts at 1.
	// SLASH_SOURCE_KIND_CHALLENGE_EFFECT identifies the corresponding protocol value.
	SlashSourceKind_SLASH_SOURCE_KIND_CHALLENGE_EFFECT SlashSourceKind = 2
)

var SlashSourceKind_name = map[int32]string{
	0: "SLASH_SOURCE_KIND_UNSPECIFIED",
	1: "SLASH_SOURCE_KIND_ROLE_FAULT",
	2: "SLASH_SOURCE_KIND_CHALLENGE_EFFECT",
}

var SlashSourceKind_value = map[string]int32{
	"SLASH_SOURCE_KIND_UNSPECIFIED":      0,
	"SLASH_SOURCE_KIND_ROLE_FAULT":       1,
	"SLASH_SOURCE_KIND_CHALLENGE_EFFECT": 2,
}

func (x SlashSourceKind) String() string {
	return proto.EnumName(SlashSourceKind_name, int32(x))
}

func (SlashSourceKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_764fefa941e2886c, []int{0}
}

// SlashDestination is the custody account that receives every layer debit.
// Keeper code maps this enum to a module account; callers cannot supply an
// arbitrary module name.
// SlashDestination defines the SlashDestination wire type.
type SlashDestination int32

const (
	// Never written.
	// SLASH_DESTINATION_UNSPECIFIED identifies the corresponding protocol value.
	SlashDestination_SLASH_DESTINATION_UNSPECIFIED SlashDestination = 0
	// Treasury custody; the only destination allowed for a role-fault slash.
	// SLASH_DESTINATION_TREASURY identifies the corresponding protocol value.
	SlashDestination_SLASH_DESTINATION_TREASURY SlashDestination = 1
	// Challenge effect pool custody; the only destination allowed for a challenge
	// effect slash.
	// SLASH_DESTINATION_CHALLENGE_EFFECT_POOL identifies the corresponding protocol value.
	SlashDestination_SLASH_DESTINATION_CHALLENGE_EFFECT_POOL SlashDestination = 2
)

var SlashDestination_name = map[int32]string{
	0: "SLASH_DESTINATION_UNSPECIFIED",
	1: "SLASH_DESTINATION_TREASURY",
	2: "SLASH_DESTINATION_CHALLENGE_EFFECT_POOL",
}

var SlashDestination_value = map[string]int32{
	"SLASH_DESTINATION_UNSPECIFIED":           0,
	"SLASH_DESTINATION_TREASURY":              1,
	"SLASH_DESTINATION_CHALLENGE_EFFECT_POOL": 2,
}

func (x SlashDestination) String() string {
	return proto.EnumName(SlashDestination_name, int32(x))
}

func (SlashDestination) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_764fefa941e2886c, []int{1}
}

// RoleFault is a single recorded fault attributed to one task duty.
//
// fault_id is deterministic and deduplicates the same observation across
// re-runs. WORKER and VERIFIER describe the duty assigned by the protocol for
// this task; they are not node-declared roles.
// RoleFaultState defines the RoleFaultState wire type.
type RoleFaultState struct {
	FaultId              []byte                            `protobuf:"bytes,1,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	TaskId               []byte                            `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OperatorAddress      string                            `protobuf:"bytes,3,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	Duty                 types.Duty                        `protobuf:"varint,4,opt,name=duty,proto3,enum=shared.v1.Duty" json:"duty,omitempty"`
	FaultClass           FaultKind                         `protobuf:"varint,5,opt,name=fault_class,json=faultClass,proto3,enum=hub.v1.FaultKind" json:"fault_class,omitempty"`
	ClassificationSource types.FailureClassificationSource `protobuf:"varint,6,opt,name=classification_source,json=classificationSource,proto3,enum=shared.v1.FailureClassificationSource" json:"classification_source,omitempty"`
	EvidenceDigest       []byte                            `protobuf:"bytes,7,opt,name=evidence_digest,json=evidenceDigest,proto3" json:"evidence_digest,omitempty"`
	JailDelta            uint32                            `protobuf:"varint,8,opt,name=jail_delta,json=jailDelta,proto3" json:"jail_delta,omitempty"`
	// Types that are valid to be assigned to XSlashSummaryId:
	//	*RoleFaultState_SlashSummaryId
	XSlashSummaryId isRoleFaultState_XSlashSummaryId `protobuf_oneof:"_slash_summary_id"`
	RecordedHeight  uint64                           `protobuf:"varint,10,opt,name=recorded_height,json=recordedHeight,proto3" json:"recorded_height,omitempty"`
	Status          RoleFaultStatus                  `protobuf:"varint,11,opt,name=status,proto3,enum=hub.v1.RoleFaultStatus" json:"status,omitempty"`
}

func (m *RoleFaultState) Reset()         { *m = RoleFaultState{} }
func (m *RoleFaultState) String() string { return proto.CompactTextString(m) }
func (*RoleFaultState) ProtoMessage()    {}
func (*RoleFaultState) Descriptor() ([]byte, []int) {
	return fileDescriptor_764fefa941e2886c, []int{0}
}
func (m *RoleFaultState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoleFaultState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoleFaultState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoleFaultState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleFaultState.Merge(m, src)
}
func (m *RoleFaultState) XXX_Size() int {
	return m.Size()
}
func (m *RoleFaultState) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleFaultState.DiscardUnknown(m)
}

var xxx_messageInfo_RoleFaultState proto.InternalMessageInfo

type isRoleFaultState_XSlashSummaryId interface {
	isRoleFaultState_XSlashSummaryId()
	MarshalTo([]byte) (int, error)
	Size() int
}

type RoleFaultState_SlashSummaryId struct {
	SlashSummaryId []byte `protobuf:"bytes,9,opt,name=slash_summary_id,json=slashSummaryId,proto3,oneof" json:"slash_summary_id,omitempty"`
}

func (*RoleFaultState_SlashSummaryId) isRoleFaultState_XSlashSummaryId() {}

func (m *RoleFaultState) GetXSlashSummaryId() isRoleFaultState_XSlashSummaryId {
	if m != nil {
		return m.XSlashSummaryId
	}
	return nil
}

func (m *RoleFaultState) GetFaultId() []byte {
	if m != nil {
		return m.FaultId
	}
	return nil
}

func (m *RoleFaultState) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *RoleFaultState) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *RoleFaultState) GetDuty() types.Duty {
	if m != nil {
		return m.Duty
	}
	return types.Duty_DUTY_UNSPECIFIED
}

func (m *RoleFaultState) GetFaultClass() FaultKind {
	if m != nil {
		return m.FaultClass
	}
	return FaultKind_FAULT_KIND_UNSPECIFIED
}

func (m *RoleFaultState) GetClassificationSource() types.FailureClassificationSource {
	if m != nil {
		return m.ClassificationSource
	}
	return types.FailureClassificationSource_FAILURE_CLASSIFICATION_SOURCE_UNSPECIFIED
}

func (m *RoleFaultState) GetEvidenceDigest() []byte {
	if m != nil {
		return m.EvidenceDigest
	}
	return nil
}

func (m *RoleFaultState) GetJailDelta() uint32 {
	if m != nil {
		return m.JailDelta
	}
	return 0
}

func (m *RoleFaultState) GetSlashSummaryId() []byte {
	if x, ok := m.GetXSlashSummaryId().(*RoleFaultState_SlashSummaryId); ok {
		return x.SlashSummaryId
	}
	return nil
}

func (m *RoleFaultState) GetRecordedHeight() uint64 {
	if m != nil {
		return m.RecordedHeight
	}
	return 0
}

func (m *RoleFaultState) GetStatus() RoleFaultStatus {
	if m != nil {
		return m.Status
	}
	return RoleFaultStatus_ROLE_FAULT_STATUS_UNSPECIFIED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoleFaultState) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoleFaultState_SlashSummaryId)(nil),
	}
}

// SlashSummaryState is the authoritative audit receipt for one execution of
// the four-layer service slash waterfall. slash_summary_id is a Hash32 replay
// handle; source_kind/source_id/effect_index are the collection key.
// SlashSummaryState defines the SlashSummaryState wire type.
type SlashSummaryState struct {
	SlashSummaryId []byte          `protobuf:"bytes,1,opt,name=slash_summary_id,json=slashSummaryId,proto3" json:"slash_summary_id,omitempty"`
	SourceKind     SlashSourceKind `protobuf:"varint,2,opt,name=source_kind,json=sourceKind,proto3,enum=hub.v1.SlashSourceKind" json:"source_kind,omitempty"`
	// Raw Hash32 in both namespaces: the fault_id for ROLE_FAULT, the
	// challenge_id for CHALLENGE_EFFECT. Never a hex projection.
	SourceId        []byte     `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	EffectIndex     uint64     `protobuf:"varint,4,opt,name=effect_index,json=effectIndex,proto3" json:"effect_index,omitempty"`
	OperatorAddress string     `protobuf:"bytes,5,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	Duty            types.Duty `protobuf:"varint,6,opt,name=duty,proto3,enum=shared.v1.Duty" json:"duty,omitempty"`
	// Types that are valid to be assigned to XTaskId:
	//	*SlashSummaryState_TaskId
	XTaskId                  isSlashSummaryState_XTaskId `protobuf_oneof:"_task_id"`
	RequestedAmount          types.Amount                `protobuf:"bytes,8,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount"`
	PendingTaskEarningsDebit types.Amount                `protobuf:"bytes,9,opt,name=pending_task_earnings_debit,json=pendingTaskEarningsDebit,proto3" json:"pending_task_earnings_debit"`
	ActiveBondDebit          types.Amount                `protobuf:"bytes,10,opt,name=active_bond_debit,json=activeBondDebit,proto3" json:"active_bond_debit"`
	UnbondingDebit           types.Amount                `protobuf:"bytes,11,opt,name=unbonding_debit,json=unbondingDebit,proto3" json:"unbonding_debit"`
	ClaimableEarningsDebit   types.Amount                `protobuf:"bytes,12,opt,name=claimable_earnings_debit,json=claimableEarningsDebit,proto3" json:"claimable_earnings_debit"`
	AppliedAmount            types.Amount                `protobuf:"bytes,13,opt,name=applied_amount,json=appliedAmount,proto3" json:"applied_amount"`
	UnfilledAmount           types.Amount                `protobuf:"bytes,14,opt,name=unfilled_amount,json=unfilledAmount,proto3" json:"unfilled_amount"`
	Destination              SlashDestination            `protobuf:"varint,15,opt,name=destination,proto3,enum=hub.v1.SlashDestination" json:"destination,omitempty"`
	UnbondingRowsVisited     uint32                      `protobuf:"varint,16,opt,name=unbonding_rows_visited,json=unbondingRowsVisited,proto3" json:"unbonding_rows_visited,omitempty"`
	AppliedHeight            uint64                      `protobuf:"varint,17,opt,name=applied_height,json=appliedHeight,proto3" json:"applied_height,omitempty"`
	BondVersion              uint64                      `protobuf:"varint,18,opt,name=bond_version,json=bondVersion,proto3" json:"bond_version,omitempty"`
}

func (m *SlashSummaryState) Reset()         { *m = SlashSummaryState{} }
func (m *SlashSummaryState) String() string { return proto.CompactTextString(m) }
func (*SlashSummaryState) ProtoMessage()    {}
func (*SlashSummaryState) Descriptor() ([]byte, []int) {
	return fileDescriptor_764fefa941e2886c, []int{1}
}
func (m *SlashSummaryState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SlashSummaryState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SlashSummaryState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SlashSummaryState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashSummaryState.Merge(m, src)
}
func (m *SlashSummaryState) XXX_Size() int {
	return m.Size()
}
func (m *SlashSummaryState) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashSummaryState.DiscardUnknown(m)
}

var xxx_messageInfo_SlashSummaryState proto.InternalMessageInfo

type isSlashSummaryState_XTaskId interface {
	isSlashSummaryState_XTaskId()
	MarshalTo([]byte) (int, error)
	Size() int
}

type SlashSummaryState_TaskId struct {
	TaskId []byte `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
}

func (*SlashSummaryState_TaskId) isSlashSummaryState_XTaskId() {}

func (m *SlashSummaryState) GetXTaskId() isSlashSummaryState_XTaskId {
	if m != nil {
		return m.XTaskId
	}
	return nil
}

func (m *SlashSummaryState) GetSlashSummaryId() []byte {
	if m != nil {
		return m.SlashSummaryId
	}
	return nil
}

func (m *SlashSummaryState) GetSourceKind() SlashSourceKind {
	if m != nil {
		return m.SourceKind
	}
	return SlashSourceKind_SLASH_SOURCE_KIND_UNSPECIFIED
}

func (m *SlashSummaryState) GetSourceId() []byte {
	if m != nil {
		return m.SourceId
	}
	return nil
}

func (m *SlashSummaryState) GetEffectIndex() uint64 {
	if m != nil {
		return m.EffectIndex
	}
	return 0
}

func (m *SlashSummaryState) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *SlashSummaryState) GetDuty() types.Duty {
	if m != nil {
		return m.Duty
	}
	return types.Duty_DUTY_UNSPECIFIED
}

func (m *SlashSummaryState) GetTaskId() []byte {
	if x, ok := m.GetXTaskId().(*SlashSummaryState_TaskId); ok {
		return x.TaskId
	}
	return nil
}

func (m *SlashSummaryState) GetRequestedAmount() types.Amount {
	if m != nil {
		return m.RequestedAmount
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetPendingTaskEarningsDebit() types.Amount {
	if m != nil {
		return m.PendingTaskEarningsDebit
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetActiveBondDebit() types.Amount {
	if m != nil {
		return m.ActiveBondDebit
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetUnbondingDebit() types.Amount {
	if m != nil {
		return m.UnbondingDebit
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetClaimableEarningsDebit() types.Amount {
	if m != nil {
		return m.ClaimableEarningsDebit
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetAppliedAmount() types.Amount {
	if m != nil {
		return m.AppliedAmount
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetUnfilledAmount() types.Amount {
	if m != nil {
		return m.UnfilledAmount
	}
	return types.Amount{}
}

func (m *SlashSummaryState) GetDestination() SlashDestination {
	if m != nil {
		return m.Destination
	}
	return SlashDestination_SLASH_DESTINATION_UNSPECIFIED
}

func (m *SlashSummaryState) GetUnbondingRowsVisited() uint32 {
	if m != nil {
		return m.UnbondingRowsVisited
	}
	return 0
}

func (m *SlashSummaryState) GetAppliedHeight() uint64 {
	if m != nil {
		return m.AppliedHeight
	}
	return 0
}

func (m *SlashSummaryState) GetBondVersion() uint64 {
	if m != nil {
		return m.BondVersion
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SlashSummaryState) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SlashSummaryState_TaskId)(nil),
	}
}

func init() {
	proto.RegisterEnum("hub.v1.SlashSourceKind", SlashSourceKind_name, SlashSourceKind_value)
	proto.RegisterEnum("hub.v1.SlashDestination", SlashDestination_name, SlashDestination_value)
	proto.RegisterType((*RoleFaultState)(nil), "hub.v1.RoleFaultState")
	proto.RegisterType((*SlashSummaryState)(nil), "hub.v1.SlashSummaryState")
}

func init() { proto.RegisterFile("hub/v1/fault.proto", fileDescriptor_764fefa941e2886c) }

var fileDescriptor_764fefa941e2886c = []byte{
	// 1010 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0x23, 0x45,
	0x17, 0x75, 0xe7, 0xf3, 0x38, 0x49, 0x39, 0xf1, 0x4f, 0x4d, 0xbe, 0xd0, 0x04, 0xe2, 0x71, 0x02,
	0xcc, 0x44, 0x83, 0xc6, 0x56, 0x32, 0x2c, 0x10, 0x8b, 0x11, 0xfe, 0x69, 0x93, 0xd6, 0x58, 0xf1,
	0xd0, 0xed, 0x44, 0x02, 0x16, 0xa5, 0x72, 0x57, 0xc5, 0x2e, 0xd2, 0xee, 0x32, 0x5d, 0xd5, 0x9e,
	0xc9, 0x86, 0x05, 0x2b, 0x96, 0xf0, 0x2e, 0x6c, 0xd9, 0x67, 0x39, 0x62, 0xc5, 0x0a, 0xa1, 0xe4,
	0x11, 0x78, 0x01, 0xd4, 0x55, 0xed, 0xf8, 0x27, 0x91, 0x47, 0x62, 0x67, 0x9f, 0x73, 0xee, 0xa9,
	0x7b, 0x6f, 0xdd, 0x5b, 0x0d, 0xe0, 0x20, 0xea, 0x55, 0xc7, 0x87, 0xd5, 0x73, 0x1c, 0xf9, 0xb2,
	0x32, 0x0a, 0xb9, 0xe4, 0x30, 0x33, 0x88, 0x7a, 0x95, 0xf1, 0xe1, 0xce, 0xfb, 0x1e, 0x17, 0x43,
	0x2e, 0x90, 0x42, 0xab, 0xfa, 0x8f, 0x96, 0xec, 0x6c, 0xf5, 0x79, 0x9f, 0x6b, 0x3c, 0xfe, 0x95,
	0xa0, 0x0f, 0x13, 0x33, 0x8f, 0x0f, 0x87, 0x3c, 0x48, 0xc0, 0x6d, 0x31, 0xc0, 0x21, 0x25, 0x31,
	0x8e, 0x87, 0x3c, 0x0a, 0xe4, 0x5d, 0x7c, 0x4e, 0xbf, 0x3b, 0xc5, 0x43, 0x2a, 0x24, 0xa2, 0x81,
	0xc7, 0x09, 0x0b, 0xfa, 0x9a, 0xde, 0xff, 0x3d, 0x0d, 0x72, 0x0e, 0xf7, 0x69, 0x2b, 0x4e, 0xd8,
	0x95, 0x58, 0x52, 0xf8, 0x08, 0xac, 0xa9, 0xf4, 0x11, 0x23, 0xa6, 0x51, 0x36, 0x0e, 0x36, 0xea,
	0xe9, 0xab, 0x7f, 0xcc, 0x15, 0x67, 0x55, 0xa1, 0x36, 0x81, 0xbb, 0x60, 0x55, 0x62, 0x71, 0x11,
	0xf3, 0x2b, 0x33, 0x7c, 0x26, 0x06, 0x6d, 0x02, 0x1b, 0xa0, 0xc0, 0x47, 0x34, 0xc4, 0x92, 0x87,
	0x08, 0x13, 0x12, 0x52, 0x21, 0xcc, 0xff, 0x95, 0x8d, 0x83, 0xf5, 0xba, 0xf9, 0xc7, 0x6f, 0xcf,
	0xb6, 0x92, 0xc2, 0x6b, 0x9a, 0x71, 0x65, 0xc8, 0x82, 0xbe, 0x93, 0x9f, 0x44, 0x24, 0x30, 0xfc,
	0x08, 0xa4, 0x49, 0x24, 0x2f, 0xcd, 0x74, 0xd9, 0x38, 0xc8, 0x1d, 0xe5, 0x2b, 0xba, 0x8a, 0xca,
	0xf8, 0xb0, 0xd2, 0x8c, 0xe4, 0xa5, 0xa3, 0x48, 0x78, 0x04, 0xb2, 0x3a, 0x53, 0xcf, 0xc7, 0x42,
	0x98, 0x0f, 0x94, 0xb6, 0x58, 0xd1, 0xfd, 0xae, 0xa8, 0x92, 0x5e, 0xb2, 0x80, 0x38, 0x40, 0xa9,
	0x1a, 0xb1, 0x08, 0x7e, 0x07, 0xfe, 0xaf, 0xd4, 0xec, 0x9c, 0x79, 0x58, 0x32, 0x1e, 0x20, 0xc1,
	0xa3, 0xd0, 0xa3, 0x66, 0x46, 0x45, 0x3f, 0x9e, 0x39, 0xa9, 0x85, 0x99, 0x1f, 0x85, 0xb4, 0x31,
	0x27, 0x77, 0x95, 0xda, 0xd9, 0xf2, 0xee, 0x41, 0xe1, 0x33, 0x90, 0xa7, 0x63, 0x46, 0x68, 0xe0,
	0x51, 0x44, 0x58, 0x9f, 0x0a, 0x69, 0xae, 0xce, 0x74, 0x28, 0x37, 0x21, 0x9b, 0x8a, 0x83, 0xbb,
	0x00, 0x7c, 0x8f, 0x99, 0x8f, 0x08, 0xf5, 0x25, 0x36, 0xd7, 0xca, 0xc6, 0xc1, 0xa6, 0xb3, 0x1e,
	0x23, 0xcd, 0x18, 0x80, 0xcf, 0x41, 0x41, 0xf8, 0x58, 0x0c, 0x90, 0x88, 0x86, 0x43, 0x1c, 0x5e,
	0xc6, 0x0d, 0x5f, 0x9f, 0xda, 0x1d, 0xa7, 0x9c, 0x9c, 0xe2, 0x5d, 0x4d, 0xdb, 0xe4, 0x67, 0xc3,
	0x80, 0x4f, 0x40, 0x3e, 0xa4, 0x1e, 0x0f, 0x09, 0x25, 0x68, 0x40, 0x59, 0x7f, 0x20, 0x4d, 0x50,
	0x36, 0x0e, 0xd2, 0x4e, 0x6e, 0x02, 0x1f, 0x2b, 0x14, 0x56, 0x41, 0x46, 0x48, 0x2c, 0x23, 0x61,
	0x66, 0x55, 0xe5, 0xef, 0x4d, 0xfa, 0x36, 0x37, 0x0e, 0x91, 0x70, 0x12, 0x59, 0xfd, 0x21, 0x28,
	0xa2, 0xc5, 0x7c, 0xf6, 0x7f, 0x5d, 0x03, 0x45, 0x77, 0x26, 0x09, 0x3d, 0x42, 0x95, 0x7b, 0x32,
	0x9f, 0x1d, 0xa5, 0x85, 0xbc, 0xe1, 0xe7, 0x20, 0xab, 0x6f, 0x01, 0x5d, 0xb0, 0x40, 0x4f, 0xd5,
	0x4c, 0x42, 0xda, 0x5f, 0xf1, 0xfa, 0x3a, 0xc5, 0xed, 0x6f, 0xb8, 0x07, 0xd6, 0x93, 0x48, 0x46,
	0xd4, 0x94, 0x4d, 0x8e, 0x58, 0xd3, 0xb0, 0x1d, 0x4b, 0x36, 0xe8, 0xf9, 0x39, 0xf5, 0x24, 0x62,
	0x01, 0xa1, 0x6f, 0xd4, 0x48, 0xa5, 0x9d, 0xac, 0xc6, 0xec, 0x18, 0xba, 0x77, 0x64, 0x1f, 0xfc,
	0xd7, 0x91, 0xcd, 0x2c, 0x1b, 0xd9, 0xfd, 0xe9, 0xee, 0xac, 0xce, 0x5d, 0x65, 0xb2, 0x3d, 0xf1,
	0x15, 0xd6, 0x41, 0x21, 0xa4, 0x3f, 0x44, 0x54, 0x48, 0x4a, 0x90, 0x5e, 0x72, 0x35, 0x1c, 0xd9,
	0xa3, 0xe2, 0x8c, 0x69, 0x4d, 0x11, 0xf5, 0xf4, 0xd5, 0x5f, 0x8f, 0x52, 0x4e, 0xfe, 0x36, 0x40,
	0xc3, 0xf0, 0x0c, 0x7c, 0x30, 0xa2, 0x41, 0xbc, 0xe8, 0x48, 0x9d, 0x47, 0x71, 0x18, 0xb0, 0xa0,
	0x2f, 0x10, 0xa1, 0x3d, 0x26, 0xd5, 0x18, 0x2d, 0xb1, 0x33, 0x93, 0xd8, 0x2e, 0x16, 0x17, 0x56,
	0x12, 0xd9, 0x8c, 0x03, 0x61, 0x03, 0x14, 0xb1, 0x27, 0xd9, 0x98, 0xa2, 0x1e, 0x0f, 0x48, 0xe2,
	0x06, 0xde, 0x91, 0x9c, 0x8e, 0xa8, 0xf3, 0x80, 0x68, 0x93, 0x2f, 0x41, 0x3e, 0x0a, 0xe2, 0xf8,
	0x38, 0x3d, 0x6d, 0x91, 0x5d, 0x6e, 0x91, 0xbb, 0xd5, 0x6b, 0x87, 0xaf, 0x81, 0xe9, 0xf9, 0x98,
	0x0d, 0x71, 0xcf, 0xa7, 0x8b, 0xb5, 0x6d, 0x2c, 0xb7, 0xda, 0xbe, 0x0d, 0x9c, 0xaf, 0xec, 0x05,
	0xc8, 0xe1, 0xd1, 0xc8, 0x67, 0xd3, 0x9e, 0x6f, 0x2e, 0x37, 0xda, 0x4c, 0xe4, 0x49, 0xc7, 0x55,
	0x51, 0xe7, 0xcc, 0xf7, 0xa7, 0x06, 0xb9, 0x77, 0x16, 0xa5, 0xf5, 0x89, 0xc3, 0x17, 0x20, 0x4b,
	0xa8, 0x90, 0x2c, 0x50, 0x4f, 0x8a, 0x99, 0x57, 0x73, 0x64, 0xce, 0x6d, 0x41, 0x73, 0xca, 0x3b,
	0xb3, 0x62, 0xf8, 0x19, 0xd8, 0x9e, 0xb6, 0x34, 0xe4, 0xaf, 0x05, 0x1a, 0x33, 0xc1, 0x24, 0x25,
	0x66, 0x41, 0x3d, 0x2b, 0x5b, 0xb7, 0xac, 0xc3, 0x5f, 0x8b, 0x33, 0xcd, 0xc1, 0x4f, 0xa6, 0x35,
	0x27, 0x6f, 0x45, 0x51, 0x2d, 0xc7, 0xa4, 0xb4, 0xe4, 0xa9, 0xd8, 0x03, 0x1b, 0xea, 0xb6, 0xc7,
	0x34, 0x14, 0x71, 0x66, 0x50, 0x6f, 0x50, 0x8c, 0x9d, 0x69, 0xa8, 0x0e, 0xc0, 0x1a, 0x4a, 0x06,
	0xfb, 0xe9, 0x8f, 0x20, 0xbf, 0xb0, 0xb2, 0x70, 0x0f, 0xec, 0xba, 0xed, 0x9a, 0x7b, 0x8c, 0xdc,
	0xce, 0xa9, 0xd3, 0xb0, 0xd0, 0x4b, 0xfb, 0xa4, 0x89, 0x4e, 0x4f, 0xdc, 0x57, 0x56, 0xc3, 0x6e,
	0xd9, 0x56, 0xb3, 0x90, 0x82, 0x65, 0xf0, 0xe1, 0x5d, 0x89, 0xd3, 0x69, 0x5b, 0xa8, 0x55, 0x3b,
	0x6d, 0x77, 0x0b, 0x06, 0x7c, 0x0c, 0xf6, 0xef, 0x2a, 0x1a, 0xc7, 0xb5, 0x76, 0xdb, 0x3a, 0xf9,
	0xca, 0x42, 0x56, 0xab, 0x65, 0x35, 0xba, 0x85, 0x95, 0xa7, 0x3f, 0x19, 0xa0, 0xb0, 0xd8, 0xad,
	0x69, 0x06, 0x4d, 0xcb, 0xed, 0xda, 0x27, 0xb5, 0xae, 0xdd, 0x39, 0x59, 0xc8, 0xa0, 0x04, 0x76,
	0xee, 0x4a, 0xba, 0x8e, 0x55, 0x73, 0x4f, 0x9d, 0x6f, 0x0a, 0x06, 0xfc, 0x14, 0x3c, 0xb9, 0xcb,
	0x2f, 0x9e, 0x8f, 0x5e, 0x75, 0x3a, 0xed, 0xc2, 0x4a, 0xfd, 0xc5, 0xd5, 0x75, 0xc9, 0x78, 0x7b,
	0x5d, 0x32, 0xfe, 0xbe, 0x2e, 0x19, 0xbf, 0xdc, 0x94, 0x52, 0x6f, 0x6f, 0x4a, 0xa9, 0x3f, 0x6f,
	0x4a, 0xa9, 0x6f, 0x3f, 0xee, 0x33, 0x19, 0xdf, 0xa9, 0xc7, 0x87, 0xd5, 0x6e, 0x18, 0xd1, 0xce,
	0x88, 0x06, 0xd5, 0x80, 0x13, 0x5a, 0x7d, 0x53, 0x8d, 0xbf, 0xf8, 0xf2, 0x72, 0x44, 0x45, 0x2f,
	0xa3, 0xbe, 0xcf, 0xcf, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xac, 0xbf, 0xd6, 0xac, 0x52, 0x08,
	0x00, 0x00,
}

func (m *RoleFaultState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoleFaultState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoleFaultState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x58
	}
	if m.RecordedHeight != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.RecordedHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.XSlashSummaryId != nil {
		{
			size := m.XSlashSummaryId.Size()
			i -= size
			if _, err := m.XSlashSummaryId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.JailDelta != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.JailDelta))
		i--
		dAtA[i] = 0x40
	}
	if len(m.EvidenceDigest) > 0 {
		i -= len(m.EvidenceDigest)
		copy(dAtA[i:], m.EvidenceDigest)
		i = encodeVarintFault(dAtA, i, uint64(len(m.EvidenceDigest)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ClassificationSource != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.ClassificationSource))
		i--
		dAtA[i] = 0x30
	}
	if m.FaultClass != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.FaultClass))
		i--
		dAtA[i] = 0x28
	}
	if m.Duty != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.Duty))
		i--
		dAtA[i] = 0x20
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintFault(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintFault(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FaultId) > 0 {
		i -= len(m.FaultId)
		copy(dAtA[i:], m.FaultId)
		i = encodeVarintFault(dAtA, i, uint64(len(m.FaultId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RoleFaultState_SlashSummaryId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoleFaultState_SlashSummaryId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SlashSummaryId != nil {
		i -= len(m.SlashSummaryId)
		copy(dAtA[i:], m.SlashSummaryId)
		i = encodeVarintFault(dAtA, i, uint64(len(m.SlashSummaryId)))
		i--
		dAtA[i] = 0x4a
	}
	return len(dAtA) - i, nil
}
func (m *SlashSummaryState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SlashSummaryState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlashSummaryState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BondVersion != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.BondVersion))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.AppliedHeight != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.AppliedHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.UnbondingRowsVisited != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.UnbondingRowsVisited))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.Destination != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.Destination))
		i--
		dAtA[i] = 0x78
	}
	{
		size, err := m.UnfilledAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size, err := m.AppliedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.ClaimableEarningsDebit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size, err := m.UnbondingDebit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.ActiveBondDebit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.PendingTaskEarningsDebit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.RequestedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.XTaskId != nil {
		{
			size := m.XTaskId.Size()
			i -= size
			if _, err := m.XTaskId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Duty != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.Duty))
		i--
		dAtA[i] = 0x30
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintFault(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.EffectIndex != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.EffectIndex))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SourceId) > 0 {
		i -= len(m.SourceId)
		copy(dAtA[i:], m.SourceId)
		i = encodeVarintFault(dAtA, i, uint64(len(m.SourceId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SourceKind != 0 {
		i = encodeVarintFault(dAtA, i, uint64(m.SourceKind))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SlashSummaryId) > 0 {
		i -= len(m.SlashSummaryId)
		copy(dAtA[i:], m.SlashSummaryId)
		i = encodeVarintFault(dAtA, i, uint64(len(m.SlashSummaryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SlashSummaryState_TaskId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlashSummaryState_TaskId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.TaskId != nil {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintFault(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func encodeVarintFault(dAtA []byte, offset int, v uint64) int {
	offset -= sovFault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RoleFaultState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FaultId)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	if m.Duty != 0 {
		n += 1 + sovFault(uint64(m.Duty))
	}
	if m.FaultClass != 0 {
		n += 1 + sovFault(uint64(m.FaultClass))
	}
	if m.ClassificationSource != 0 {
		n += 1 + sovFault(uint64(m.ClassificationSource))
	}
	l = len(m.EvidenceDigest)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	if m.JailDelta != 0 {
		n += 1 + sovFault(uint64(m.JailDelta))
	}
	if m.XSlashSummaryId != nil {
		n += m.XSlashSummaryId.Size()
	}
	if m.RecordedHeight != 0 {
		n += 1 + sovFault(uint64(m.RecordedHeight))
	}
	if m.Status != 0 {
		n += 1 + sovFault(uint64(m.Status))
	}
	return n
}

func (m *RoleFaultState_SlashSummaryId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlashSummaryId != nil {
		l = len(m.SlashSummaryId)
		n += 1 + l + sovFault(uint64(l))
	}
	return n
}
func (m *SlashSummaryState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SlashSummaryId)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	if m.SourceKind != 0 {
		n += 1 + sovFault(uint64(m.SourceKind))
	}
	l = len(m.SourceId)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	if m.EffectIndex != 0 {
		n += 1 + sovFault(uint64(m.EffectIndex))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovFault(uint64(l))
	}
	if m.Duty != 0 {
		n += 1 + sovFault(uint64(m.Duty))
	}
	if m.XTaskId != nil {
		n += m.XTaskId.Size()
	}
	l = m.RequestedAmount.Size()
	n += 1 + l + sovFault(uint64(l))
	l = m.PendingTaskEarningsDebit.Size()
	n += 1 + l + sovFault(uint64(l))
	l = m.ActiveBondDebit.Size()
	n += 1 + l + sovFault(uint64(l))
	l = m.UnbondingDebit.Size()
	n += 1 + l + sovFault(uint64(l))
	l = m.ClaimableEarningsDebit.Size()
	n += 1 + l + sovFault(uint64(l))
	l = m.AppliedAmount.Size()
	n += 1 + l + sovFault(uint64(l))
	l = m.UnfilledAmount.Size()
	n += 1 + l + sovFault(uint64(l))
	if m.Destination != 0 {
		n += 1 + sovFault(uint64(m.Destination))
	}
	if m.UnbondingRowsVisited != 0 {
		n += 2 + sovFault(uint64(m.UnbondingRowsVisited))
	}
	if m.AppliedHeight != 0 {
		n += 2 + sovFault(uint64(m.AppliedHeight))
	}
	if m.BondVersion != 0 {
		n += 2 + sovFault(uint64(m.BondVersion))
	}
	return n
}

func (m *SlashSummaryState_TaskId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != nil {
		l = len(m.TaskId)
		n += 1 + l + sovFault(uint64(l))
	}
	return n
}

func sovFault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFault(x uint64) (n int) {
	return sovFault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RoleFaultState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoleFaultState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoleFaultState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaultId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FaultId = append(m.FaultId[:0], dAtA[iNdEx:postIndex]...)
			if m.FaultId == nil {
				m.FaultId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duty", wireType)
			}
			m.Duty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duty |= types.Duty(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaultClass", wireType)
			}
			m.FaultClass = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FaultClass |= FaultKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassificationSource", wireType)
			}
			m.ClassificationSource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClassificationSource |= types.FailureClassificationSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceDigest = append(m.EvidenceDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.EvidenceDigest == nil {
				m.EvidenceDigest = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailDelta", wireType)
			}
			m.JailDelta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JailDelta |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashSummaryId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.XSlashSummaryId = &RoleFaultState_SlashSummaryId{v}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordedHeight", wireType)
			}
			m.RecordedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RoleFaultStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SlashSummaryState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SlashSummaryState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SlashSummaryState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashSummaryId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashSummaryId = append(m.SlashSummaryId[:0], dAtA[iNdEx:postIndex]...)
			if m.SlashSummaryId == nil {
				m.SlashSummaryId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceKind", wireType)
			}
			m.SourceKind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceKind |= SlashSourceKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceId = append(m.SourceId[:0], dAtA[iNdEx:postIndex]...)
			if m.SourceId == nil {
				m.SourceId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectIndex", wireType)
			}
			m.EffectIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duty", wireType)
			}
			m.Duty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duty |= types.Duty(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.XTaskId = &SlashSummaryState_TaskId{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequestedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTaskEarningsDebit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingTaskEarningsDebit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveBondDebit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActiveBondDebit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingDebit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnbondingDebit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimableEarningsDebit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimableEarningsDebit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppliedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AppliedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnfilledAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnfilledAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			m.Destination = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Destination |= SlashDestination(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingRowsVisited", wireType)
			}
			m.UnbondingRowsVisited = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingRowsVisited |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppliedHeight", wireType)
			}
			m.AppliedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppliedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondVersion", wireType)
			}
			m.BondVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFault = fmt.Errorf("proto: unexpected end of group")
)
