// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/v1/model_profile_state.proto

package types

import (
	fmt "fmt"
	types "github.com/TrueOpen/node/x/shared/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ModelProfileStatus is the shared model and profile lifecycle status; numbers are frozen by the upstream model registry projection referenced from 9.6b.
type ModelProfileStatus int32

const (
	// Never written; rejects zero-value rows.
	// MODEL_PROFILE_STATUS_UNSPECIFIED identifies the corresponding protocol value.
	ModelProfileStatus_MODEL_PROFILE_STATUS_UNSPECIFIED ModelProfileStatus = 0
	// Registered but not yet usable for new tasks.
	// MODEL_PROFILE_STATUS_REGISTERED identifies the corresponding protocol value.
	ModelProfileStatus_MODEL_PROFILE_STATUS_REGISTERED ModelProfileStatus = 1
	// Usable for new tasks.
	// MODEL_PROFILE_STATUS_ACTIVE identifies the corresponding protocol value.
	ModelProfileStatus_MODEL_PROFILE_STATUS_ACTIVE ModelProfileStatus = 2
	// Governance frozen; unfreezing returns to REGISTERED.
	// MODEL_PROFILE_STATUS_FROZEN identifies the corresponding protocol value.
	ModelProfileStatus_MODEL_PROFILE_STATUS_FROZEN ModelProfileStatus = 3
	// Frozen by the validator emergency freeze quorum.
	// MODEL_PROFILE_STATUS_EMERGENCY_FROZEN identifies the corresponding protocol value.
	ModelProfileStatus_MODEL_PROFILE_STATUS_EMERGENCY_FROZEN ModelProfileStatus = 4
	// Terminal; never returns to a usable status.
	// MODEL_PROFILE_STATUS_DELISTED identifies the corresponding protocol value.
	ModelProfileStatus_MODEL_PROFILE_STATUS_DELISTED ModelProfileStatus = 5
)

var ModelProfileStatus_name = map[int32]string{
	0: "MODEL_PROFILE_STATUS_UNSPECIFIED",
	1: "MODEL_PROFILE_STATUS_REGISTERED",
	2: "MODEL_PROFILE_STATUS_ACTIVE",
	3: "MODEL_PROFILE_STATUS_FROZEN",
	4: "MODEL_PROFILE_STATUS_EMERGENCY_FROZEN",
	5: "MODEL_PROFILE_STATUS_DELISTED",
}

var ModelProfileStatus_value = map[string]int32{
	"MODEL_PROFILE_STATUS_UNSPECIFIED":      0,
	"MODEL_PROFILE_STATUS_REGISTERED":       1,
	"MODEL_PROFILE_STATUS_ACTIVE":           2,
	"MODEL_PROFILE_STATUS_FROZEN":           3,
	"MODEL_PROFILE_STATUS_EMERGENCY_FROZEN": 4,
	"MODEL_PROFILE_STATUS_DELISTED":         5,
}

func (x ModelProfileStatus) String() string {
	return proto.EnumName(ModelProfileStatus_name, int32(x))
}

func (ModelProfileStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2a17f60d08b8e7, []int{0}
}

// ModelStatusSource attributes one model status transition to its trigger.
type ModelStatusSource int32

const (
	// Never written.
	// MODEL_STATUS_SOURCE_UNSPECIFIED identifies the corresponding protocol value.
	ModelStatusSource_MODEL_STATUS_SOURCE_UNSPECIFIED ModelStatusSource = 0
	// Derived from the model-wide support aggregate.
	ModelStatusSource_MODEL_STATUS_SOURCE_AUTO_SUPPORT ModelStatusSource = 1
	// Applied by a governance transition.
	// MODEL_STATUS_SOURCE_GOVERNANCE identifies the corresponding protocol value.
	ModelStatusSource_MODEL_STATUS_SOURCE_GOVERNANCE ModelStatusSource = 2
	// Applied by the emergency freeze path.
	// MODEL_STATUS_SOURCE_EMERGENCY identifies the corresponding protocol value.
	ModelStatusSource_MODEL_STATUS_SOURCE_EMERGENCY ModelStatusSource = 3
)

var ModelStatusSource_name = map[int32]string{
	0: "MODEL_STATUS_SOURCE_UNSPECIFIED",
	1: "MODEL_STATUS_SOURCE_AUTO_SUPPORT",
	2: "MODEL_STATUS_SOURCE_GOVERNANCE",
	3: "MODEL_STATUS_SOURCE_EMERGENCY",
}

var ModelStatusSource_value = map[string]int32{
	"MODEL_STATUS_SOURCE_UNSPECIFIED":  0,
	"MODEL_STATUS_SOURCE_AUTO_SUPPORT": 1,
	"MODEL_STATUS_SOURCE_GOVERNANCE":   2,
	"MODEL_STATUS_SOURCE_EMERGENCY":    3,
}

func (x ModelStatusSource) String() string {
	return proto.EnumName(ModelStatusSource_name, int32(x))
}

func (ModelStatusSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2a17f60d08b8e7, []int{1}
}

// ProfileStatusSource attributes one profile status transition to its trigger.
type ProfileStatusSource int32

const (
	// Never written.
	// PROFILE_STATUS_SOURCE_UNSPECIFIED identifies the corresponding protocol value.
	ProfileStatusSource_PROFILE_STATUS_SOURCE_UNSPECIFIED ProfileStatusSource = 0
	// Applied by a governance transition.
	// PROFILE_STATUS_SOURCE_GOVERNANCE identifies the corresponding protocol value.
	ProfileStatusSource_PROFILE_STATUS_SOURCE_GOVERNANCE ProfileStatusSource = 2
	// Applied by the emergency freeze path.
	// PROFILE_STATUS_SOURCE_EMERGENCY identifies the corresponding protocol value.
	ProfileStatusSource_PROFILE_STATUS_SOURCE_EMERGENCY ProfileStatusSource = 3
)

var ProfileStatusSource_name = map[int32]string{
	0: "PROFILE_STATUS_SOURCE_UNSPECIFIED",
	2: "PROFILE_STATUS_SOURCE_GOVERNANCE",
	3: "PROFILE_STATUS_SOURCE_EMERGENCY",
}

var ProfileStatusSource_value = map[string]int32{
	"PROFILE_STATUS_SOURCE_UNSPECIFIED": 0,
	"PROFILE_STATUS_SOURCE_GOVERNANCE":  2,
	"PROFILE_STATUS_SOURCE_EMERGENCY":   3,
}

func (x ProfileStatusSource) String() string {
	return proto.EnumName(ProfileStatusSource_name, int32(x))
}

func (ProfileStatusSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2a17f60d08b8e7, []int{2}
}

// ModelState is one registered model primary row (wire storage model 6.3).
type ModelState struct {
	ModelId         []byte             `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProposerAddress string             `protobuf:"bytes,2,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	Status          ModelProfileStatus `protobuf:"varint,3,opt,name=status,proto3,enum=hub.v1.ModelProfileStatus" json:"status,omitempty"`
	// active_profile_count (4) counted profiles in ACTIVE status. ACTIVE is now
	// derived from ModelSupportState alone (active_support_stake,
	// active_supporter_count below), so no producer sets a per-profile count.
	LatestProfileVersion   uint32            `protobuf:"varint,5,opt,name=latest_profile_version,json=latestProfileVersion,proto3" json:"latest_profile_version,omitempty"`
	StatusSource           ModelStatusSource `protobuf:"varint,6,opt,name=status_source,json=statusSource,proto3,enum=hub.v1.ModelStatusSource" json:"status_source,omitempty"`
	RegistrationFeePaid    uint64            `protobuf:"varint,7,opt,name=registration_fee_paid,json=registrationFeePaid,proto3" json:"registration_fee_paid,omitempty"`
	CreatedHeight          uint64            `protobuf:"varint,8,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	UpdatedHeight          uint64            `protobuf:"varint,9,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
	ActiveSupportStake     uint64            `protobuf:"varint,10,opt,name=active_support_stake,json=activeSupportStake,proto3" json:"active_support_stake,omitempty"`
	ActiveSupporterCount   uint32            `protobuf:"varint,11,opt,name=active_supporter_count,json=activeSupporterCount,proto3" json:"active_supporter_count,omitempty"`
	SupportMinStake        uint64            `protobuf:"varint,12,opt,name=support_min_stake,json=supportMinStake,proto3" json:"support_min_stake,omitempty"`
	PendingSupportMinStake uint64            `protobuf:"varint,13,opt,name=pending_support_min_stake,json=pendingSupportMinStake,proto3" json:"pending_support_min_stake,omitempty"`
	PendingEffectiveHeight uint64            `protobuf:"varint,14,opt,name=pending_effective_height,json=pendingEffectiveHeight,proto3" json:"pending_effective_height,omitempty"`
	Provider               string            `protobuf:"bytes,15,opt,name=provider,proto3" json:"provider,omitempty"`
	RepoId                 string            `protobuf:"bytes,16,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
}

func (m *ModelState) Reset()         { *m = ModelState{} }
func (m *ModelState) String() string { return proto.CompactTextString(m) }
func (*ModelState) ProtoMessage()    {}
func (*ModelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2a17f60d08b8e7, []int{0}
}
func (m *ModelState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModelState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ModelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelState.Merge(m, src)
}
func (m *ModelState) XXX_Size() int {
	return m.Size()
}
func (m *ModelState) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelState.DiscardUnknown(m)
}

var xxx_messageInfo_ModelState proto.InternalMessageInfo

func (m *ModelState) GetModelId() []byte {
	if m != nil {
		return m.ModelId
	}
	return nil
}

func (m *ModelState) GetProposerAddress() string {
	if m != nil {
		return m.ProposerAddress
	}
	return ""
}

func (m *ModelState) GetStatus() ModelProfileStatus {
	if m != nil {
		return m.Status
	}
	return ModelProfileStatus_MODEL_PROFILE_STATUS_UNSPECIFIED
}

func (m *ModelState) GetLatestProfileVersion() uint32 {
	if m != nil {
		return m.LatestProfileVersion
	}
	return 0
}

func (m *ModelState) GetStatusSource() ModelStatusSource {
	if m != nil {
		return m.StatusSource
	}
	return ModelStatusSource_MODEL_STATUS_SOURCE_UNSPECIFIED
}

func (m *ModelState) GetRegistrationFeePaid() uint64 {
	if m != nil {
		return m.RegistrationFeePaid
	}
	return 0
}

func (m *ModelState) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *ModelState) GetUpdatedHeight() uint64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func (m *ModelState) GetActiveSupportStake() uint64 {
	if m != nil {
		return m.ActiveSupportStake
	}
	return 0
}

func (m *ModelState) GetActiveSupporterCount() uint32 {
	if m != nil {
		return m.ActiveSupporterCount
	}
	return 0
}

func (m *ModelState) GetSupportMinStake() uint64 {
	if m != nil {
		return m.SupportMinStake
	}
	return 0
}

func (m *ModelState) GetPendingSupportMinStake() uint64 {
	if m != nil {
		return m.PendingSupportMinStake
	}
	return 0
}

func (m *ModelState) GetPendingEffectiveHeight() uint64 {
	if m != nil {
		return m.PendingEffectiveHeight
	}
	return 0
}

func (m *ModelState) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ModelState) GetRepoId() string {
	if m != nil {
		return m.RepoId
	}
	return ""
}

// ProfileState is one registered model profile primary row.
type ProfileState struct {
	ModelId                   []byte                        `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProfileVersion            uint32                        `protobuf:"varint,2,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	ManifestHash              []byte                        `protobuf:"bytes,3,opt,name=manifest_hash,json=manifestHash,proto3" json:"manifest_hash,omitempty"`
	TokenizerHash             []byte                        `protobuf:"bytes,4,opt,name=tokenizer_hash,json=tokenizerHash,proto3" json:"tokenizer_hash,omitempty"`
	RuntimeClass              string                        `protobuf:"bytes,5,opt,name=runtime_class,json=runtimeClass,proto3" json:"runtime_class,omitempty"`
	RequiredTopK              uint32                        `protobuf:"varint,6,opt,name=required_top_k,json=requiredTopK,proto3" json:"required_top_k,omitempty"`
	TaskTypes                 []types.TaskType              `protobuf:"varint,7,rep,packed,name=task_types,json=taskTypes,proto3,enum=shared.v1.TaskType" json:"task_types,omitempty"`
	GenerationType            types.GenerationType          `protobuf:"varint,8,opt,name=generation_type,json=generationType,proto3,enum=shared.v1.GenerationType" json:"generation_type,omitempty"`
	ResourceTier              uint32                        `protobuf:"varint,9,opt,name=resource_tier,json=resourceTier,proto3" json:"resource_tier,omitempty"`
	MinStake                  uint64                        `protobuf:"varint,10,opt,name=min_stake,json=minStake,proto3" json:"min_stake,omitempty"`
	ChallengeOpenWindowBlocks uint64                        `protobuf:"varint,11,opt,name=challenge_open_window_blocks,json=challengeOpenWindowBlocks,proto3" json:"challenge_open_window_blocks,omitempty"`
	VerificationProfile       types.VerificationProfile     `protobuf:"bytes,12,opt,name=verification_profile,json=verificationProfile,proto3" json:"verification_profile"`
	VerificationThresholds    types.VerificationThresholds  `protobuf:"bytes,13,opt,name=verification_thresholds,json=verificationThresholds,proto3" json:"verification_thresholds"`
	BatchVerification         types.BatchVerification       `protobuf:"bytes,14,opt,name=batch_verification,json=batchVerification,proto3" json:"batch_verification"`
	PricingProfile            types.PricingProfile          `protobuf:"bytes,15,opt,name=pricing_profile,json=pricingProfile,proto3" json:"pricing_profile"`
	TimeoutBootstrapProfile   types.TimeoutBootstrapProfile `protobuf:"bytes,16,opt,name=timeout_bootstrap_profile,json=timeoutBootstrapProfile,proto3" json:"timeout_bootstrap_profile"`
	SchemaHash                []byte                        `protobuf:"bytes,17,opt,name=schema_hash,json=schemaHash,proto3" json:"schema_hash,omitempty"`
	Status                    ModelProfileStatus            `protobuf:"varint,18,opt,name=status,proto3,enum=hub.v1.ModelProfileStatus" json:"status,omitempty"`
	StatusSource              ProfileStatusSource           `protobuf:"varint,22,opt,name=status_source,json=statusSource,proto3,enum=hub.v1.ProfileStatusSource" json:"status_source,omitempty"`
	RegistrationFeePaid       uint64                        `protobuf:"varint,23,opt,name=registration_fee_paid,json=registrationFeePaid,proto3" json:"registration_fee_paid,omitempty"`
	PreviousProfileVersion    uint32                        `protobuf:"varint,24,opt,name=previous_profile_version,json=previousProfileVersion,proto3" json:"previous_profile_version,omitempty"`
	ProposerAddress           string                        `protobuf:"bytes,25,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	RegistrationDigest        []byte                        `protobuf:"bytes,26,opt,name=registration_digest,json=registrationDigest,proto3" json:"registration_digest,omitempty"`
	CreatedHeight             uint64                        `protobuf:"varint,27,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	UpdatedHeight             uint64                        `protobuf:"varint,28,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
	// Types that are valid to be assigned to XLastFreezeRiskWindowEvaluated:
	//	*ProfileState_LastFreezeRiskWindowEvaluated
	XLastFreezeRiskWindowEvaluated isProfileState_XLastFreezeRiskWindowEvaluated `protobuf_oneof:"_last_freeze_risk_window_evaluated"`
	RefPrice                       uint64                                        `protobuf:"varint,30,opt,name=ref_price,json=refPrice,proto3" json:"ref_price,omitempty"`
	Source                         types.ProfileSourceRefV1                      `protobuf:"bytes,31,opt,name=source,proto3" json:"source"`
	ToolCallParser                 types.ParserRefV1                             `protobuf:"bytes,32,opt,name=tool_call_parser,json=toolCallParser,proto3" json:"tool_call_parser"`
	ReasoningParser                types.ParserRefV1                             `protobuf:"bytes,33,opt,name=reasoning_parser,json=reasoningParser,proto3" json:"reasoning_parser"`
}

func (m *ProfileState) Reset()         { *m = ProfileState{} }
func (m *ProfileState) String() string { return proto.CompactTextString(m) }
func (*ProfileState) ProtoMessage()    {}
func (*ProfileState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2a17f60d08b8e7, []int{1}
}
func (m *ProfileState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileState.Merge(m, src)
}
func (m *ProfileState) XXX_Size() int {
	return m.Size()
}
func (m *ProfileState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileState.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileState proto.InternalMessageInfo

type isProfileState_XLastFreezeRiskWindowEvaluated interface {
	isProfileState_XLastFreezeRiskWindowEvaluated()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ProfileState_LastFreezeRiskWindowEvaluated struct {
	LastFreezeRiskWindowEvaluated uint64 `protobuf:"varint,29,opt,name=last_freeze_risk_window_evaluated,json=lastFreezeRiskWindowEvaluated,proto3,oneof" json:"last_freeze_risk_window_evaluated,omitempty"`
}

func (*ProfileState_LastFreezeRiskWindowEvaluated) isProfileState_XLastFreezeRiskWindowEvaluated() {}

func (m *ProfileState) GetXLastFreezeRiskWindowEvaluated() isProfileState_XLastFreezeRiskWindowEvaluated {
	if m != nil {
		return m.XLastFreezeRiskWindowEvaluated
	}
	return nil
}

func (m *ProfileState) GetModelId() []byte {
	if m != nil {
		return m.ModelId
	}
	return nil
}

func (m *ProfileState) GetProfileVersion() uint32 {
	if m != nil {
		return m.ProfileVersion
	}
	return 0
}

func (m *ProfileState) GetManifestHash() []byte {
	if m != nil {
		return m.ManifestHash
	}
	return nil
}

func (m *ProfileState) GetTokenizerHash() []byte {
	if m != nil {
		return m.TokenizerHash
	}
	return nil
}

func (m *ProfileState) GetRuntimeClass() string {
	if m != nil {
		return m.RuntimeClass
	}
	return ""
}

func (m *ProfileState) GetRequiredTopK() uint32 {
	if m != nil {
		return m.RequiredTopK
	}
	return 0
}

func (m *ProfileState) GetTaskTypes() []types.TaskType {
	if m != nil {
		return m.TaskTypes
	}
	return nil
}

func (m *ProfileState) GetGenerationType() types.GenerationType {
	if m != nil {
		return m.GenerationType
	}
	return types.GenerationType_GENERATION_TYPE_UNSPECIFIED
}

func (m *ProfileState) GetResourceTier() uint32 {
	if m != nil {
		return m.ResourceTier
	}
	return 0
}

func (m *ProfileState) GetMinStake() uint64 {
	if m != nil {
		return m.MinStake
	}
	return 0
}

func (m *ProfileState) GetChallengeOpenWindowBlocks() uint64 {
	if m != nil {
		return m.ChallengeOpenWindowBlocks
	}
	return 0
}

func (m *ProfileState) GetVerificationProfile() types.VerificationProfile {
	if m != nil {
		return m.VerificationProfile
	}
	return types.VerificationProfile{}
}

func (m *ProfileState) GetVerificationThresholds() types.VerificationThresholds {
	if m != nil {
		return m.VerificationThresholds
	}
	return types.VerificationThresholds{}
}

func (m *ProfileState) GetBatchVerification() types.BatchVerification {
	if m != nil {
		return m.BatchVerification
	}
	return types.BatchVerification{}
}

func (m *ProfileState) GetPricingProfile() types.PricingProfile {
	if m != nil {
		return m.PricingProfile
	}
	return types.PricingProfile{}
}

func (m *ProfileState) GetTimeoutBootstrapProfile() types.TimeoutBootstrapProfile {
	if m != nil {
		return m.TimeoutBootstrapProfile
	}
	return types.TimeoutBootstrapProfile{}
}

func (m *ProfileState) GetSchemaHash() []byte {
	if m != nil {
		return m.SchemaHash
	}
	return nil
}

func (m *ProfileState) GetStatus() ModelProfileStatus {
	if m != nil {
		return m.Status
	}
	return ModelProfileStatus_MODEL_PROFILE_STATUS_UNSPECIFIED
}

func (m *ProfileState) GetStatusSource() ProfileStatusSource {
	if m != nil {
		return m.StatusSource
	}
	return ProfileStatusSource_PROFILE_STATUS_SOURCE_UNSPECIFIED
}

func (m *ProfileState) GetRegistrationFeePaid() uint64 {
	if m != nil {
		return m.RegistrationFeePaid
	}
	return 0
}

func (m *ProfileState) GetPreviousProfileVersion() uint32 {
	if m != nil {
		return m.PreviousProfileVersion
	}
	return 0
}

func (m *ProfileState) GetProposerAddress() string {
	if m != nil {
		return m.ProposerAddress
	}
	return ""
}

func (m *ProfileState) GetRegistrationDigest() []byte {
	if m != nil {
		return m.RegistrationDigest
	}
	return nil
}

func (m *ProfileState) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *ProfileState) GetUpdatedHeight() uint64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func (m *ProfileState) GetLastFreezeRiskWindowEvaluated() uint64 {
	if x, ok := m.GetXLastFreezeRiskWindowEvaluated().(*ProfileState_LastFreezeRiskWindowEvaluated); ok {
		return x.LastFreezeRiskWindowEvaluated
	}
	return 0
}

func (m *ProfileState) GetRefPrice() uint64 {
	if m != nil {
		return m.RefPrice
	}
	return 0
}

func (m *ProfileState) GetSource() types.ProfileSourceRefV1 {
	if m != nil {
		return m.Source
	}
	return types.ProfileSourceRefV1{}
}

func (m *ProfileState) GetToolCallParser() types.ParserRefV1 {
	if m != nil {
		return m.ToolCallParser
	}
	return types.ParserRefV1{}
}

func (m *ProfileState) GetReasoningParser() types.ParserRefV1 {
	if m != nil {
		return m.ReasoningParser
	}
	return types.ParserRefV1{}
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProfileState) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProfileState_LastFreezeRiskWindowEvaluated)(nil),
	}
}

// RegistrationReceipt is the minimal replay locator stored under the
// registration digest key. The remaining receipt facts live in ProfileState.
// RegistrationReceipt defines the RegistrationReceipt wire type.
type RegistrationReceipt struct {
	ModelId        []byte `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProfileVersion uint32 `protobuf:"varint,2,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
}

func (m *RegistrationReceipt) Reset()         { *m = RegistrationReceipt{} }
func (m *RegistrationReceipt) String() string { return proto.CompactTextString(m) }
func (*RegistrationReceipt) ProtoMessage()    {}
func (*RegistrationReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2a17f60d08b8e7, []int{2}
}
func (m *RegistrationReceipt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegistrationReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegistrationReceipt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegistrationReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationReceipt.Merge(m, src)
}
func (m *RegistrationReceipt) XXX_Size() int {
	return m.Size()
}
func (m *RegistrationReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationReceipt proto.InternalMessageInfo

func (m *RegistrationReceipt) GetModelId() []byte {
	if m != nil {
		return m.ModelId
	}
	return nil
}

func (m *RegistrationReceipt) GetProfileVersion() uint32 {
	if m != nil {
		return m.ProfileVersion
	}
	return 0
}

func init() {
	proto.RegisterEnum("hub.v1.ModelProfileStatus", ModelProfileStatus_name, ModelProfileStatus_value)
	proto.RegisterEnum("hub.v1.ModelStatusSource", ModelStatusSource_name, ModelStatusSource_value)
	proto.RegisterEnum("hub.v1.ProfileStatusSource", ProfileStatusSource_name, ProfileStatusSource_value)
	proto.RegisterType((*ModelState)(nil), "hub.v1.ModelState")
	proto.RegisterType((*ProfileState)(nil), "hub.v1.ProfileState")
	proto.RegisterType((*RegistrationReceipt)(nil), "hub.v1.RegistrationReceipt")
}

func init() { proto.RegisterFile("hub/v1/model_profile_state.proto", fileDescriptor_ef2a17f60d08b8e7) }

var fileDescriptor_ef2a17f60d08b8e7 = []byte{
	// 1433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x53, 0x23, 0x45,
	0x14, 0x67, 0x20, 0xfc, 0x6b, 0x48, 0x08, 0x0d, 0xc2, 0x00, 0x4b, 0x08, 0x59, 0x28, 0x59, 0x2c,
	0xc1, 0x8d, 0x5a, 0xa5, 0x65, 0xd5, 0x2a, 0x09, 0xc3, 0x1f, 0x5d, 0x08, 0x4e, 0x02, 0x5b, 0xee,
	0xa5, 0x1d, 0x66, 0x5e, 0x92, 0xa9, 0x24, 0xd3, 0x63, 0xf7, 0x24, 0xeb, 0xee, 0x27, 0xf0, 0xe8,
	0x97, 0xf0, 0x03, 0x58, 0xe5, 0x87, 0xd8, 0xe3, 0x96, 0x27, 0x4f, 0x96, 0xb5, 0x7b, 0xf2, 0xe4,
	0xc1, 0x8b, 0x47, 0xab, 0xbb, 0x67, 0xc2, 0x0c, 0x84, 0x92, 0xad, 0xf2, 0xc6, 0xbc, 0xdf, 0xef,
	0xf7, 0xba, 0x5f, 0xf7, 0xef, 0xf5, 0x23, 0x28, 0xdf, 0xec, 0x5e, 0xee, 0xf6, 0x1e, 0xee, 0x76,
	0xa8, 0x03, 0x6d, 0xe2, 0x33, 0x5a, 0x77, 0xdb, 0x40, 0x78, 0x60, 0x05, 0xb0, 0xe3, 0x33, 0x1a,
	0x50, 0x3c, 0xd6, 0xec, 0x5e, 0xee, 0xf4, 0x1e, 0x2e, 0x2f, 0xd9, 0x94, 0x77, 0x28, 0x27, 0x32,
	0xba, 0xab, 0x3e, 0x14, 0x65, 0x79, 0xbe, 0x41, 0x1b, 0x54, 0xc5, 0xc5, 0x5f, 0x61, 0x74, 0x95,
	0x37, 0x2d, 0x06, 0xce, 0x8d, 0xec, 0x37, 0x61, 0x06, 0x3c, 0x20, 0xe0, 0xd9, 0xd4, 0x71, 0xbd,
	0x86, 0x82, 0x0b, 0xff, 0x8c, 0x22, 0x74, 0x22, 0x64, 0x55, 0xb1, 0x17, 0xbc, 0x86, 0x26, 0x54,
	0x12, 0xd7, 0xd1, 0xb5, 0xbc, 0xb6, 0x35, 0x5d, 0x4a, 0xbd, 0xfc, 0x5b, 0x1f, 0x36, 0xc7, 0x65,
	0xf4, 0xd8, 0xc1, 0x65, 0x94, 0xf5, 0x19, 0xf5, 0x29, 0x07, 0x46, 0x2c, 0xc7, 0x61, 0xc0, 0xb9,
	0x3e, 0x9c, 0xd7, 0xb6, 0x26, 0x4b, 0xfa, 0xaf, 0xbf, 0xbc, 0x3f, 0x1f, 0xee, 0x77, 0x4f, 0x21,
	0xd5, 0x80, 0xb9, 0x5e, 0xc3, 0x9c, 0x89, 0x14, 0x61, 0x18, 0x17, 0xd1, 0x98, 0x28, 0xbd, 0xcb,
	0xf5, 0x91, 0xbc, 0xb6, 0x95, 0x29, 0x2e, 0xef, 0xa8, 0xe2, 0x77, 0xe4, 0x4e, 0xce, 0xd4, 0xfe,
	0xab, 0x92, 0x61, 0x86, 0x4c, 0xfc, 0x11, 0x5a, 0x68, 0x5b, 0x81, 0xa8, 0x20, 0x3a, 0xbd, 0x1e,
	0x30, 0xee, 0x52, 0x4f, 0x1f, 0xcd, 0x6b, 0x5b, 0x69, 0x73, 0x5e, 0xa1, 0xa1, 0xf8, 0x42, 0x61,
	0xf8, 0x11, 0x4a, 0x2b, 0x3d, 0xe1, 0xb4, 0xcb, 0x6c, 0xd0, 0xc7, 0xe4, 0x82, 0x4b, 0x89, 0x05,
	0xd5, 0x4a, 0x55, 0x49, 0x30, 0xa7, 0x79, 0xec, 0x0b, 0x17, 0xd1, 0x3b, 0x0c, 0x1a, 0x2e, 0x0f,
	0x98, 0x15, 0xb8, 0xd4, 0x23, 0x75, 0x00, 0xe2, 0x5b, 0xae, 0xa3, 0x8f, 0xe7, 0xb5, 0xad, 0x94,
	0x39, 0x17, 0x07, 0x0f, 0x00, 0xce, 0x2c, 0xd7, 0xc1, 0x9b, 0x28, 0x63, 0x33, 0xb0, 0x02, 0x70,
	0x48, 0x13, 0xdc, 0x46, 0x33, 0xd0, 0x27, 0x24, 0x39, 0x1d, 0x46, 0x8f, 0x64, 0x50, 0xd0, 0xba,
	0xbe, 0x13, 0xa7, 0x4d, 0x2a, 0x5a, 0x18, 0x0d, 0x69, 0x1f, 0xa0, 0x79, 0xcb, 0x0e, 0xdc, 0x1e,
	0x10, 0xde, 0xf5, 0x7d, 0xca, 0x02, 0xe1, 0x9a, 0x16, 0xe8, 0x48, 0x92, 0xb1, 0xc2, 0xaa, 0x0a,
	0xaa, 0x0a, 0x44, 0x9c, 0x54, 0x52, 0x01, 0x8c, 0xd8, 0xb4, 0xeb, 0x05, 0xfa, 0x94, 0x3a, 0xa9,
	0x84, 0x06, 0x58, 0x59, 0x60, 0x78, 0x1b, 0xcd, 0x46, 0x0b, 0x74, 0x5c, 0x2f, 0x5c, 0x64, 0x5a,
	0x2e, 0x32, 0x13, 0x02, 0x27, 0xae, 0xa7, 0x56, 0xf8, 0x14, 0x2d, 0xf9, 0xe0, 0x09, 0x17, 0x91,
	0x9b, 0x9a, 0xb4, 0xd4, 0x2c, 0x84, 0x84, 0xea, 0x35, 0xe9, 0x27, 0x48, 0x8f, 0xa4, 0x50, 0xaf,
	0x83, 0xda, 0x67, 0x58, 0x7f, 0x26, 0xa1, 0x34, 0x22, 0x38, 0x3c, 0x88, 0x65, 0x34, 0xe1, 0x33,
	0xda, 0x73, 0x1d, 0x60, 0xfa, 0x8c, 0x70, 0x9c, 0xd9, 0xff, 0xc6, 0x8b, 0x68, 0x9c, 0x81, 0x4f,
	0x85, 0x6b, 0xb3, 0x12, 0x1a, 0x13, 0x9f, 0xc7, 0xce, 0x97, 0xa9, 0x89, 0x54, 0x76, 0x34, 0xaa,
	0xb8, 0xef, 0x1c, 0x79, 0x1a, 0x85, 0x3f, 0xd3, 0x68, 0x3a, 0xe6, 0xb5, 0x3b, 0x98, 0xff, 0x5d,
	0x34, 0x73, 0xdd, 0x7c, 0xc3, 0xf2, 0x48, 0x33, 0x7e, 0xd2, 0x76, 0x0f, 0x50, 0xba, 0x63, 0x79,
	0x6e, 0x5d, 0xd8, 0xb5, 0x69, 0xf1, 0xa6, 0xf4, 0x79, 0x94, 0x6e, 0x3a, 0x82, 0x8e, 0x2c, 0xde,
	0xc4, 0xef, 0xa1, 0x4c, 0x40, 0x5b, 0xe0, 0xb9, 0x2f, 0x80, 0x29, 0x6e, 0x2a, 0xc6, 0x4d, 0xf7,
	0x31, 0x49, 0xbe, 0x8f, 0xd2, 0xac, 0xeb, 0x05, 0x6e, 0x07, 0x88, 0xdd, 0xb6, 0x38, 0x97, 0xde,
	0x9f, 0x34, 0xa7, 0xc3, 0x60, 0x59, 0xc4, 0xf0, 0x06, 0xca, 0x30, 0xf8, 0xae, 0xeb, 0x32, 0x70,
	0x48, 0x40, 0x7d, 0xd2, 0x92, 0xa6, 0x4f, 0x9b, 0xd3, 0x51, 0xb4, 0x46, 0xfd, 0xaf, 0x70, 0x11,
	0xa1, 0xc0, 0xe2, 0x2d, 0x12, 0x3c, 0xf7, 0x81, 0xeb, 0xe3, 0xf9, 0x91, 0xad, 0x4c, 0x71, 0x6e,
	0x47, 0x3d, 0x16, 0xa2, 0x33, 0x6a, 0x16, 0x6f, 0xd5, 0x9e, 0xfb, 0x60, 0x4e, 0x06, 0xe1, 0x5f,
	0x1c, 0x97, 0xd0, 0x4c, 0x03, 0x3c, 0x08, 0x7b, 0x41, 0x28, 0xa5, 0xb5, 0x45, 0x3f, 0x5d, 0x09,
	0x0f, 0xfb, 0x0c, 0x29, 0xcf, 0x34, 0x12, 0xdf, 0xb2, 0x04, 0x50, 0xcd, 0x48, 0x02, 0x17, 0x98,
	0x74, 0xbd, 0xdc, 0x9c, 0x0a, 0xd6, 0x5c, 0x60, 0x78, 0x05, 0x4d, 0x5e, 0x19, 0x4a, 0x39, 0x7d,
	0xa2, 0x13, 0x59, 0xe8, 0x73, 0x74, 0xcf, 0x6e, 0x5a, 0xed, 0x36, 0x78, 0x0d, 0x20, 0xd4, 0x07,
	0x8f, 0x3c, 0x73, 0x3d, 0x87, 0x3e, 0x23, 0x97, 0x6d, 0x6a, 0xb7, 0xb8, 0x74, 0x79, 0xca, 0x5c,
	0xea, 0x73, 0x2a, 0x3e, 0x78, 0x4f, 0x24, 0xa3, 0x24, 0x09, 0xf8, 0x09, 0x9a, 0xef, 0x01, 0x73,
	0xeb, 0xae, 0xad, 0x0a, 0x09, 0x2f, 0x4f, 0xba, 0x7d, 0xaa, 0x98, 0x8b, 0xd5, 0x72, 0x11, 0xa3,
	0x85, 0x56, 0x29, 0xa5, 0x5e, 0xfe, 0xbe, 0x36, 0x64, 0xce, 0xf5, 0x6e, 0x42, 0xf8, 0x5b, 0xb4,
	0x98, 0x48, 0x1c, 0x34, 0x19, 0xf0, 0x26, 0x6d, 0x3b, 0x5c, 0x76, 0xc5, 0x54, 0x71, 0xfd, 0x96,
	0xdc, 0xb5, 0x3e, 0x31, 0x4c, 0xbf, 0xd0, 0x1b, 0x88, 0xe2, 0xaf, 0x11, 0xbe, 0xb4, 0x02, 0xbb,
	0x49, 0xe2, 0xb8, 0x6c, 0x9c, 0xa9, 0xe2, 0xbd, 0x58, 0xf2, 0x92, 0x20, 0xc5, 0x57, 0x08, 0xf3,
	0xce, 0x5e, 0x5e, 0x07, 0xf0, 0x91, 0x30, 0xb5, 0x6b, 0x8b, 0x8e, 0x8c, 0x0e, 0x62, 0x46, 0xe6,
	0x8b, 0x5f, 0xea, 0x99, 0x62, 0x24, 0xcf, 0x20, 0xe3, 0x27, 0xa2, 0xd8, 0x41, 0x4b, 0xc2, 0x85,
	0xb4, 0x1b, 0x90, 0x4b, 0x4a, 0x03, 0xf1, 0x2e, 0xfa, 0xfd, 0x9c, 0x59, 0x99, 0xb3, 0x10, 0x77,
	0x98, 0xe2, 0x96, 0x22, 0x6a, 0x32, 0xf9, 0x62, 0x30, 0x18, 0xc6, 0x9b, 0x68, 0x8a, 0xdb, 0x4d,
	0xe8, 0x58, 0xaa, 0x5b, 0x66, 0x63, 0xdd, 0x82, 0x14, 0x20, 0x5b, 0xe5, 0x6a, 0xc6, 0xe0, 0x3b,
	0xcf, 0x98, 0x2f, 0xae, 0x4f, 0x8b, 0x05, 0x29, 0x5d, 0x89, 0xa4, 0x09, 0xd5, 0xdb, 0xcd, 0x8b,
	0xc5, 0xdb, 0xe7, 0x85, 0x78, 0x12, 0x19, 0xf4, 0x5c, 0xda, 0xe5, 0x37, 0x66, 0x9b, 0x2e, 0x9b,
	0x63, 0x21, 0xc2, 0xaf, 0x4d, 0xb7, 0x41, 0xc3, 0x78, 0xe9, 0x6d, 0x87, 0xf1, 0xc7, 0x28, 0xb1,
	0x2b, 0xe2, 0xb8, 0x0d, 0xe0, 0x81, 0xbe, 0x1c, 0x3b, 0x57, 0x1c, 0x27, 0xec, 0x4b, 0x7c, 0xc0,
	0x94, 0x5b, 0xb9, 0xdb, 0x94, 0xbb, 0x37, 0x68, 0xca, 0x9d, 0xa0, 0xf5, 0xb6, 0xc5, 0x03, 0x52,
	0x67, 0x00, 0x2f, 0x80, 0x30, 0x97, 0xb7, 0xa2, 0xae, 0x86, 0x9e, 0xd5, 0xee, 0x0a, 0xaa, 0xbe,
	0x2a, 0x94, 0x47, 0x43, 0xe6, 0xaa, 0xa0, 0x1e, 0x48, 0xa6, 0xe9, 0xf2, 0x96, 0xea, 0x6d, 0x23,
	0xa2, 0xfd, 0xa0, 0x69, 0xe2, 0xfd, 0x60, 0x50, 0x27, 0xc2, 0x9f, 0xa0, 0xe7, 0xd4, 0xfb, 0xc1,
	0xa0, 0x2e, 0x5c, 0x0c, 0xf8, 0x33, 0x34, 0x16, 0x5e, 0xef, 0x9a, 0xf4, 0xe4, 0x6a, 0xc2, 0xe7,
	0xea, 0x86, 0xd5, 0xdd, 0x42, 0xfd, 0xe2, 0x61, 0x68, 0xc7, 0x50, 0x82, 0x0f, 0x50, 0x36, 0xa0,
	0xb4, 0x4d, 0x6c, 0xab, 0xdd, 0x26, 0xbe, 0xc5, 0x38, 0x30, 0x3d, 0x2f, 0xd3, 0x2c, 0xc4, 0xd3,
	0x48, 0x20, 0xae, 0xcf, 0x08, 0x55, 0xd9, 0x6a, 0xb7, 0x15, 0x84, 0x0f, 0x51, 0x96, 0x81, 0xc5,
	0xa9, 0x27, 0xfb, 0x4e, 0xe5, 0x59, 0xbf, 0x43, 0x9e, 0x99, 0xbe, 0x4a, 0x61, 0xa5, 0x0d, 0x54,
	0x20, 0xff, 0x79, 0x74, 0x05, 0x82, 0xe6, 0xcc, 0xd8, 0x1d, 0x9a, 0x60, 0x83, 0xeb, 0x07, 0xff,
	0xdf, 0xc4, 0xdb, 0xfe, 0x4b, 0x43, 0xf8, 0x66, 0x67, 0xe1, 0x0d, 0x94, 0x3f, 0xa9, 0xec, 0x1b,
	0x8f, 0xc9, 0x99, 0x59, 0x39, 0x38, 0x7e, 0x6c, 0x90, 0x6a, 0x6d, 0xaf, 0x76, 0x5e, 0x25, 0xe7,
	0xa7, 0xd5, 0x33, 0xa3, 0x7c, 0x7c, 0x70, 0x6c, 0xec, 0x67, 0x87, 0xf0, 0x7d, 0xb4, 0x36, 0x90,
	0x65, 0x1a, 0x87, 0xc7, 0xd5, 0x9a, 0x61, 0x1a, 0xfb, 0x59, 0x0d, 0xaf, 0xa1, 0x95, 0x81, 0xa4,
	0xbd, 0x72, 0xed, 0xf8, 0xc2, 0xc8, 0x0e, 0xdf, 0x4a, 0x38, 0x30, 0x2b, 0x4f, 0x8d, 0xd3, 0xec,
	0x08, 0x7e, 0x80, 0x36, 0x07, 0x12, 0x8c, 0x13, 0xc3, 0x3c, 0x34, 0x4e, 0xcb, 0xdf, 0x44, 0xd4,
	0x14, 0x5e, 0x47, 0xab, 0x03, 0xa9, 0xfb, 0xc6, 0x63, 0xb1, 0xa3, 0xfd, 0xec, 0xe8, 0xf6, 0x4f,
	0x1a, 0x9a, 0xbd, 0xf1, 0xef, 0xe3, 0x55, 0x29, 0xa1, 0xa0, 0x5a, 0x39, 0x37, 0xcb, 0xc6, 0xb5,
	0x7a, 0xfb, 0xa7, 0x92, 0x24, 0xed, 0x9d, 0xd7, 0x2a, 0xa4, 0x7a, 0x7e, 0x76, 0x56, 0x31, 0x6b,
	0x59, 0x0d, 0x17, 0x50, 0x6e, 0x10, 0xeb, 0xb0, 0x72, 0x61, 0x98, 0xa7, 0x7b, 0xa7, 0x65, 0x51,
	0x73, 0x7f, 0x9f, 0x49, 0x4e, 0xbf, 0xa2, 0xec, 0xc8, 0xf6, 0xcf, 0x1a, 0x9a, 0x1b, 0xf0, 0x70,
	0xe1, 0x4d, 0xb4, 0x7e, 0xad, 0xb8, 0xdb, 0xf6, 0x3a, 0x98, 0x96, 0xd8, 0xc7, 0x7d, 0xb4, 0x36,
	0x98, 0x15, 0xdb, 0x49, 0x21, 0x35, 0xa1, 0x65, 0xb5, 0xed, 0xc2, 0x60, 0x62, 0xbc, 0xf8, 0xd2,
	0xa3, 0x97, 0xaf, 0x73, 0xda, 0xab, 0xd7, 0x39, 0xed, 0x8f, 0xd7, 0x39, 0xed, 0xc7, 0x37, 0xb9,
	0xa1, 0x57, 0x6f, 0x72, 0x43, 0xbf, 0xbd, 0xc9, 0x0d, 0x3d, 0xdd, 0x68, 0xb8, 0x81, 0x78, 0x8d,
	0x6d, 0xda, 0xd9, 0xad, 0xb1, 0xae, 0x1c, 0xee, 0xbb, 0x1e, 0x75, 0x60, 0xf7, 0xfb, 0x5d, 0xf1,
	0x1b, 0x4b, 0xfe, 0x3b, 0x73, 0x39, 0x26, 0x7f, 0xdc, 0x7c, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x61, 0x71, 0x90, 0x58, 0x77, 0x0d, 0x00, 0x00,
}

func (m *ModelState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModelState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ModelState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RepoId) > 0 {
		i -= len(m.RepoId)
		copy(dAtA[i:], m.RepoId)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.RepoId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x7a
	}
	if m.PendingEffectiveHeight != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.PendingEffectiveHeight))
		i--
		dAtA[i] = 0x70
	}
	if m.PendingSupportMinStake != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.PendingSupportMinStake))
		i--
		dAtA[i] = 0x68
	}
	if m.SupportMinStake != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.SupportMinStake))
		i--
		dAtA[i] = 0x60
	}
	if m.ActiveSupporterCount != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.ActiveSupporterCount))
		i--
		dAtA[i] = 0x58
	}
	if m.ActiveSupportStake != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.ActiveSupportStake))
		i--
		dAtA[i] = 0x50
	}
	if m.UpdatedHeight != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.RegistrationFeePaid != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.RegistrationFeePaid))
		i--
		dAtA[i] = 0x38
	}
	if m.StatusSource != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.StatusSource))
		i--
		dAtA[i] = 0x30
	}
	if m.LatestProfileVersion != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.LatestProfileVersion))
		i--
		dAtA[i] = 0x28
	}
	if m.Status != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProposerAddress) > 0 {
		i -= len(m.ProposerAddress)
		copy(dAtA[i:], m.ProposerAddress)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.ProposerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProfileState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ReasoningParser.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x8a
	{
		size, err := m.ToolCallParser.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x82
	{
		size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xfa
	if m.RefPrice != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.RefPrice))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	if m.XLastFreezeRiskWindowEvaluated != nil {
		{
			size := m.XLastFreezeRiskWindowEvaluated.Size()
			i -= size
			if _, err := m.XLastFreezeRiskWindowEvaluated.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.UpdatedHeight != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if len(m.RegistrationDigest) > 0 {
		i -= len(m.RegistrationDigest)
		copy(dAtA[i:], m.RegistrationDigest)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.RegistrationDigest)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd2
	}
	if len(m.ProposerAddress) > 0 {
		i -= len(m.ProposerAddress)
		copy(dAtA[i:], m.ProposerAddress)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.ProposerAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if m.PreviousProfileVersion != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.PreviousProfileVersion))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if m.RegistrationFeePaid != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.RegistrationFeePaid))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.StatusSource != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.StatusSource))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.Status != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.SchemaHash) > 0 {
		i -= len(m.SchemaHash)
		copy(dAtA[i:], m.SchemaHash)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.SchemaHash)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	{
		size, err := m.TimeoutBootstrapProfile.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	{
		size, err := m.PricingProfile.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x7a
	{
		size, err := m.BatchVerification.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size, err := m.VerificationThresholds.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.VerificationProfile.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintModelProfileState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.ChallengeOpenWindowBlocks != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.ChallengeOpenWindowBlocks))
		i--
		dAtA[i] = 0x58
	}
	if m.MinStake != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.MinStake))
		i--
		dAtA[i] = 0x50
	}
	if m.ResourceTier != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.ResourceTier))
		i--
		dAtA[i] = 0x48
	}
	if m.GenerationType != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.GenerationType))
		i--
		dAtA[i] = 0x40
	}
	if len(m.TaskTypes) > 0 {
		dAtA10 := make([]byte, len(m.TaskTypes)*10)
		var j9 int
		for _, num := range m.TaskTypes {
			for num >= 1<<7 {
				dAtA10[j9] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j9++
			}
			dAtA10[j9] = uint8(num)
			j9++
		}
		i -= j9
		copy(dAtA[i:], dAtA10[:j9])
		i = encodeVarintModelProfileState(dAtA, i, uint64(j9))
		i--
		dAtA[i] = 0x3a
	}
	if m.RequiredTopK != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.RequiredTopK))
		i--
		dAtA[i] = 0x30
	}
	if len(m.RuntimeClass) > 0 {
		i -= len(m.RuntimeClass)
		copy(dAtA[i:], m.RuntimeClass)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.RuntimeClass)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TokenizerHash) > 0 {
		i -= len(m.TokenizerHash)
		copy(dAtA[i:], m.TokenizerHash)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.TokenizerHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ManifestHash) > 0 {
		i -= len(m.ManifestHash)
		copy(dAtA[i:], m.ManifestHash)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.ManifestHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProfileVersion != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.ProfileVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProfileState_LastFreezeRiskWindowEvaluated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileState_LastFreezeRiskWindowEvaluated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintModelProfileState(dAtA, i, uint64(m.LastFreezeRiskWindowEvaluated))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xe8
	return len(dAtA) - i, nil
}
func (m *RegistrationReceipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegistrationReceipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegistrationReceipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProfileVersion != 0 {
		i = encodeVarintModelProfileState(dAtA, i, uint64(m.ProfileVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintModelProfileState(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintModelProfileState(dAtA []byte, offset int, v uint64) int {
	offset -= sovModelProfileState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ModelState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	l = len(m.ProposerAddress)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovModelProfileState(uint64(m.Status))
	}
	if m.LatestProfileVersion != 0 {
		n += 1 + sovModelProfileState(uint64(m.LatestProfileVersion))
	}
	if m.StatusSource != 0 {
		n += 1 + sovModelProfileState(uint64(m.StatusSource))
	}
	if m.RegistrationFeePaid != 0 {
		n += 1 + sovModelProfileState(uint64(m.RegistrationFeePaid))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovModelProfileState(uint64(m.CreatedHeight))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovModelProfileState(uint64(m.UpdatedHeight))
	}
	if m.ActiveSupportStake != 0 {
		n += 1 + sovModelProfileState(uint64(m.ActiveSupportStake))
	}
	if m.ActiveSupporterCount != 0 {
		n += 1 + sovModelProfileState(uint64(m.ActiveSupporterCount))
	}
	if m.SupportMinStake != 0 {
		n += 1 + sovModelProfileState(uint64(m.SupportMinStake))
	}
	if m.PendingSupportMinStake != 0 {
		n += 1 + sovModelProfileState(uint64(m.PendingSupportMinStake))
	}
	if m.PendingEffectiveHeight != 0 {
		n += 1 + sovModelProfileState(uint64(m.PendingEffectiveHeight))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	l = len(m.RepoId)
	if l > 0 {
		n += 2 + l + sovModelProfileState(uint64(l))
	}
	return n
}

func (m *ProfileState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	if m.ProfileVersion != 0 {
		n += 1 + sovModelProfileState(uint64(m.ProfileVersion))
	}
	l = len(m.ManifestHash)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	l = len(m.TokenizerHash)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	l = len(m.RuntimeClass)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	if m.RequiredTopK != 0 {
		n += 1 + sovModelProfileState(uint64(m.RequiredTopK))
	}
	if len(m.TaskTypes) > 0 {
		l = 0
		for _, e := range m.TaskTypes {
			l += sovModelProfileState(uint64(e))
		}
		n += 1 + sovModelProfileState(uint64(l)) + l
	}
	if m.GenerationType != 0 {
		n += 1 + sovModelProfileState(uint64(m.GenerationType))
	}
	if m.ResourceTier != 0 {
		n += 1 + sovModelProfileState(uint64(m.ResourceTier))
	}
	if m.MinStake != 0 {
		n += 1 + sovModelProfileState(uint64(m.MinStake))
	}
	if m.ChallengeOpenWindowBlocks != 0 {
		n += 1 + sovModelProfileState(uint64(m.ChallengeOpenWindowBlocks))
	}
	l = m.VerificationProfile.Size()
	n += 1 + l + sovModelProfileState(uint64(l))
	l = m.VerificationThresholds.Size()
	n += 1 + l + sovModelProfileState(uint64(l))
	l = m.BatchVerification.Size()
	n += 1 + l + sovModelProfileState(uint64(l))
	l = m.PricingProfile.Size()
	n += 1 + l + sovModelProfileState(uint64(l))
	l = m.TimeoutBootstrapProfile.Size()
	n += 2 + l + sovModelProfileState(uint64(l))
	l = len(m.SchemaHash)
	if l > 0 {
		n += 2 + l + sovModelProfileState(uint64(l))
	}
	if m.Status != 0 {
		n += 2 + sovModelProfileState(uint64(m.Status))
	}
	if m.StatusSource != 0 {
		n += 2 + sovModelProfileState(uint64(m.StatusSource))
	}
	if m.RegistrationFeePaid != 0 {
		n += 2 + sovModelProfileState(uint64(m.RegistrationFeePaid))
	}
	if m.PreviousProfileVersion != 0 {
		n += 2 + sovModelProfileState(uint64(m.PreviousProfileVersion))
	}
	l = len(m.ProposerAddress)
	if l > 0 {
		n += 2 + l + sovModelProfileState(uint64(l))
	}
	l = len(m.RegistrationDigest)
	if l > 0 {
		n += 2 + l + sovModelProfileState(uint64(l))
	}
	if m.CreatedHeight != 0 {
		n += 2 + sovModelProfileState(uint64(m.CreatedHeight))
	}
	if m.UpdatedHeight != 0 {
		n += 2 + sovModelProfileState(uint64(m.UpdatedHeight))
	}
	if m.XLastFreezeRiskWindowEvaluated != nil {
		n += m.XLastFreezeRiskWindowEvaluated.Size()
	}
	if m.RefPrice != 0 {
		n += 2 + sovModelProfileState(uint64(m.RefPrice))
	}
	l = m.Source.Size()
	n += 2 + l + sovModelProfileState(uint64(l))
	l = m.ToolCallParser.Size()
	n += 2 + l + sovModelProfileState(uint64(l))
	l = m.ReasoningParser.Size()
	n += 2 + l + sovModelProfileState(uint64(l))
	return n
}

func (m *ProfileState_LastFreezeRiskWindowEvaluated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2 + sovModelProfileState(uint64(m.LastFreezeRiskWindowEvaluated))
	return n
}
func (m *RegistrationReceipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovModelProfileState(uint64(l))
	}
	if m.ProfileVersion != 0 {
		n += 1 + sovModelProfileState(uint64(m.ProfileVersion))
	}
	return n
}

func sovModelProfileState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModelProfileState(x uint64) (n int) {
	return sovModelProfileState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ModelState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModelProfileState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModelState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModelState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = append(m.ModelId[:0], dAtA[iNdEx:postIndex]...)
			if m.ModelId == nil {
				m.ModelId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ModelProfileStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestProfileVersion", wireType)
			}
			m.LatestProfileVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestProfileVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusSource", wireType)
			}
			m.StatusSource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusSource |= ModelStatusSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationFeePaid", wireType)
			}
			m.RegistrationFeePaid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationFeePaid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveSupportStake", wireType)
			}
			m.ActiveSupportStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveSupportStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveSupporterCount", wireType)
			}
			m.ActiveSupporterCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveSupporterCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportMinStake", wireType)
			}
			m.SupportMinStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SupportMinStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingSupportMinStake", wireType)
			}
			m.PendingSupportMinStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingSupportMinStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingEffectiveHeight", wireType)
			}
			m.PendingEffectiveHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingEffectiveHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepoId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepoId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModelProfileState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProfileState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModelProfileState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = append(m.ModelId[:0], dAtA[iNdEx:postIndex]...)
			if m.ModelId == nil {
				m.ModelId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfileVersion", wireType)
			}
			m.ProfileVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProfileVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ManifestHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ManifestHash = append(m.ManifestHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ManifestHash == nil {
				m.ManifestHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenizerHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenizerHash = append(m.TokenizerHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TokenizerHash == nil {
				m.TokenizerHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeClass", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuntimeClass = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredTopK", wireType)
			}
			m.RequiredTopK = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequiredTopK |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType == 0 {
				var v types.TaskType
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowModelProfileState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= types.TaskType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TaskTypes = append(m.TaskTypes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowModelProfileState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthModelProfileState
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthModelProfileState
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.TaskTypes) == 0 {
					m.TaskTypes = make([]types.TaskType, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v types.TaskType
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowModelProfileState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= types.TaskType(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TaskTypes = append(m.TaskTypes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskTypes", wireType)
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenerationType", wireType)
			}
			m.GenerationType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenerationType |= types.GenerationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceTier", wireType)
			}
			m.ResourceTier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResourceTier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStake", wireType)
			}
			m.MinStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeOpenWindowBlocks", wireType)
			}
			m.ChallengeOpenWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeOpenWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationProfile", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerificationProfile.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationThresholds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerificationThresholds.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchVerification", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BatchVerification.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricingProfile", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PricingProfile.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutBootstrapProfile", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutBootstrapProfile.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SchemaHash = append(m.SchemaHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SchemaHash == nil {
				m.SchemaHash = []byte{}
			}
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ModelProfileStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusSource", wireType)
			}
			m.StatusSource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusSource |= ProfileStatusSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationFeePaid", wireType)
			}
			m.RegistrationFeePaid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationFeePaid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousProfileVersion", wireType)
			}
			m.PreviousProfileVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousProfileVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationDigest = append(m.RegistrationDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.RegistrationDigest == nil {
				m.RegistrationDigest = []byte{}
			}
			iNdEx = postIndex
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 29:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastFreezeRiskWindowEvaluated", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XLastFreezeRiskWindowEvaluated = &ProfileState_LastFreezeRiskWindowEvaluated{v}
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefPrice", wireType)
			}
			m.RefPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RefPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToolCallParser", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ToolCallParser.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 33:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasoningParser", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReasoningParser.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModelProfileState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegistrationReceipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModelProfileState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegistrationReceipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegistrationReceipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthModelProfileState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = append(m.ModelId[:0], dAtA[iNdEx:postIndex]...)
			if m.ModelId == nil {
				m.ModelId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfileVersion", wireType)
			}
			m.ProfileVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProfileVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModelProfileState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModelProfileState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModelProfileState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModelProfileState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModelProfileState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModelProfileState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModelProfileState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModelProfileState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModelProfileState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModelProfileState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModelProfileState = fmt.Errorf("proto: unexpected end of group")
)
