// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hub/v1/msg_identity.proto

package types

import (
	fmt "fmt"
	types "github.com/TrueOpen/node/x/shared/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRotateServiceKey replaces the current service key binding of one stable operator (10.0c1).
type MsgRotateServiceKey struct {
	ParticipantType                          types.ParticipantType `protobuf:"varint,1,opt,name=participant_type,json=participantType,proto3,enum=shared.v1.ParticipantType" json:"participant_type,omitempty"`
	NewServicePubkey                         []byte                `protobuf:"bytes,2,opt,name=new_service_pubkey,json=newServicePubkey,proto3" json:"new_service_pubkey,omitempty"`
	ExpectedCurrentServiceAuthorizationNonce uint64                `protobuf:"varint,3,opt,name=expected_current_service_authorization_nonce,json=expectedCurrentServiceAuthorizationNonce,proto3" json:"expected_current_service_authorization_nonce,omitempty"`
	NewServiceKeyProof                       []byte                `protobuf:"bytes,4,opt,name=new_service_key_proof,json=newServiceKeyProof,proto3" json:"new_service_key_proof,omitempty"`
	OperatorAddress                          string                `protobuf:"bytes,5,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
}

func (m *MsgRotateServiceKey) Reset()         { *m = MsgRotateServiceKey{} }
func (m *MsgRotateServiceKey) String() string { return proto.CompactTextString(m) }
func (*MsgRotateServiceKey) ProtoMessage()    {}
func (*MsgRotateServiceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_088b1815194819e9, []int{0}
}
func (m *MsgRotateServiceKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRotateServiceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRotateServiceKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRotateServiceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRotateServiceKey.Merge(m, src)
}
func (m *MsgRotateServiceKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRotateServiceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRotateServiceKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRotateServiceKey proto.InternalMessageInfo

func (m *MsgRotateServiceKey) GetParticipantType() types.ParticipantType {
	if m != nil {
		return m.ParticipantType
	}
	return types.ParticipantType_PARTICIPANT_TYPE_UNSPECIFIED
}

func (m *MsgRotateServiceKey) GetNewServicePubkey() []byte {
	if m != nil {
		return m.NewServicePubkey
	}
	return nil
}

func (m *MsgRotateServiceKey) GetExpectedCurrentServiceAuthorizationNonce() uint64 {
	if m != nil {
		return m.ExpectedCurrentServiceAuthorizationNonce
	}
	return 0
}

func (m *MsgRotateServiceKey) GetNewServiceKeyProof() []byte {
	if m != nil {
		return m.NewServiceKeyProof
	}
	return nil
}

func (m *MsgRotateServiceKey) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

// MsgRotateServiceKeyResponse returns the new service address and authorization nonce.
type MsgRotateServiceKeyResponse struct {
	OperatorAddress   string                 `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	NewServiceAddress string                 `protobuf:"bytes,2,opt,name=new_service_address,json=newServiceAddress,proto3" json:"new_service_address,omitempty"`
	NewNonce          uint64                 `protobuf:"varint,3,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	Status            types.MutationStatusV1 `protobuf:"varint,4,opt,name=status,proto3,enum=shared.v1.MutationStatusV1" json:"status,omitempty"`
}

func (m *MsgRotateServiceKeyResponse) Reset()         { *m = MsgRotateServiceKeyResponse{} }
func (m *MsgRotateServiceKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRotateServiceKeyResponse) ProtoMessage()    {}
func (*MsgRotateServiceKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_088b1815194819e9, []int{1}
}
func (m *MsgRotateServiceKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRotateServiceKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRotateServiceKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRotateServiceKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRotateServiceKeyResponse.Merge(m, src)
}
func (m *MsgRotateServiceKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRotateServiceKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRotateServiceKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRotateServiceKeyResponse proto.InternalMessageInfo

func (m *MsgRotateServiceKeyResponse) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *MsgRotateServiceKeyResponse) GetNewServiceAddress() string {
	if m != nil {
		return m.NewServiceAddress
	}
	return ""
}

func (m *MsgRotateServiceKeyResponse) GetNewNonce() uint64 {
	if m != nil {
		return m.NewNonce
	}
	return 0
}

func (m *MsgRotateServiceKeyResponse) GetStatus() types.MutationStatusV1 {
	if m != nil {
		return m.Status
	}
	return types.MutationStatusV1_MUTATION_STATUS_V1_UNSPECIFIED
}

// MsgRevokeServiceKey immediately revokes the current service key binding (9.6a).
type MsgRevokeServiceKey struct {
	ParticipantType                          types.ParticipantType      `protobuf:"varint,1,opt,name=participant_type,json=participantType,proto3,enum=shared.v1.ParticipantType" json:"participant_type,omitempty"`
	ExpectedCurrentServiceAuthorizationNonce uint64                     `protobuf:"varint,2,opt,name=expected_current_service_authorization_nonce,json=expectedCurrentServiceAuthorizationNonce,proto3" json:"expected_current_service_authorization_nonce,omitempty"`
	ReasonCode                               ServiceKeyRevocationReason `protobuf:"varint,3,opt,name=reason_code,json=reasonCode,proto3,enum=hub.v1.ServiceKeyRevocationReason" json:"reason_code,omitempty"`
	OperatorAddress                          string                     `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
}

func (m *MsgRevokeServiceKey) Reset()         { *m = MsgRevokeServiceKey{} }
func (m *MsgRevokeServiceKey) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeServiceKey) ProtoMessage()    {}
func (*MsgRevokeServiceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_088b1815194819e9, []int{2}
}
func (m *MsgRevokeServiceKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeServiceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeServiceKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeServiceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeServiceKey.Merge(m, src)
}
func (m *MsgRevokeServiceKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeServiceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeServiceKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeServiceKey proto.InternalMessageInfo

func (m *MsgRevokeServiceKey) GetParticipantType() types.ParticipantType {
	if m != nil {
		return m.ParticipantType
	}
	return types.ParticipantType_PARTICIPANT_TYPE_UNSPECIFIED
}

func (m *MsgRevokeServiceKey) GetExpectedCurrentServiceAuthorizationNonce() uint64 {
	if m != nil {
		return m.ExpectedCurrentServiceAuthorizationNonce
	}
	return 0
}

func (m *MsgRevokeServiceKey) GetReasonCode() ServiceKeyRevocationReason {
	if m != nil {
		return m.ReasonCode
	}
	return ServiceKeyRevocationReason_SERVICE_KEY_REVOCATION_REASON_UNSPECIFIED
}

func (m *MsgRevokeServiceKey) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

// MsgRevokeServiceKeyResponse returns the revoked service address and the
// unchanged authorization nonce. Revoke changes only the binding status;
// rotation is the only operation that increments the nonce.
// MsgRevokeServiceKeyResponse defines the MsgRevokeServiceKeyResponse wire type.
type MsgRevokeServiceKeyResponse struct {
	OperatorAddress       string                 `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	RevokedServiceAddress string                 `protobuf:"bytes,2,opt,name=revoked_service_address,json=revokedServiceAddress,proto3" json:"revoked_service_address,omitempty"`
	AuthorizationNonce    uint64                 `protobuf:"varint,3,opt,name=authorization_nonce,json=authorizationNonce,proto3" json:"authorization_nonce,omitempty"`
	Status                types.MutationStatusV1 `protobuf:"varint,4,opt,name=status,proto3,enum=shared.v1.MutationStatusV1" json:"status,omitempty"`
}

func (m *MsgRevokeServiceKeyResponse) Reset()         { *m = MsgRevokeServiceKeyResponse{} }
func (m *MsgRevokeServiceKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeServiceKeyResponse) ProtoMessage()    {}
func (*MsgRevokeServiceKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_088b1815194819e9, []int{3}
}
func (m *MsgRevokeServiceKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeServiceKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeServiceKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeServiceKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeServiceKeyResponse.Merge(m, src)
}
func (m *MsgRevokeServiceKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeServiceKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeServiceKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeServiceKeyResponse proto.InternalMessageInfo

func (m *MsgRevokeServiceKeyResponse) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *MsgRevokeServiceKeyResponse) GetRevokedServiceAddress() string {
	if m != nil {
		return m.RevokedServiceAddress
	}
	return ""
}

func (m *MsgRevokeServiceKeyResponse) GetAuthorizationNonce() uint64 {
	if m != nil {
		return m.AuthorizationNonce
	}
	return 0
}

func (m *MsgRevokeServiceKeyResponse) GetStatus() types.MutationStatusV1 {
	if m != nil {
		return m.Status
	}
	return types.MutationStatusV1_MUTATION_STATUS_V1_UNSPECIFIED
}

// MsgUpdateServiceDescriptor publishes one bounded descriptor version (9.6a).
type MsgUpdateServiceDescriptor struct {
	ParticipantType           types.ParticipantType `protobuf:"varint,1,opt,name=participant_type,json=participantType,proto3,enum=shared.v1.ParticipantType" json:"participant_type,omitempty"`
	ExpectedDescriptorVersion uint64                `protobuf:"varint,2,opt,name=expected_descriptor_version,json=expectedDescriptorVersion,proto3" json:"expected_descriptor_version,omitempty"`
	Descriptor_               ServiceDescriptorV1   `protobuf:"bytes,3,opt,name=descriptor,proto3" json:"descriptor"`
	OperatorAddress           string                `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
}

func (m *MsgUpdateServiceDescriptor) Reset()         { *m = MsgUpdateServiceDescriptor{} }
func (m *MsgUpdateServiceDescriptor) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateServiceDescriptor) ProtoMessage()    {}
func (*MsgUpdateServiceDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_088b1815194819e9, []int{4}
}
func (m *MsgUpdateServiceDescriptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateServiceDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateServiceDescriptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateServiceDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateServiceDescriptor.Merge(m, src)
}
func (m *MsgUpdateServiceDescriptor) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateServiceDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateServiceDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateServiceDescriptor proto.InternalMessageInfo

func (m *MsgUpdateServiceDescriptor) GetParticipantType() types.ParticipantType {
	if m != nil {
		return m.ParticipantType
	}
	return types.ParticipantType_PARTICIPANT_TYPE_UNSPECIFIED
}

func (m *MsgUpdateServiceDescriptor) GetExpectedDescriptorVersion() uint64 {
	if m != nil {
		return m.ExpectedDescriptorVersion
	}
	return 0
}

func (m *MsgUpdateServiceDescriptor) GetDescriptor_() ServiceDescriptorV1 {
	if m != nil {
		return m.Descriptor_
	}
	return ServiceDescriptorV1{}
}

func (m *MsgUpdateServiceDescriptor) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

// MsgUpdateServiceDescriptorResponse returns the new version and its descriptor hash.
type MsgUpdateServiceDescriptorResponse struct {
	NewDescriptorVersion uint64                 `protobuf:"varint,1,opt,name=new_descriptor_version,json=newDescriptorVersion,proto3" json:"new_descriptor_version,omitempty"`
	DescriptorHash       []byte                 `protobuf:"bytes,2,opt,name=descriptor_hash,json=descriptorHash,proto3" json:"descriptor_hash,omitempty"`
	Status               types.MutationStatusV1 `protobuf:"varint,3,opt,name=status,proto3,enum=shared.v1.MutationStatusV1" json:"status,omitempty"`
}

func (m *MsgUpdateServiceDescriptorResponse) Reset()         { *m = MsgUpdateServiceDescriptorResponse{} }
func (m *MsgUpdateServiceDescriptorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateServiceDescriptorResponse) ProtoMessage()    {}
func (*MsgUpdateServiceDescriptorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_088b1815194819e9, []int{5}
}
func (m *MsgUpdateServiceDescriptorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateServiceDescriptorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateServiceDescriptorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateServiceDescriptorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateServiceDescriptorResponse.Merge(m, src)
}
func (m *MsgUpdateServiceDescriptorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateServiceDescriptorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateServiceDescriptorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateServiceDescriptorResponse proto.InternalMessageInfo

func (m *MsgUpdateServiceDescriptorResponse) GetNewDescriptorVersion() uint64 {
	if m != nil {
		return m.NewDescriptorVersion
	}
	return 0
}

func (m *MsgUpdateServiceDescriptorResponse) GetDescriptorHash() []byte {
	if m != nil {
		return m.DescriptorHash
	}
	return nil
}

func (m *MsgUpdateServiceDescriptorResponse) GetStatus() types.MutationStatusV1 {
	if m != nil {
		return m.Status
	}
	return types.MutationStatusV1_MUTATION_STATUS_V1_UNSPECIFIED
}

func init() {
	proto.RegisterType((*MsgRotateServiceKey)(nil), "hub.v1.MsgRotateServiceKey")
	proto.RegisterType((*MsgRotateServiceKeyResponse)(nil), "hub.v1.MsgRotateServiceKeyResponse")
	proto.RegisterType((*MsgRevokeServiceKey)(nil), "hub.v1.MsgRevokeServiceKey")
	proto.RegisterType((*MsgRevokeServiceKeyResponse)(nil), "hub.v1.MsgRevokeServiceKeyResponse")
	proto.RegisterType((*MsgUpdateServiceDescriptor)(nil), "hub.v1.MsgUpdateServiceDescriptor")
	proto.RegisterType((*MsgUpdateServiceDescriptorResponse)(nil), "hub.v1.MsgUpdateServiceDescriptorResponse")
}

func init() { proto.RegisterFile("hub/v1/msg_identity.proto", fileDescriptor_088b1815194819e9) }

var fileDescriptor_088b1815194819e9 = []byte{
	// 777 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xe3, 0x34, 0x54, 0xf4, 0x8a, 0xd2, 0xd6, 0xe9, 0x8f, 0x34, 0x11, 0x21, 0x58, 0x0c,
	0xa1, 0xa2, 0xb1, 0x92, 0x22, 0x21, 0x21, 0x54, 0xa9, 0x09, 0x48, 0x95, 0xaa, 0x42, 0xe4, 0x96,
	0x0e, 0x0c, 0x58, 0x8e, 0xfd, 0x48, 0xac, 0x2a, 0x77, 0xd6, 0xdd, 0x39, 0x69, 0x18, 0x11, 0x13,
	0x13, 0x33, 0x7f, 0x03, 0x43, 0x07, 0x66, 0xe6, 0x8e, 0x15, 0x13, 0x13, 0x42, 0xed, 0xd0, 0x15,
	0x89, 0x1d, 0x21, 0xdb, 0x97, 0xd8, 0xe4, 0x87, 0x20, 0xa8, 0x5d, 0xa2, 0xf8, 0xbd, 0xf7, 0x7d,
	0xf7, 0xf4, 0x7d, 0x1f, 0x9f, 0xd1, 0x6a, 0xd3, 0xad, 0xab, 0xed, 0x92, 0xda, 0x62, 0x0d, 0xdd,
	0xb6, 0x00, 0x73, 0x9b, 0x77, 0x8b, 0x0e, 0x25, 0x9c, 0xc8, 0xd3, 0x4d, 0xb7, 0x5e, 0x6c, 0x97,
	0x32, 0x0b, 0x46, 0xcb, 0xc6, 0x44, 0xf5, 0x7f, 0x83, 0x54, 0x66, 0xc5, 0x24, 0xac, 0x45, 0x98,
	0xa7, 0x12, 0x62, 0x91, 0x58, 0x0d, 0x12, 0xba, 0xff, 0xa4, 0x06, 0x0f, 0x22, 0xb5, 0xd8, 0x20,
	0x0d, 0x12, 0xc4, 0xbd, 0x7f, 0x22, 0x9a, 0x12, 0xe7, 0x9b, 0xa4, 0xd5, 0x22, 0x58, 0x04, 0x6f,
	0x8b, 0xa0, 0x63, 0x50, 0x6e, 0x9b, 0xb6, 0x63, 0x60, 0x3e, 0x30, 0x5c, 0x66, 0x99, 0x35, 0x0d,
	0x0a, 0xd6, 0x90, 0xf4, 0x66, 0x18, 0xa7, 0xc0, 0xb8, 0x0e, 0xd8, 0x24, 0x96, 0x8d, 0xc5, 0x7c,
	0xca, 0xc7, 0x29, 0x94, 0xda, 0x65, 0x0d, 0x8d, 0x70, 0x83, 0xc3, 0x1e, 0xd0, 0xb6, 0x6d, 0xc2,
	0x0e, 0x74, 0xe5, 0x27, 0x68, 0x3e, 0x7a, 0x18, 0xef, 0x3a, 0x90, 0x96, 0xf2, 0x52, 0x21, 0x59,
	0xce, 0x14, 0x83, 0x8e, 0xc5, 0x76, 0xa9, 0x58, 0x0b, 0x4b, 0xf6, 0xbb, 0x0e, 0x68, 0x73, 0xce,
	0x9f, 0x01, 0xb9, 0x8c, 0x64, 0x0c, 0x1d, 0x9d, 0x05, 0x8d, 0x75, 0xc7, 0xad, 0x1f, 0x42, 0x37,
	0x1d, 0xcf, 0x4b, 0x85, 0x1b, 0x95, 0xc4, 0xc9, 0xcf, 0xb4, 0xa4, 0xcd, 0x63, 0xe8, 0x88, 0x73,
	0x6b, 0x7e, 0x56, 0x7e, 0x89, 0xee, 0xc1, 0x91, 0x03, 0x26, 0x07, 0x4b, 0x37, 0x5d, 0x4a, 0x01,
	0xf3, 0x7e, 0x03, 0xc3, 0xe5, 0x4d, 0x42, 0xed, 0xd7, 0x06, 0xb7, 0x09, 0xd6, 0x31, 0xc1, 0x26,
	0xa4, 0xa7, 0xf2, 0x52, 0x21, 0xa1, 0x15, 0x7a, 0x9a, 0x6a, 0x20, 0x11, 0x3d, 0xb7, 0xa2, 0x82,
	0xa7, 0x5e, 0xbd, 0xfc, 0x00, 0x2d, 0x45, 0x67, 0x3a, 0x84, 0xae, 0xb7, 0x1d, 0xf2, 0x2a, 0x9d,
	0x88, 0x8c, 0x25, 0x87, 0x63, 0xed, 0x40, 0xb7, 0xe6, 0xe5, 0xe5, 0x2a, 0x9a, 0x27, 0x0e, 0x50,
	0x83, 0x13, 0xaa, 0x1b, 0x96, 0x45, 0x81, 0xb1, 0xf4, 0xb5, 0xbc, 0x54, 0x98, 0xa9, 0xa4, 0xbf,
	0x7c, 0x5a, 0x5f, 0x14, 0xcb, 0xdd, 0x0a, 0x32, 0x7b, 0x9c, 0xda, 0xb8, 0xa1, 0xcd, 0xf5, 0x14,
	0x22, 0xfc, 0xf0, 0xd1, 0x9b, 0x8b, 0xe3, 0xb5, 0xa1, 0x3e, 0xef, 0x2e, 0x8e, 0xd7, 0x14, 0x4e,
	0x5d, 0x20, 0x0e, 0x60, 0xf5, 0x48, 0xf5, 0xf6, 0x3d, 0x62, 0x2d, 0xca, 0x2f, 0x09, 0x65, 0x47,
	0xc4, 0x35, 0x60, 0x0e, 0xc1, 0x0c, 0x46, 0x8e, 0x28, 0x4d, 0x38, 0xa2, 0xbc, 0x8d, 0x52, 0x51,
	0x83, 0x7a, 0x7d, 0xe2, 0x7f, 0xe9, 0xb3, 0x10, 0x5a, 0xd6, 0xeb, 0x94, 0x45, 0x33, 0x5e, 0xa7,
	0xe8, 0x9e, 0xae, 0x63, 0xe8, 0x04, 0x7b, 0xd8, 0x40, 0xd3, 0x8c, 0x1b, 0xdc, 0x65, 0xbe, 0xf1,
	0xc9, 0x72, 0x36, 0x02, 0xd6, 0xae, 0xcb, 0xfd, 0x8d, 0xed, 0xf9, 0x05, 0x07, 0x25, 0x4d, 0x94,
	0x2a, 0x6f, 0x05, 0xaf, 0xd0, 0x26, 0x87, 0x57, 0xc0, 0xeb, 0xa4, 0xec, 0xc5, 0x27, 0x64, 0xaf,
	0x8a, 0x66, 0x29, 0x18, 0x8c, 0x60, 0xdd, 0x24, 0x56, 0x60, 0x49, 0xb2, 0xac, 0x14, 0x83, 0x8b,
	0xa5, 0x18, 0x5d, 0x68, 0x9b, 0x98, 0xbe, 0x4e, 0xf3, 0xcb, 0x35, 0x14, 0xc8, 0xaa, 0xc4, 0x1a,
	0xbd, 0xe4, 0xc4, 0xd5, 0x72, 0x38, 0x60, 0xb7, 0xf2, 0x21, 0x1e, 0x70, 0x38, 0x10, 0xbf, 0x5c,
	0x0e, 0x6b, 0x68, 0x85, 0xfa, 0x07, 0x58, 0x13, 0xb3, 0xb8, 0x24, 0x84, 0x03, 0x3c, 0xaa, 0x28,
	0x35, 0xfe, 0x06, 0x91, 0x8d, 0xe1, 0x7d, 0xfd, 0x17, 0xa3, 0x3f, 0xe2, 0x28, 0xb3, 0xcb, 0x1a,
	0xcf, 0x1d, 0x2b, 0x7c, 0x49, 0x1f, 0x03, 0x33, 0xa9, 0xed, 0x70, 0x42, 0x2f, 0x0b, 0xd5, 0x4d,
	0x94, 0xed, 0xa3, 0x6a, 0xf5, 0xbb, 0xeb, 0x6d, 0xa0, 0xcc, 0x26, 0x58, 0x90, 0xb9, 0xda, 0x2b,
	0x09, 0xcf, 0x3f, 0x08, 0x0a, 0xe4, 0x2d, 0x84, 0x42, 0x99, 0x6f, 0xc1, 0x6c, 0x39, 0x3b, 0x40,
	0x62, 0x44, 0x55, 0xaa, 0x24, 0x4e, 0xbe, 0xdd, 0x8a, 0x69, 0x11, 0xd1, 0xe5, 0x80, 0x58, 0x1d,
	0x0b, 0xe2, 0xdd, 0x61, 0x10, 0xc7, 0x78, 0xaa, 0x7c, 0x96, 0x90, 0x32, 0x3e, 0xdd, 0xc7, 0xf2,
	0x3e, 0x5a, 0xf6, 0xee, 0xa3, 0x11, 0x76, 0x49, 0xbe, 0x5d, 0x8b, 0x18, 0x3a, 0xc3, 0x4e, 0xad,
	0xa3, 0xb9, 0x88, 0xa2, 0x69, 0xb0, 0x66, 0xe4, 0x0b, 0x16, 0xd7, 0x92, 0x61, 0x72, 0xdb, 0x60,
	0xcd, 0x08, 0x33, 0x53, 0xff, 0xcc, 0x4c, 0x65, 0xf3, 0xe4, 0x2c, 0x27, 0x9d, 0x9e, 0xe5, 0xa4,
	0xef, 0x67, 0x39, 0xe9, 0xfd, 0x79, 0x2e, 0x76, 0x7a, 0x9e, 0x8b, 0x7d, 0x3d, 0xcf, 0xc5, 0x5e,
	0xdc, 0x69, 0xd8, 0xdc, 0xdb, 0x8a, 0x49, 0x5a, 0xea, 0x3e, 0x75, 0xe1, 0x99, 0x67, 0x08, 0x26,
	0x16, 0x08, 0x57, 0x3c, 0x7e, 0x58, 0x7d, 0xda, 0xff, 0x9c, 0x6f, 0xfc, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0xb4, 0xb3, 0x64, 0xbf, 0x08, 0x00, 0x00,
}

func (m *MsgRotateServiceKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRotateServiceKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRotateServiceKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NewServiceKeyProof) > 0 {
		i -= len(m.NewServiceKeyProof)
		copy(dAtA[i:], m.NewServiceKeyProof)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.NewServiceKeyProof)))
		i--
		dAtA[i] = 0x22
	}
	if m.ExpectedCurrentServiceAuthorizationNonce != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ExpectedCurrentServiceAuthorizationNonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.NewServicePubkey) > 0 {
		i -= len(m.NewServicePubkey)
		copy(dAtA[i:], m.NewServicePubkey)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.NewServicePubkey)))
		i--
		dAtA[i] = 0x12
	}
	if m.ParticipantType != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ParticipantType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRotateServiceKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRotateServiceKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRotateServiceKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.NewNonce != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.NewNonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.NewServiceAddress) > 0 {
		i -= len(m.NewServiceAddress)
		copy(dAtA[i:], m.NewServiceAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.NewServiceAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeServiceKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeServiceKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeServiceKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.ReasonCode != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ReasonCode))
		i--
		dAtA[i] = 0x18
	}
	if m.ExpectedCurrentServiceAuthorizationNonce != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ExpectedCurrentServiceAuthorizationNonce))
		i--
		dAtA[i] = 0x10
	}
	if m.ParticipantType != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ParticipantType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeServiceKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeServiceKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeServiceKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.AuthorizationNonce != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.AuthorizationNonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RevokedServiceAddress) > 0 {
		i -= len(m.RevokedServiceAddress)
		copy(dAtA[i:], m.RevokedServiceAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.RevokedServiceAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateServiceDescriptor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateServiceDescriptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateServiceDescriptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Descriptor_.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgIdentity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ExpectedDescriptorVersion != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ExpectedDescriptorVersion))
		i--
		dAtA[i] = 0x10
	}
	if m.ParticipantType != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.ParticipantType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateServiceDescriptorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateServiceDescriptorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateServiceDescriptorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DescriptorHash) > 0 {
		i -= len(m.DescriptorHash)
		copy(dAtA[i:], m.DescriptorHash)
		i = encodeVarintMsgIdentity(dAtA, i, uint64(len(m.DescriptorHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.NewDescriptorVersion != 0 {
		i = encodeVarintMsgIdentity(dAtA, i, uint64(m.NewDescriptorVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgIdentity(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgIdentity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRotateServiceKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ParticipantType != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ParticipantType))
	}
	l = len(m.NewServicePubkey)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	if m.ExpectedCurrentServiceAuthorizationNonce != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ExpectedCurrentServiceAuthorizationNonce))
	}
	l = len(m.NewServiceKeyProof)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	return n
}

func (m *MsgRotateServiceKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	l = len(m.NewServiceAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	if m.NewNonce != 0 {
		n += 1 + sovMsgIdentity(uint64(m.NewNonce))
	}
	if m.Status != 0 {
		n += 1 + sovMsgIdentity(uint64(m.Status))
	}
	return n
}

func (m *MsgRevokeServiceKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ParticipantType != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ParticipantType))
	}
	if m.ExpectedCurrentServiceAuthorizationNonce != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ExpectedCurrentServiceAuthorizationNonce))
	}
	if m.ReasonCode != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ReasonCode))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	return n
}

func (m *MsgRevokeServiceKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	l = len(m.RevokedServiceAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	if m.AuthorizationNonce != 0 {
		n += 1 + sovMsgIdentity(uint64(m.AuthorizationNonce))
	}
	if m.Status != 0 {
		n += 1 + sovMsgIdentity(uint64(m.Status))
	}
	return n
}

func (m *MsgUpdateServiceDescriptor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ParticipantType != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ParticipantType))
	}
	if m.ExpectedDescriptorVersion != 0 {
		n += 1 + sovMsgIdentity(uint64(m.ExpectedDescriptorVersion))
	}
	l = m.Descriptor_.Size()
	n += 1 + l + sovMsgIdentity(uint64(l))
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	return n
}

func (m *MsgUpdateServiceDescriptorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NewDescriptorVersion != 0 {
		n += 1 + sovMsgIdentity(uint64(m.NewDescriptorVersion))
	}
	l = len(m.DescriptorHash)
	if l > 0 {
		n += 1 + l + sovMsgIdentity(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovMsgIdentity(uint64(m.Status))
	}
	return n
}

func sovMsgIdentity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgIdentity(x uint64) (n int) {
	return sovMsgIdentity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRotateServiceKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRotateServiceKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRotateServiceKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantType", wireType)
			}
			m.ParticipantType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticipantType |= types.ParticipantType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewServicePubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewServicePubkey = append(m.NewServicePubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.NewServicePubkey == nil {
				m.NewServicePubkey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedCurrentServiceAuthorizationNonce", wireType)
			}
			m.ExpectedCurrentServiceAuthorizationNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpectedCurrentServiceAuthorizationNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewServiceKeyProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewServiceKeyProof = append(m.NewServiceKeyProof[:0], dAtA[iNdEx:postIndex]...)
			if m.NewServiceKeyProof == nil {
				m.NewServiceKeyProof = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRotateServiceKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRotateServiceKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRotateServiceKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewServiceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewServiceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewNonce", wireType)
			}
			m.NewNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types.MutationStatusV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeServiceKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeServiceKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeServiceKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantType", wireType)
			}
			m.ParticipantType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticipantType |= types.ParticipantType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedCurrentServiceAuthorizationNonce", wireType)
			}
			m.ExpectedCurrentServiceAuthorizationNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpectedCurrentServiceAuthorizationNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasonCode", wireType)
			}
			m.ReasonCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReasonCode |= ServiceKeyRevocationReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeServiceKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeServiceKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeServiceKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedServiceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevokedServiceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationNonce", wireType)
			}
			m.AuthorizationNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuthorizationNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types.MutationStatusV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateServiceDescriptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateServiceDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateServiceDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantType", wireType)
			}
			m.ParticipantType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticipantType |= types.ParticipantType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedDescriptorVersion", wireType)
			}
			m.ExpectedDescriptorVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpectedDescriptorVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Descriptor_", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Descriptor_.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateServiceDescriptorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateServiceDescriptorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateServiceDescriptorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewDescriptorVersion", wireType)
			}
			m.NewDescriptorVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewDescriptorVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DescriptorHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DescriptorHash = append(m.DescriptorHash[:0], dAtA[iNdEx:postIndex]...)
			if m.DescriptorHash == nil {
				m.DescriptorHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types.MutationStatusV1(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgIdentity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgIdentity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgIdentity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgIdentity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgIdentity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgIdentity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgIdentity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgIdentity = fmt.Errorf("proto: unexpected end of group")
)
