// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task/internal/v1/verifier_assignment_store.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SelectedVerifierStoreV1 stores the verifier operator as codec bytes.
type SelectedVerifierStoreV1 struct {
	OperatorAddress []byte `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	Slot            uint32 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	SlotVersion     uint64 `protobuf:"varint,3,opt,name=slot_version,json=slotVersion,proto3" json:"slot_version,omitempty"`
}

func (m *SelectedVerifierStoreV1) Reset()         { *m = SelectedVerifierStoreV1{} }
func (m *SelectedVerifierStoreV1) String() string { return proto.CompactTextString(m) }
func (*SelectedVerifierStoreV1) ProtoMessage()    {}
func (*SelectedVerifierStoreV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_39e9de45ff785cde, []int{0}
}
func (m *SelectedVerifierStoreV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SelectedVerifierStoreV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SelectedVerifierStoreV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SelectedVerifierStoreV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectedVerifierStoreV1.Merge(m, src)
}
func (m *SelectedVerifierStoreV1) XXX_Size() int {
	return m.Size()
}
func (m *SelectedVerifierStoreV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectedVerifierStoreV1.DiscardUnknown(m)
}

var xxx_messageInfo_SelectedVerifierStoreV1 proto.InternalMessageInfo

func (m *SelectedVerifierStoreV1) GetOperatorAddress() []byte {
	if m != nil {
		return m.OperatorAddress
	}
	return nil
}

func (m *SelectedVerifierStoreV1) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *SelectedVerifierStoreV1) GetSlotVersion() uint64 {
	if m != nil {
		return m.SlotVersion
	}
	return 0
}

// VerifierAssignmentStoreState preserves selected verifier order.
type VerifierAssignmentStoreState struct {
	TaskId                      []byte                     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VerifyRound                 uint32                     `protobuf:"varint,2,opt,name=verify_round,json=verifyRound,proto3" json:"verify_round,omitempty"`
	OpenVerifyHeight            uint64                     `protobuf:"varint,3,opt,name=open_verify_height,json=openVerifyHeight,proto3" json:"open_verify_height,omitempty"`
	VerifierCandidateWindowHash []byte                     `protobuf:"bytes,4,opt,name=verifier_candidate_window_hash,json=verifierCandidateWindowHash,proto3" json:"verifier_candidate_window_hash,omitempty"`
	VerifierLegalSetHash        []byte                     `protobuf:"bytes,5,opt,name=verifier_legal_set_hash,json=verifierLegalSetHash,proto3" json:"verifier_legal_set_hash,omitempty"`
	SelectedVerifiersHash       []byte                     `protobuf:"bytes,6,opt,name=selected_verifiers_hash,json=selectedVerifiersHash,proto3" json:"selected_verifiers_hash,omitempty"`
	SelectionRandomnessHeight   uint64                     `protobuf:"varint,7,opt,name=selection_randomness_height,json=selectionRandomnessHeight,proto3" json:"selection_randomness_height,omitempty"`
	SelectionRandomnessBeacon   []byte                     `protobuf:"bytes,8,opt,name=selection_randomness_beacon,json=selectionRandomnessBeacon,proto3" json:"selection_randomness_beacon,omitempty"`
	SelectedVerifiers           []*SelectedVerifierStoreV1 `protobuf:"bytes,9,rep,name=selected_verifiers,json=selectedVerifiers,proto3" json:"selected_verifiers,omitempty"`
	SelectedVerifierCount       uint32                     `protobuf:"varint,10,opt,name=selected_verifier_count,json=selectedVerifierCount,proto3" json:"selected_verifier_count,omitempty"`
	VerifierHandraiseCount      uint32                     `protobuf:"varint,11,opt,name=verifier_handraise_count,json=verifierHandraiseCount,proto3" json:"verifier_handraise_count,omitempty"`
	CommitDeadlineHeight        uint64                     `protobuf:"varint,12,opt,name=commit_deadline_height,json=commitDeadlineHeight,proto3" json:"commit_deadline_height,omitempty"`
	RevealDeadlineHeight        uint64                     `protobuf:"varint,13,opt,name=reveal_deadline_height,json=revealDeadlineHeight,proto3" json:"reveal_deadline_height,omitempty"`
	VerifyDeadlineHeight        uint64                     `protobuf:"varint,14,opt,name=verify_deadline_height,json=verifyDeadlineHeight,proto3" json:"verify_deadline_height,omitempty"`
}

func (m *VerifierAssignmentStoreState) Reset()         { *m = VerifierAssignmentStoreState{} }
func (m *VerifierAssignmentStoreState) String() string { return proto.CompactTextString(m) }
func (*VerifierAssignmentStoreState) ProtoMessage()    {}
func (*VerifierAssignmentStoreState) Descriptor() ([]byte, []int) {
	return fileDescriptor_39e9de45ff785cde, []int{1}
}
func (m *VerifierAssignmentStoreState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifierAssignmentStoreState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifierAssignmentStoreState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifierAssignmentStoreState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierAssignmentStoreState.Merge(m, src)
}
func (m *VerifierAssignmentStoreState) XXX_Size() int {
	return m.Size()
}
func (m *VerifierAssignmentStoreState) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierAssignmentStoreState.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierAssignmentStoreState proto.InternalMessageInfo

func (m *VerifierAssignmentStoreState) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *VerifierAssignmentStoreState) GetVerifyRound() uint32 {
	if m != nil {
		return m.VerifyRound
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetOpenVerifyHeight() uint64 {
	if m != nil {
		return m.OpenVerifyHeight
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetVerifierCandidateWindowHash() []byte {
	if m != nil {
		return m.VerifierCandidateWindowHash
	}
	return nil
}

func (m *VerifierAssignmentStoreState) GetVerifierLegalSetHash() []byte {
	if m != nil {
		return m.VerifierLegalSetHash
	}
	return nil
}

func (m *VerifierAssignmentStoreState) GetSelectedVerifiersHash() []byte {
	if m != nil {
		return m.SelectedVerifiersHash
	}
	return nil
}

func (m *VerifierAssignmentStoreState) GetSelectionRandomnessHeight() uint64 {
	if m != nil {
		return m.SelectionRandomnessHeight
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetSelectionRandomnessBeacon() []byte {
	if m != nil {
		return m.SelectionRandomnessBeacon
	}
	return nil
}

func (m *VerifierAssignmentStoreState) GetSelectedVerifiers() []*SelectedVerifierStoreV1 {
	if m != nil {
		return m.SelectedVerifiers
	}
	return nil
}

func (m *VerifierAssignmentStoreState) GetSelectedVerifierCount() uint32 {
	if m != nil {
		return m.SelectedVerifierCount
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetVerifierHandraiseCount() uint32 {
	if m != nil {
		return m.VerifierHandraiseCount
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetCommitDeadlineHeight() uint64 {
	if m != nil {
		return m.CommitDeadlineHeight
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetRevealDeadlineHeight() uint64 {
	if m != nil {
		return m.RevealDeadlineHeight
	}
	return 0
}

func (m *VerifierAssignmentStoreState) GetVerifyDeadlineHeight() uint64 {
	if m != nil {
		return m.VerifyDeadlineHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*SelectedVerifierStoreV1)(nil), "task.internal.v1.SelectedVerifierStoreV1")
	proto.RegisterType((*VerifierAssignmentStoreState)(nil), "task.internal.v1.VerifierAssignmentStoreState")
}

func init() {
	proto.RegisterFile("task/internal/v1/verifier_assignment_store.proto", fileDescriptor_39e9de45ff785cde)
}

var fileDescriptor_39e9de45ff785cde = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x4f, 0x6f, 0xd3, 0x3e,
	0x1c, 0xc6, 0x9b, 0xdf, 0xfa, 0xeb, 0xc0, 0xed, 0x60, 0x58, 0xa3, 0x0d, 0x1a, 0x8a, 0xca, 0x4e,
	0x9d, 0x84, 0x12, 0x0a, 0x03, 0x71, 0x42, 0xda, 0xca, 0xa1, 0x48, 0x48, 0x48, 0x29, 0x2a, 0x88,
	0x8b, 0xe5, 0xc6, 0x5f, 0x1a, 0x8b, 0xd4, 0xae, 0x6c, 0xb7, 0xa3, 0xe2, 0x4d, 0xf0, 0x3a, 0x78,
	0x25, 0x1c, 0x77, 0xe4, 0x88, 0xda, 0x37, 0x82, 0x62, 0x27, 0x91, 0xd6, 0x6e, 0xa7, 0x36, 0xcf,
	0xf3, 0x7c, 0xf2, 0xfd, 0x63, 0x2b, 0xe8, 0x99, 0xa1, 0xfa, 0x5b, 0xc4, 0x85, 0x01, 0x25, 0x68,
	0x16, 0x2d, 0xfb, 0xd1, 0x12, 0x14, 0xff, 0xca, 0x41, 0x11, 0xaa, 0x35, 0x9f, 0x8a, 0x19, 0x08,
	0x43, 0xb4, 0x91, 0x0a, 0xc2, 0xb9, 0x92, 0x46, 0xe2, 0xc3, 0x9c, 0x08, 0x4b, 0x22, 0x5c, 0xf6,
	0x4f, 0x7e, 0xa0, 0xce, 0x08, 0x32, 0x48, 0x0c, 0xb0, 0x71, 0x01, 0x8f, 0x72, 0x60, 0xdc, 0xc7,
	0xa7, 0xe8, 0x50, 0xce, 0x41, 0x51, 0x23, 0x15, 0xa1, 0x8c, 0x29, 0xd0, 0xda, 0xf7, 0xba, 0x5e,
	0xaf, 0x15, 0xdf, 0x2f, 0xf5, 0x73, 0x27, 0x63, 0x8c, 0xea, 0x3a, 0x93, 0xc6, 0xff, 0xaf, 0xeb,
	0xf5, 0x0e, 0x62, 0xfb, 0x1f, 0x3f, 0x41, 0xad, 0xfc, 0x97, 0x2c, 0x41, 0x69, 0x2e, 0x85, 0xbf,
	0xd7, 0xf5, 0x7a, 0xf5, 0xb8, 0x99, 0x6b, 0x63, 0x27, 0x9d, 0xfc, 0x6a, 0xa0, 0xc7, 0x65, 0xd5,
	0xf3, 0xaa, 0x63, 0x5b, 0x7f, 0x64, 0xa8, 0x01, 0xdc, 0x41, 0xfb, 0x79, 0xc7, 0x84, 0xb3, 0xa2,
	0x72, 0x23, 0x7f, 0x7c, 0xc7, 0xf2, 0x97, 0xdb, 0x59, 0x57, 0x44, 0xc9, 0x85, 0x60, 0x45, 0xe1,
	0xa6, 0xd3, 0xe2, 0x5c, 0xc2, 0x4f, 0x11, 0x96, 0x73, 0x10, 0xa4, 0xc8, 0xa5, 0xc0, 0xa7, 0xa9,
	0x29, 0xba, 0xc8, 0x07, 0x13, 0xb6, 0xf2, 0x6a, 0x68, 0x75, 0x3c, 0x40, 0x41, 0xb5, 0xbc, 0x84,
	0x0a, 0xc6, 0x19, 0x35, 0x40, 0x2e, 0xb9, 0x60, 0xf2, 0x92, 0xa4, 0x54, 0xa7, 0x7e, 0xdd, 0x36,
	0x70, 0x5c, 0xa6, 0x06, 0x65, 0xe8, 0x93, 0xcd, 0x0c, 0xa9, 0x4e, 0xf1, 0x4b, 0xd4, 0xa9, 0x5e,
	0x92, 0xc1, 0x94, 0x66, 0x44, 0x83, 0x71, 0xf4, 0xff, 0x96, 0x3e, 0x2a, 0xed, 0xf7, 0xb9, 0x3b,
	0x02, 0x63, 0xb1, 0x57, 0xa8, 0xa3, 0x8b, 0x33, 0x20, 0x65, 0x40, 0x3b, 0xac, 0x61, 0xb1, 0x87,
	0x7a, 0xeb, 0x88, 0xb4, 0xe5, 0xde, 0xa0, 0x63, 0x67, 0x70, 0x29, 0x88, 0xa2, 0x82, 0xc9, 0x99,
	0x00, 0xad, 0xcb, 0x51, 0xf7, 0xed, 0xa8, 0x8f, 0xaa, 0x48, 0x5c, 0x25, 0x8a, 0x99, 0x6f, 0xe3,
	0x27, 0x40, 0x13, 0x29, 0xfc, 0x3b, 0xb6, 0xf6, 0x4d, 0xfc, 0x85, 0x0d, 0xe0, 0xcf, 0x08, 0xef,
	0xf6, 0xed, 0xdf, 0xed, 0xee, 0xf5, 0x9a, 0xcf, 0x4f, 0xc3, 0xed, 0xab, 0x16, 0xde, 0x72, 0xcf,
	0xe2, 0x07, 0x3b, 0xd3, 0xdd, 0xb8, 0x11, 0x92, 0xc8, 0x85, 0x30, 0x3e, 0xb2, 0x27, 0xbd, 0xb3,
	0x91, 0x41, 0x6e, 0xe2, 0xd7, 0xc8, 0xaf, 0xe2, 0x29, 0x15, 0x4c, 0x51, 0xae, 0xa1, 0x00, 0x9b,
	0x16, 0x6c, 0x97, 0xfe, 0xb0, 0xb4, 0x1d, 0x79, 0x86, 0xda, 0x89, 0x9c, 0xcd, 0xb8, 0x21, 0x0c,
	0x28, 0xcb, 0xb8, 0x80, 0x72, 0x8d, 0x2d, 0xbb, 0xc6, 0x23, 0xe7, 0xbe, 0x2d, 0xcc, 0x62, 0x83,
	0x67, 0xa8, 0xad, 0x60, 0x09, 0x34, 0xdb, 0xa1, 0x0e, 0x1c, 0xe5, 0xdc, 0x5d, 0xaa, 0xb8, 0x94,
	0xdb, 0xd4, 0x3d, 0x47, 0x39, 0xf7, 0x3a, 0x75, 0x31, 0xfc, 0xbd, 0x0e, 0xbc, 0xab, 0x75, 0xe0,
	0xfd, 0x5d, 0x07, 0xde, 0xcf, 0x4d, 0x50, 0xbb, 0xda, 0x04, 0xb5, 0x3f, 0x9b, 0xa0, 0xf6, 0x25,
	0x9c, 0x72, 0x93, 0x2e, 0x26, 0x61, 0x22, 0x67, 0xd1, 0x47, 0xb5, 0x80, 0x0f, 0x73, 0x10, 0x91,
	0x90, 0x0c, 0xa2, 0xef, 0xd1, 0xf5, 0x4f, 0x84, 0x59, 0xcd, 0x41, 0x4f, 0x1a, 0xf6, 0x63, 0xf0,
	0xe2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x59, 0x0e, 0x2e, 0x40, 0x04, 0x00, 0x00,
}

func (m *SelectedVerifierStoreV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SelectedVerifierStoreV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SelectedVerifierStoreV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlotVersion != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.SlotVersion))
		i--
		dAtA[i] = 0x18
	}
	if m.Slot != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VerifierAssignmentStoreState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifierAssignmentStoreState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifierAssignmentStoreState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerifyDeadlineHeight != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.VerifyDeadlineHeight))
		i--
		dAtA[i] = 0x70
	}
	if m.RevealDeadlineHeight != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.RevealDeadlineHeight))
		i--
		dAtA[i] = 0x68
	}
	if m.CommitDeadlineHeight != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.CommitDeadlineHeight))
		i--
		dAtA[i] = 0x60
	}
	if m.VerifierHandraiseCount != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.VerifierHandraiseCount))
		i--
		dAtA[i] = 0x58
	}
	if m.SelectedVerifierCount != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.SelectedVerifierCount))
		i--
		dAtA[i] = 0x50
	}
	if len(m.SelectedVerifiers) > 0 {
		for iNdEx := len(m.SelectedVerifiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SelectedVerifiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.SelectionRandomnessBeacon) > 0 {
		i -= len(m.SelectionRandomnessBeacon)
		copy(dAtA[i:], m.SelectionRandomnessBeacon)
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(len(m.SelectionRandomnessBeacon)))
		i--
		dAtA[i] = 0x42
	}
	if m.SelectionRandomnessHeight != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.SelectionRandomnessHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SelectedVerifiersHash) > 0 {
		i -= len(m.SelectedVerifiersHash)
		copy(dAtA[i:], m.SelectedVerifiersHash)
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(len(m.SelectedVerifiersHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.VerifierLegalSetHash) > 0 {
		i -= len(m.VerifierLegalSetHash)
		copy(dAtA[i:], m.VerifierLegalSetHash)
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(len(m.VerifierLegalSetHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.VerifierCandidateWindowHash) > 0 {
		i -= len(m.VerifierCandidateWindowHash)
		copy(dAtA[i:], m.VerifierCandidateWindowHash)
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(len(m.VerifierCandidateWindowHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.OpenVerifyHeight != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.OpenVerifyHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.VerifyRound != 0 {
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(m.VerifyRound))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintVerifierAssignmentStore(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVerifierAssignmentStore(dAtA []byte, offset int, v uint64) int {
	offset -= sovVerifierAssignmentStore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SelectedVerifierStoreV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovVerifierAssignmentStore(uint64(l))
	}
	if m.Slot != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.Slot))
	}
	if m.SlotVersion != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.SlotVersion))
	}
	return n
}

func (m *VerifierAssignmentStoreState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovVerifierAssignmentStore(uint64(l))
	}
	if m.VerifyRound != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.VerifyRound))
	}
	if m.OpenVerifyHeight != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.OpenVerifyHeight))
	}
	l = len(m.VerifierCandidateWindowHash)
	if l > 0 {
		n += 1 + l + sovVerifierAssignmentStore(uint64(l))
	}
	l = len(m.VerifierLegalSetHash)
	if l > 0 {
		n += 1 + l + sovVerifierAssignmentStore(uint64(l))
	}
	l = len(m.SelectedVerifiersHash)
	if l > 0 {
		n += 1 + l + sovVerifierAssignmentStore(uint64(l))
	}
	if m.SelectionRandomnessHeight != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.SelectionRandomnessHeight))
	}
	l = len(m.SelectionRandomnessBeacon)
	if l > 0 {
		n += 1 + l + sovVerifierAssignmentStore(uint64(l))
	}
	if len(m.SelectedVerifiers) > 0 {
		for _, e := range m.SelectedVerifiers {
			l = e.Size()
			n += 1 + l + sovVerifierAssignmentStore(uint64(l))
		}
	}
	if m.SelectedVerifierCount != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.SelectedVerifierCount))
	}
	if m.VerifierHandraiseCount != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.VerifierHandraiseCount))
	}
	if m.CommitDeadlineHeight != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.CommitDeadlineHeight))
	}
	if m.RevealDeadlineHeight != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.RevealDeadlineHeight))
	}
	if m.VerifyDeadlineHeight != 0 {
		n += 1 + sovVerifierAssignmentStore(uint64(m.VerifyDeadlineHeight))
	}
	return n
}

func sovVerifierAssignmentStore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVerifierAssignmentStore(x uint64) (n int) {
	return sovVerifierAssignmentStore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SelectedVerifierStoreV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerifierAssignmentStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SelectedVerifierStoreV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SelectedVerifierStoreV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = append(m.OperatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.OperatorAddress == nil {
				m.OperatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotVersion", wireType)
			}
			m.SlotVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVerifierAssignmentStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifierAssignmentStoreState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerifierAssignmentStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifierAssignmentStoreState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifierAssignmentStoreState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyRound", wireType)
			}
			m.VerifyRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifyRound |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenVerifyHeight", wireType)
			}
			m.OpenVerifyHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpenVerifyHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierCandidateWindowHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifierCandidateWindowHash = append(m.VerifierCandidateWindowHash[:0], dAtA[iNdEx:postIndex]...)
			if m.VerifierCandidateWindowHash == nil {
				m.VerifierCandidateWindowHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierLegalSetHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifierLegalSetHash = append(m.VerifierLegalSetHash[:0], dAtA[iNdEx:postIndex]...)
			if m.VerifierLegalSetHash == nil {
				m.VerifierLegalSetHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectedVerifiersHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SelectedVerifiersHash = append(m.SelectedVerifiersHash[:0], dAtA[iNdEx:postIndex]...)
			if m.SelectedVerifiersHash == nil {
				m.SelectedVerifiersHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectionRandomnessHeight", wireType)
			}
			m.SelectionRandomnessHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelectionRandomnessHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectionRandomnessBeacon", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SelectionRandomnessBeacon = append(m.SelectionRandomnessBeacon[:0], dAtA[iNdEx:postIndex]...)
			if m.SelectionRandomnessBeacon == nil {
				m.SelectionRandomnessBeacon = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectedVerifiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SelectedVerifiers = append(m.SelectedVerifiers, &SelectedVerifierStoreV1{})
			if err := m.SelectedVerifiers[len(m.SelectedVerifiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectedVerifierCount", wireType)
			}
			m.SelectedVerifierCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelectedVerifierCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierHandraiseCount", wireType)
			}
			m.VerifierHandraiseCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierHandraiseCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitDeadlineHeight", wireType)
			}
			m.CommitDeadlineHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitDeadlineHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealDeadlineHeight", wireType)
			}
			m.RevealDeadlineHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealDeadlineHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyDeadlineHeight", wireType)
			}
			m.VerifyDeadlineHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifyDeadlineHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVerifierAssignmentStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerifierAssignmentStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerifierAssignmentStore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerifierAssignmentStore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifierAssignmentStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVerifierAssignmentStore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVerifierAssignmentStore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVerifierAssignmentStore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVerifierAssignmentStore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerifierAssignmentStore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVerifierAssignmentStore = fmt.Errorf("proto: unexpected end of group")
)
